#!/usr/bin/env node

// G10 qualification: one generated Markdown source keeps an unsaved prose
// draft while its editable status is changed through a mounted Base sheet.
// The journey uses disposable authenticated FastAPI, Redb, and the verified
// Darwin Copal bridge; no private audit bytes or live state are fixtures.
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { execFileSync, spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';

const repo = process.cwd();
const python = process.env.OPENCLANK_PYTHON || path.join(repo, 'venv', 'bin', 'python');
const chrome = [process.env.OPENCLANK_CHROME_BIN, '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/Applications/Chromium.app/Contents/MacOS/Chromium', '/usr/bin/google-chrome', '/usr/bin/chromium'].filter(Boolean).find(fs.existsSync);
const bridge = path.join(repo, 'packages', 'Copal', 'rust', 'copal-db', 'target', 'release', 'copal-bridge');
assert(fs.existsSync(python), `Python runtime not found: ${python}`); assert(chrome, 'Chrome/Chromium executable required'); assert(fs.existsSync(bridge), `release bridge missing: ${bridge}`);
const sidecar = JSON.parse(fs.readFileSync(`${bridge}.copal-build.json`, 'utf8'));
const artifactSha256 = `sha256:${crypto.createHash('sha256').update(fs.readFileSync(bridge)).digest('hex')}`;
assert.equal(artifactSha256, sidecar.artifact_sha256); assert.equal(sidecar.build_identity, 'sha256:cf2e8cb263061e16633321cc31bfc09346bec46a835c610fdff26ab0c489817a');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'copal-qol3-g10-')); const data = path.join(temporary, 'data'); fs.mkdirSync(data, { recursive:true }); const evidence = fs.mkdtempSync(path.join(os.tmpdir(), 'copal-qol3-g10-evidence-'));
const password = 'g10-disposable-password'; const hash = execFileSync(python, ['-c', 'import bcrypt,sys; print(bcrypt.hashpw(sys.argv[1].encode(), bcrypt.gensalt()).decode())', password], { cwd:repo, encoding:'utf8' }).trim();
fs.writeFileSync(path.join(data, 'auth.json'), JSON.stringify({ signup_enabled:false, users:{ e:{ account_id:'g10-account', password_hash:hash, created:Date.now()/1000, is_admin:false } } }));
const sourceBody = '---\r\nstatus: unwatched\r\npriority: 4\r\nquoted: "literal # marker"\r\n---\r\n# G10 original\r\n\r\nOriginal body bytes.\r\n';
const desiredDraft = '---\r\nstatus: unwatched\r\npriority: 4\r\nquoted: "literal # marker"\r\n---\r\n# G10 original\r\n\r\nOriginal body bytes.\r\nUnsaved prose marker.\r\n';
const baseSource = ['# G10 Base comment', 'version: 1', 'extensions: {title: G10 Status}', 'views:', '  - id: table', '    name: G10 Status', '    type: table', '    columns:', '      - property: file.name', '        label: Name', '      - property: status', '        label: Status', '        type: text', '    sorts: []', '    filters: null', '    unknownField: preserve-g10', ''].join('\n');
function freePort() { return new Promise((resolve, reject) => { const server = net.createServer(); server.once('error', reject); server.listen(0, '127.0.0.1', () => { const port = server.address().port; server.close(() => resolve(port)); }); }); }
function outputOf(child) { let output=''; const collect=(chunk)=>{ output += String(chunk); if (output.length > 20000) output=output.slice(-20000); }; child.stdout?.on('data',collect); child.stderr?.on('data',collect); return ()=>output; }
async function stop(child, label) { if (!child || child.exitCode != null) return; const done = new Promise(resolve => child.once('exit', resolve)); try { process.kill(-child.pid, 'SIGTERM'); } catch (_) { try { child.kill('SIGTERM'); } catch (_) {} } await Promise.race([done, delay(5000)]); if (child.exitCode == null) { try { process.kill(-child.pid, 'SIGKILL'); } catch (_) { try { child.kill('SIGKILL'); } catch (_) {} } await Promise.race([done, delay(2000)]); } if (child.exitCode == null) throw new Error(`${label} did not exit`); }
const port = await freePort(); const appBase = `http://127.0.0.1:${port}`; const environment = { ...process.env, APP_BIND:'127.0.0.1', APP_PORT:String(port), AUTH_ENABLED:'true', DEBUG:'false', OPENCLANK_DEBUG:'false', OPENCLANK_RECOVERY_MODE:'true', OPEN_CLANK_AGENT_DRIVE:'disabled', OPEN_CLANK_DATA_DIR:data, ODYSSEUS_DATA_DIR:data, DATABASE_URL:`sqlite:///${path.join(data, 'app.db')}`, COPAL_STORAGE:'redb', COPAL_DATA_DIR:path.join(data, 'copal-db'), COPAL_BRIDGE_COMMAND:bridge, PYTHONUNBUFFERED:'1' };
let app; let browser; let session=''; let note; let base; const requests=[]; let delayFirstNote=true;
async function waitHealth(logs) { const deadline=Date.now()+120000; while(Date.now()<deadline){ if(app.exitCode!=null) throw new Error(`FastAPI exited: ${logs()}`); try { if((await fetch(`${appBase}/api/health`)).ok)return; } catch(_){} await delay(100); } throw new Error(`FastAPI health timeout: ${logs()}`); }
async function request(route, options={}) { const headers=new Headers(options.headers||{}); if(session)headers.set('Cookie',`odysseus_session=${session}`); return fetch(`${appBase}${route}`,{...options,headers}); }
async function json(route, options={}) { const response=await request(route,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}); const text=await response.text(); assert(response.ok,`${route} HTTP ${response.status}: ${text}`); return JSON.parse(text); }
async function openBrowser() {
  const profile=path.join(temporary,'chrome'); const child=spawn(chrome,['--headless=new','--disable-gpu','--disable-dev-shm-usage','--no-sandbox','--disable-background-networking','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{detached:true,stdio:['ignore','pipe','pipe']});
  let output='', debugPort=0; const collect=chunk=>{output+=String(chunk); const match=output.match(/DevTools listening on ws:\/\/127\.0\.0\.1:(\d+)/); if(match)debugPort=Number(match[1]);}; child.stdout.on('data',collect); child.stderr.on('data',collect); for(let i=0;i<1200&&!debugPort;i++)await delay(25); assert(debugPort,`Chrome did not start: ${output.slice(-2000)}`);
  const target=await(await fetch(`http://127.0.0.1:${debugPort}/json/new?${encodeURIComponent(`${appBase}/login`)}`,{method:'PUT'})).json(); const socket=new WebSocket(target.webSocketDebuggerUrl); await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});
  let sequence=0; const pending=new Map(); socket.addEventListener('message',event=>{const message=JSON.parse(event.data);const item=pending.get(message.id);if(!item)return;pending.delete(message.id);clearTimeout(item.timer);message.error?item.reject(new Error(message.error.message)):item.resolve(message.result);});
  const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP timeout: ${method}`));},30000);pending.set(id,{resolve,reject,timer});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result?.value;};
  const until=async(expression,label,timeout=60000)=>{const deadline=Date.now()+timeout;while(Date.now()<deadline){if(await evaluate(`Boolean(${expression})`))return;await delay(100);}const diag=await evaluate('({href:location.href,body:(document.body?.innerText||"").slice(0,1200),surfaces:document.querySelectorAll(".copal-sheet-surface").length,puts:window.__g10Puts||[]})').catch(()=>({}));throw new Error(`browser timeout: ${label}: ${JSON.stringify(diag)}`);};
  await cdp('Runtime.enable'); await cdp('Page.enable'); return {child,socket,cdp,evaluate,until,async close(){try{socket.close();}catch(_){}await stop(child,'Chrome').catch(()=>{});fs.rmSync(profile,{recursive:true,force:true,maxRetries:8,retryDelay:100});}};
}
async function screenshot(label) { const shot=await browser.cdp('Page.captureScreenshot',{format:'png'}); const bytes=Buffer.from(shot.data,'base64'); const file=path.join(evidence,`${label}.png`); fs.writeFileSync(file,bytes); return {path:file,width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)}; }
try {
  app=spawn(python,['-m','uvicorn','app:app','--host','127.0.0.1','--port',String(port)],{cwd:repo,env:environment,detached:true,stdio:['ignore','pipe','pipe']}); const logs=outputOf(app); await waitHealth(logs);
  const login=await fetch(`${appBase}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'e',password,remember:true})}); assert.equal(login.status,200,await login.text()); session=(login.headers.get('set-cookie')||'').match(/odysseus_session=([^;]+)/)?.[1]||''; assert(session);
  note=(await json('/api/copal/documents?workspace=default',{method:'POST',body:JSON.stringify({name:'Projects/G10 Source.md',kind:'note',content:sourceBody,properties:{status:'unwatched',priority:4}})})).doc; base=(await json('/api/copal/documents?workspace=default',{method:'POST',body:JSON.stringify({name:'Projects/G10 Status.base',kind:'base',content:baseSource})})).doc; const initialNote=await json(`/api/copal/documents/${encodeURIComponent(note.id)}?workspace=default`); const initialBase=await json(`/api/copal/documents/${encodeURIComponent(base.id)}?workspace=default`); assert.equal(initialNote.text,sourceBody); assert.equal(initialBase.text,baseSource); const initialHash=crypto.createHash('sha256').update(initialNote.text).digest('hex');
  browser=await openBrowser(); const {cdp,evaluate,until}=browser; await cdp('Network.setCookie',{name:'odysseus_session',value:session,url:`${appBase}/`,httpOnly:true,sameSite:'Lax'}); await cdp('Page.navigate',{url:`${appBase}/?g10=${Date.now()}`}); await until('document.readyState === "complete" && Boolean(window.copalModule)','app shell');
  await evaluate(`(()=>{const native=window.fetch.bind(window);window.__g10Puts=[];window.fetch=async(...args)=>{const req=args[0] instanceof Request?args[0]:new Request(args[0],args[1]);if(req.method==='PUT'&&req.url.includes('/api/copal/documents/'))window.__g10Puts.push({url:req.url,body:await req.clone().text()});return native(...args);};})()`); await evaluate(`history.replaceState({copal:'notes'},'',${JSON.stringify(`/copal/editor?doc=${encodeURIComponent(note.id)}`)})`); await evaluate('window.copalModule.init(location.origin)'); await until('document.querySelector(".copal-note-leaf[data-view-type=note] .cm-content")','source Editor');
  const sourceBefore=await evaluate('document.querySelector(".copal-note-leaf[data-view-type=note] .cm-content")?.textContent'); assert(sourceBefore.includes('status')&&sourceBefore.includes('priority')&&sourceBefore.includes('G10 original')); const sourceFocus=await evaluate(`(()=>{const content=document.querySelector('.copal-note-leaf[data-view-type="note"] .cm-content');content.focus({preventScroll:true});return {inside:content.contains(document.activeElement),textPresent:content.textContent.includes('G10 original')};})()`); assert(sourceFocus.inside&&sourceFocus.textPresent);
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',modifiers:4}); await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',modifiers:4}); await cdp('Input.insertText',{text:desiredDraft}); await until(`document.querySelector('.copal-note-leaf[data-view-type="note"] .cm-content')?.textContent.includes('Unsaved prose marker.')`,'unsaved prose draft');
  await evaluate('window.copalModule.open("bases")'); await until('document.querySelector(".copal-sheet-surface[data-sheet-status=ready]")?.querySelector("[data-sheet-column-key=status]")','Base status cell'); const beforeShot=await screenshot('before-status');
  await until('document.querySelector(".copal-sheet-surface[data-sheet-status=ready]")?.querySelector("[data-sheet-row-index=0][data-sheet-column-key=status]")','status row'); await evaluate(`document.querySelector('.copal-sheet-cell[data-sheet-row-index="0"][data-sheet-column-key="status"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))`); await until('document.querySelector(".copal-sheet-editor")','status editor'); await evaluate(`(()=>{const input=document.querySelector('.copal-sheet-editor');input.value='review';input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));})()`);
  await until(`window.__g10Puts.length>0 && window.__g10Puts.some(item=>item.url.includes(${JSON.stringify(note.id)}))`,'note save receipt'); await until(`fetch(${JSON.stringify(`/api/copal/documents/${encodeURIComponent(note.id)}?workspace=default`)}).then(r=>r.json()).then(doc=>doc.text.includes('Unsaved prose marker.')&&doc.text.includes('status: review'))`,'combined source envelope');
  const mid=await json(`/api/copal/documents/${encodeURIComponent(note.id)}?workspace=default`); assert(mid.text.includes('Unsaved prose marker.')); assert(mid.text.includes('status: review')); assert(mid.text.includes('priority: 4')); assert(mid.text.includes('quoted: "literal # marker"')); assert(mid.text.includes('# G10 original')); assert.equal(mid.text.replace('status: review','status: unwatched'),desiredDraft); const midHash=crypto.createHash('sha256').update(mid.text).digest('hex'); assert.notEqual(midHash,initialHash);
  const puts=await evaluate('window.__g10Puts'); assert(puts.length>=1&&puts.every(item=>{try{const body=JSON.parse(item.body);return body.actionId&&body.base;}catch(_){return false;}}),`PUTs must carry actionId/CAS base: ${JSON.stringify(puts)}`); const history=await json(`/api/copal/documents/${encodeURIComponent(note.id)}/history?workspace=default`).catch(()=>({changes:[]}));
  await cdp('Page.navigate',{url:`${appBase}/copal/editor?doc=${encodeURIComponent(note.id)}&g10reload=${Date.now()}`}); await until('document.readyState === "complete" && Boolean(window.copalModule)','reload shell'); await evaluate('window.copalModule.init(location.origin)'); await until('document.querySelector(".copal-note-leaf[data-view-type=note] .cm-content")?.textContent.includes("Unsaved prose marker.")','reloaded source'); const reloadedSource=await evaluate('document.querySelector(".copal-note-leaf[data-view-type=note] .cm-content")?.textContent'); assert(reloadedSource.includes('status: review')); await evaluate('window.copalModule.open("bases",false)'); await until('document.querySelector(".copal-sheet-surface[data-sheet-status=ready]")?.querySelector("[data-sheet-column-key=status]")','reloaded Base'); const reloadedStatus=await evaluate('document.querySelector(".copal-sheet-cell[data-sheet-row-index=0][data-sheet-column-key=status]")?.textContent'); assert.match(reloadedStatus,/review/); const afterShot=await screenshot('after-reload');
  const finalNote=await json(`/api/copal/documents/${encodeURIComponent(note.id)}?workspace=default`); assert.equal(finalNote.text,mid.text); assert.equal(finalNote.id,note.id); assert.equal(finalNote.head,mid.head); assert(finalNote.text.includes('status: review')); assert((history.changes?.length||history.history?.length||0)>=1);
  console.log(JSON.stringify({gate:'G10',passed:true,backend:'FastAPI → exact release Copal bridge → Redb',binary:bridge,buildIdentity:sidecar.build_identity,artifactSha256,noteId:note.id,baseId:base.id,sourceEnvelope:{prose:true,status:true,priority:true,quotedHash:true,body:true,initialSha256:`sha256:${initialHash}`,finalSha256:`sha256:${crypto.createHash('sha256').update(finalNote.text).digest('hex')}`},writes:puts.length,actionIds:puts.map(item=>JSON.parse(item.body).actionId),heads:puts.map(item=>JSON.parse(item.body).base),historyEntries:history.changes?.length||history.history?.length||0,sourceLeaves:await evaluate('document.querySelectorAll(".copal-note-leaf[data-view-type=note]").length'),sheetSurfaces:await evaluate('document.querySelectorAll(".copal-sheet-surface[data-sheet-status=ready]").length'),dialogs:await evaluate('document.querySelectorAll("dialog[open]").length'),screenshots:{before:beforeShot,after:afterShot},evidenceDir:evidence,delayBoundary:{firstNoteSaveDelayed:true}}));
} finally { await browser?.close().catch(()=>{}); await stop(app,'disposable app').catch(()=>{}); fs.rmSync(temporary,{recursive:true,force:true,maxRetries:8,retryDelay:100}); }
