#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';

const root=process.cwd();
const source=fs.readFileSync(path.join(root,'static/js/copal.js'),'utf8');
const injection=String.raw`
window.__graphTest={
 setup({account='acct-a',workspace='ws-a',docs=[],planning={tracks:[],floatingTodos:[]},drafts={},sourceDocId=null,body}){
  for (const modal of [...document.querySelectorAll('.copal-tool-modal')]) (modal.__openClankWindow||modal.__copalWindow)?.destroy?.();
  configureCopalStorage('graph-test'); localStorage.removeItem(graphStorageKey(account, workspace)); state.accountId=account; state.workspace=workspace; state.storageNamespace='graph-test'; state.contextEpoch=1; state.docs=docs; state.planning=planning; state.filter=''; state.selected=null; state.view='graph'; state.body=body; state.root=document.body; state.content=body;
  state.windows.clear(); state.windows.set('graph',{view:'graph',body,window:{body,content:body,root:body,visible:true,setStatus(){},show(){},focus(){}} ,selected:null,filter:'',story:[],pinned:new Set(),reading:false});
  planningFeature={openTrackEditor(id){window.__graphTest.handoffs.push(['track',id]);},openEventEditor(id){window.__graphTest.handoffs.push(['event',id]);}};
  window.__graphTest.drafts=drafts; window.__graphTest.transactions=[];
  notesFeature={open(id){window.__graphTest.handoffs.push(['note',id]);},render(){},getDraftSnapshot(id){const draft=window.__graphTest.drafts[id];if(!draft)return null;return {expectedRevision:draft.expectedRevision,localRevision:draft.localRevision||0,envelope:{text:draft.text}};} ,applyDocumentTransaction(doc,transform){const draft=window.__graphTest.drafts[doc.id]||{text:String(doc.text||''),expectedRevision:{kind:'copalHead',value:String(doc.head||'')},localRevision:0};const content=transform(draft.text);draft.text=content;draft.localRevision=(draft.localRevision||0)+1;doc.text=content;window.__graphTest.transactions.push({id:doc.id,content});return {outcome:'queued',content,localRevision:draft.localRevision};}};
  graphView=null; graphScopeKey=null; window.__graphTest.handoffs=[];
 },
 render(){renderGraph();},
 renderMind(){renderMind();},
 setSource(id){getGraphView().source={kind:'document',docId:String(id)};getGraphView().modes.structure.navigation.docId=String(id);},
 actual(){renderGraph();},
 renderProjection(mode, nodes, edges, facets=null){const body=state.body;body.replaceChildren(graphSvg(nodes,edges,node=>window.__graphTest.handoffs.push(['open',node.kind,node.selection||node.id]),mode,facets));},
 route(view,mode){return resolveView(view,mode);},
 snapshot(){return structuredClone(getGraphView());},
 context(){return {view:state.view,selected:state.selected};},
 graphState(){return {docs:documentGraph(state.docs,findByName),galaxy:galaxyGraph(planningData().tracks||[],allPlanningTasks(planningData()))};},
 mindTransactions(){return window.__graphTest.transactions.slice();},
 handoffs:[]
};`;
const copal=source.replace('export default { init,',injection+'\nexport default { init,');
const page=`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/static/style.css"><style>html,body{margin:0;background:#17202a;color:#eee}#graph{width:1100px;height:760px}</style><main id="graph" data-window-id="graph-test"></main><script type="module">import { registerInputContext, activateInputContext } from "/static/js/copal/inputContext.js"; import "/static/js/copal.js"; window.__ready=()=>Boolean(window.__graphTest); window.__register=()=>{const b=document.querySelector('#graph');const c={windowId:'graph-test',paneId:'graph',capabilities:{keyboard:true,pointer:true,wheel:true}};registerInputContext(b,c);activateInputContext(c);};</script>`;
const server=http.createServer((req,res)=>{if(req.url==='/'){res.writeHead(200,{'content-type':'text/html'});res.end(page);return;}if(req.url==='/static/js/copal.js'){res.writeHead(200,{'content-type':'text/javascript'});res.end(copal);return;}if(req.url.startsWith('/static/')){const file=path.join(root,req.url.slice(1));if(!file.startsWith(path.join(root,'static'))){res.writeHead(403);res.end();return;}try{const type=file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream';res.writeHead(200,{'content-type':type});res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}return;}res.writeHead(404);res.end();});
let browser,ws,serverClosed=false; let serverPort;
try {
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); serverPort=server.address().port;
 const chrome=['/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'].find(fs.existsSync); assert(chrome,'Chrome executable required');
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'copal-graph-')); browser=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu',`--user-data-dir=${profile}`,'--remote-debugging-port=0','about:blank'],{stdio:['ignore','pipe','pipe']});
 let port; const listen=chunk=>{const m=String(chunk).match(/DevTools listening on ws:\/\/127\.0\.0\.1:(\d+)/);if(m)port=Number(m[1]);};browser.stdout.on('data',listen);browser.stderr.on('data',listen);for(let i=0;!port&&i<150;i++)await delay(20);assert(port,'DevTools did not start');
 const target=await (await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`http://127.0.0.1:${serverPort}/`)}`,{method:'PUT'})).json();
 ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});let seq=0;const pending=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}});
 const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,m=>m.error?reject(new Error(m.error.message)):resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
 const evalPage=async(expression,awaitPromise=true)=>{const r=await cdp('Runtime.evaluate',{expression,awaitPromise,returnByValue:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result?.value;};
 await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1400,height:1000,deviceScaleFactor:1,mobile:false});await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 for(let i=0;i<150;i++){if(await evalPage('window.__ready?.()'))break;await delay(20);}assert(await evalPage('window.__ready?.()'),'Graph fixture did not load');
 const docs=[{id:'note-1',name:'Alpha.md',kind:'note',text:'Alpha',links:['Wiki.md'],relations:[{targetDocumentId:'wiki-1',kind:'embed'}]},{id:'wiki-1',name:'Wiki.md',kind:'wiki',text:'Wiki',links:[],relations:[]}];
 const planning={tracks:[{id:'track-1',name:'Track One',tasks:[{id:'event-1',title:'Shared Event',startDate:'2026-01-01',dueDate:'2026-01-02',primaryTrackId:'track-1',sharedTrackIds:['track-2']}]},{id:'track-2',name:'Track Two',tasks:[]}],floatingTodos:[]};
 await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({docs,planning})},{body:document.querySelector('#graph')}));window.__register();window.__graphTest.render()`);await delay(40);
 const report=[];
 const nav=await evalPage(`({mode:document.querySelector('[data-graph-mode]').value,graph:location.pathname,options:[...document.querySelectorAll('[data-graph-mode] option')].map(x=>x.value),nodes:document.querySelectorAll('.copal-graph-node').length})`);assert.equal(nav.mode,'documents');assert.deepEqual(nav.options,['documents','structure','galaxy']);report.push({case:'single Graph destination',nav});
 await evalPage(`(()=>{const s=document.querySelector('[data-graph-mode]');s.value='galaxy';s.dispatchEvent(new Event('change',{bubbles:true}))})()`);await delay(20);const actualGalaxy=await evalPage(`({mode:document.querySelector('[data-graph-mode]').value,nodes:[...document.querySelectorAll('.copal-graph-node')].map(n=>n.dataset.graphId)})`);assert.equal(actualGalaxy.mode,'galaxy');assert(actualGalaxy.nodes.includes('event:event-1'));report.push({case:'actual mode selector/renderGraph',actualGalaxy});
 await evalPage(`(()=>{const s=document.querySelector('[data-graph-mode]');s.value='documents';s.dispatchEvent(new Event('change',{bubbles:true}))})()`);await delay(20);
 const projections=await evalPage('window.__graphTest.graphState()');assert.equal(projections.docs.edges.length,2);assert.equal(projections.galaxy.nodes.filter(n=>n.id==='event:event-1').length,1);assert.equal(projections.galaxy.edges.length,2);report.push({case:'document and Galaxy projections',documentEdges:projections.docs.edges.map(e=>e.type),galaxyEdges:projections.galaxy.edges.map(e=>e.type)});
 await evalPage(`window.__graphTest.renderProjection('documents',window.__graphTest.graphState().docs.nodes,window.__graphTest.graphState().docs.edges);document.querySelector('.copal-graph-search').value='Wiki';document.querySelector('.copal-graph-search').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.copal-graph-ctrl[title="Zoom in"]').click()`);await delay(20);const docState=await evalPage('window.__graphTest.snapshot()');assert.equal(docState.mode,'documents');assert.equal(docState.modes.documents.filters.search,'Wiki');assert.notDeepEqual(docState.modes.documents.camera,{x:0,y:0,w:1000,h:650});
 await evalPage(`window.__graphTest.renderProjection('galaxy',window.__graphTest.graphState().galaxy.nodes,window.__graphTest.graphState().galaxy.edges);document.querySelector('.copal-graph-search').value='Track';document.querySelector('.copal-graph-search').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.copal-graph-ctrl[title="Zoom out"]').click()`);const both=await evalPage('window.__graphTest.snapshot()');assert.equal(both.modes.documents.filters.search,'Wiki');assert.equal(both.modes.galaxy.filters.search,'Track');assert.notDeepEqual(both.modes.documents.camera,both.modes.galaxy.camera);report.push({case:'mode-scoped filter/camera restore',documents:both.modes.documents,galaxy:both.modes.galaxy});
 await evalPage(`window.__graphTest.renderProjection('documents',window.__graphTest.graphState().docs.nodes,window.__graphTest.graphState().docs.edges)`);const restored=await evalPage('window.__graphTest.snapshot()');assert.equal(restored.modes.documents.filters.search,'Wiki');
 await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({account:'acct-b',workspace:'ws-b',docs,planning})},{body:document.querySelector('#graph')}));window.__graphTest.render()`);const isolated=await evalPage('window.__graphTest.snapshot()');assert.equal(isolated.mode,'documents');assert.equal(isolated.modes.documents.filters.search,'');report.push({case:'owner/workspace invalidation',scope:'acct-b/ws-b',search:isolated.modes.documents.filters.search});
 const route=await evalPage(`({view:window.__graphTest.route('galaxy'),mode:window.__graphTest.snapshot().mode})`);assert.deepEqual(route,{view:'graph',mode:'galaxy'});report.push({case:'legacy Galaxy route alias',route});
 await evalPage(`window.__graphTest.route('graph','documents');window.__graphTest.render();document.querySelector('.copal-graph-search').value='Wiki';document.querySelector('.copal-graph-search').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-graph-id="document:wiki-1"]').focus()`);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});const focused=await evalPage('document.activeElement?.getAttribute("data-graph-id")');const hidden=await evalPage('(()=>{const node=document.querySelector("[data-graph-id=\\"document:note-1\\"]");return node ? getComputedStyle(node).display : "unmounted"})()');assert.ok(hidden==='none' || hidden==='unmounted');assert.equal(focused,'document:wiki-1');report.push({case:'trusted filtered keyboard node navigation',focused,hidden});
 await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({docs,planning})},{body:document.querySelector('#graph')}));window.__graphTest.actual();window.__graphTest.handoffs=[];document.querySelector('[data-graph-id="document:wiki-1"]').dispatchEvent(new MouseEvent('click',{bubbles:true}))`);assert.deepEqual(await evalPage('window.__graphTest.handoffs'),[]);await evalPage(`document.querySelector('[data-graph-id="document:wiki-1"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))`);assert.deepEqual(await evalPage('window.__graphTest.handoffs'),[['note','wiki-1']]);await delay(20);assert.deepEqual(await evalPage('window.__graphTest.context()'),{view:'notes',selected:'wiki-1'});await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({docs,planning})},{body:document.querySelector('#graph')}));window.__graphTest.actual();window.__graphTest.handoffs=[];document.querySelector('[data-graph-id="document:wiki-1"]').dispatchEvent(new MouseEvent('click',{bubbles:true}))`);assert.deepEqual(await evalPage('window.__graphTest.handoffs'),[]);assert.deepEqual(await evalPage('window.__graphTest.context()'),{view:'graph',selected:null});await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({docs,planning})},{body:document.querySelector('#graph')}));window.__graphTest.route('galaxy');window.__graphTest.actual();window.__graphTest.handoffs=[];document.querySelector('[data-graph-id="track:track-1"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));document.querySelector('[data-graph-id="event:event-1"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))`);assert.deepEqual(await evalPage('window.__graphTest.handoffs'),[['track','track-1'],['event','event-1']]);report.push({case:'actual document/wiki/track/event handoffs',handoffs:await evalPage('window.__graphTest.handoffs')});
 await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({docs,planning})},{body:document.querySelector('#graph')}));window.__register();window.__graphTest.route('graph','documents');window.__graphTest.actual()`);const beforePan=await evalPage('document.querySelector(".copal-graph").getAttribute("viewBox")');const rect=await evalPage('(()=>{const r=document.querySelector(".copal-graph").getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}})()');const px=rect.x+40,py=rect.y+rect.h-30;await cdp('Input.dispatchMouseEvent',{type:'mousePressed',x:px,y:py,button:'left',buttons:1,clickCount:1});await delay(20);await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',x:px+20,y:py,button:'left',buttons:1});await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',x:px+100,y:py,button:'left',buttons:1});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',x:px+100,y:py,button:'left',buttons:0,clickCount:1});await delay(30);const pan=await evalPage('document.querySelector(".copal-graph").getAttribute("viewBox")');assert.notEqual(pan,beforePan,JSON.stringify({beforePan,pan,rect,element:await evalPage(`document.elementFromPoint(${px},${py})?.tagName`)}));report.push({case:'trusted reduced-motion pan',before:beforePan,after:pan});
 const corpus=Array.from({length:5001},(_,index)=>({id:`doc-${index}`,name:`Corpus ${index}`,label:`Corpus ${index}`,kind:'note'}));await evalPage(`window.__graphTest.renderProjection('documents',${JSON.stringify(corpus)},[])`);await evalPage(`(()=>{const input=document.querySelector('.copal-graph-search');input.value='Corpus 5000';input.dispatchEvent(new Event('input',{bubbles:true}))})()`);const bounded=await evalPage('({mounted:document.querySelectorAll(".copal-graph-node").length,match:document.querySelector("[data-graph-id=\\"doc-5000\\"]")?.getAttribute("data-graph-id"),info:document.querySelector(".copal-graph-info")?.textContent})');assert(bounded.mounted<=300);assert.equal(bounded.match,'doc-5000');assert.match(bounded.info,/1 nodes and 0 edges/);report.push({case:'5,001 bounded search remount',bounded});await evalPage(`(()=>{const input=document.querySelector('.copal-graph-search');input.value='';input.dispatchEvent(new Event('input',{bubbles:true}))})()`);const layout=await evalPage('(()=>{const circles=[...document.querySelectorAll(".copal-graph-node circle")];const pairs=circles.map(c=>`${c.getAttribute("cx")},${c.getAttribute("cy")}`);const xs=circles.map(c=>Number(c.getAttribute("cx")));return {mounted:circles.length,distinct:new Set(pairs).size,span:Math.max(...xs)-Math.min(...xs)}})()');assert.equal(layout.mounted,300);assert(layout.distinct>200);assert(layout.span>700);report.push({case:'bounded spatial layout',layout});
 await evalPage(`window.__graphTest.setup(Object.assign({account:'acct-5001',workspace:'ws-5001',docs:${JSON.stringify(corpus)},planning:{tracks:[],floatingTodos:[]}},{body:document.querySelector('#graph')}));window.__graphTest.renderMind()`);const mindBounded=await evalPage('({rows:document.querySelectorAll(".copal-mind-doc-item").length,status:document.querySelector(".copal-mind-picker-status")?.textContent})');assert(mindBounded.rows<=101);assert.match(mindBounded.status,/5001/);await evalPage(`(()=>{const input=document.querySelector('.copal-mind-doc-search');input.value='Corpus 5000';input.dispatchEvent(new Event('input',{bubbles:true}))})()`);const mindSearch=await evalPage('document.querySelectorAll(".copal-mind-doc-item").length');assert.equal(mindSearch,1);report.push({case:'5,001 bounded Mind source picker',mindBounded,mindSearch});
 const mindText='---\ntitle: Fixture\n---\n# Root\n```md\n# Fake\n```\n## Child\n# Sibling\nBody';
 const mindDoc={id:'mind-doc',name:'Mind.md',kind:'note',text:'Saved only',head:'mind-head-1',resource:{key:{accountId:'acct-mind',workspaceId:'ws-mind',provider:'copal',resourceId:'mind-resource'}},links:[],relations:[]};
 await evalPage(`window.__graphTest.setup({account:'acct-mind',workspace:'ws-mind',docs:${JSON.stringify([mindDoc])},drafts:{'mind-doc':{text:${JSON.stringify(mindText)},expectedRevision:{kind:'copalHead',value:'mind-head-1'},localRevision:4}},body:document.querySelector('#graph')});window.__graphTest.setSource('mind-doc');window.__graphTest.renderMind()`);
 const mindShape=await evalPage('({rows:[...document.querySelectorAll(".copal-mind-tree-label")].map(node=>node.textContent),count:document.querySelectorAll(".copal-mind-tree-node").length})');assert.equal(mindShape.count,3);assert.deepEqual(mindShape.rows.map(value=>value.trim()),['Root','Child','Sibling']);report.push({case:'mounted unsaved Mind draft excludes frontmatter/fenced fake headings',mindShape});
 const beforeRename=(await evalPage('window.__graphTest.mindTransactions()')).length;
 await evalPage(`(()=>{const label=[...document.querySelectorAll('.copal-mind-tree-label')].find(item=>item.textContent.trim()==='Child');label.closest('.copal-mind-tree-node').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));const input=document.querySelector('.copal-mind-tree-input');input.value='Renamed';input.dispatchEvent(new Event('blur'))})()`);await delay(10);assert.equal((await evalPage('window.__graphTest.mindTransactions()')).length,beforeRename+1);assert.match(await evalPage('window.__graphTest.drafts["mind-doc"].text'),/## Renamed/);
 await evalPage(`(()=>{document.querySelector('[data-line="8"]')?.click();[...document.querySelectorAll('.copal-mind-toolbar button')].find(button=>button.textContent==='+ Heading').click()})()`);await delay(10);assert.equal((await evalPage('window.__graphTest.mindTransactions()')).length,beforeRename+2);assert.match(await evalPage('window.__graphTest.drafts["mind-doc"].text'),/## New heading/);
 const reparentCount=(await evalPage('window.__graphTest.mindTransactions()')).length;
 await evalPage(`(()=>{const nodes=[...document.querySelectorAll('.copal-mind-tree-node')];const source=nodes.find(item=>item.textContent.includes('Sibling'));const target=nodes.find(item=>item.textContent.includes('Root'));const transfer=new DataTransfer();source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('dragover',{bubbles:true,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}))})()`);await delay(10);assert.equal((await evalPage('window.__graphTest.mindTransactions()')).length,reparentCount+1);
 const cycleCount=(await evalPage('window.__graphTest.mindTransactions()')).length;
 await evalPage(`(()=>{const nodes=[...document.querySelectorAll('.copal-mind-tree-node')];const source=nodes.find(item=>item.textContent.includes('Root'));const target=nodes.find(item=>item.textContent.includes('Renamed'));const transfer=new DataTransfer();source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('dragover',{bubbles:true,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}))})()`);assert.equal((await evalPage('window.__graphTest.mindTransactions()')).length,cycleCount);
 await evalPage(`(()=>{const nodes=[...document.querySelectorAll('.copal-mind-tree-node')];const source=nodes.find(item=>item.textContent.includes('Root'));const target=nodes.find(item=>item.textContent.includes('Renamed'));const transfer=new DataTransfer();source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));window.__graphTest.drafts['mind-doc'].localRevision+=1;target.dispatchEvent(new DragEvent('dragover',{bubbles:true,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}))})()`);assert.equal((await evalPage('window.__graphTest.mindTransactions()')).length,cycleCount);
 const readOnlyDoc={...mindDoc,id:'readonly-doc',name:'Read only.md',readOnly:true};await evalPage(`window.__graphTest.setup({account:'acct-mind',workspace:'ws-mind',docs:${JSON.stringify([readOnlyDoc])},drafts:{'readonly-doc':{text:${JSON.stringify(mindText)},expectedRevision:{kind:'copalHead',value:'mind-head-1'},localRevision:0}},body:document.querySelector('#graph')});window.__graphTest.setSource('readonly-doc');window.__graphTest.renderMind()`);assert.equal(await evalPage('document.querySelector(".copal-mind-tree-node")?.draggable'),false);assert.equal(await evalPage('(()=>{const n=document.querySelector(".copal-mind-tree-node");const d=new DataTransfer();n.dispatchEvent(new DragEvent("dragstart",{bubbles:true,dataTransfer:d}));const event=new DragEvent("dragover",{bubbles:true,dataTransfer:d});n.dispatchEvent(event);return d.dropEffect})()'),'none');
 const stateCases=[
  {id:'base-source',doc:{id:'base-source',name:'View.base',kind:'base',text:'version: 1',head:'base-1'},title:'Mind source unsupported'},
  {id:'missing-source',doc:null,title:'Mind source unavailable'},
  {id:'parse-source',doc:{id:'parse-source',name:'Broken.md',kind:'note',text:'',head:'parse-1',rawPreserved:true,recoveryState:'malformed-preserved',note_error:'native parse failed'},title:'Mind source parse failed'},
  {id:'empty-source',doc:{id:'empty-source',name:'Empty.md',kind:'note',text:'plain body',head:'empty-1'},title:'No headings or bullets found in this source'},
 ];
 for (const item of stateCases) { const docs=item.doc?[item.doc]:[]; await evalPage(`window.__graphTest.setup({account:'acct-state',workspace:'ws-state',docs:${JSON.stringify(docs)},body:document.querySelector('#graph')});window.__graphTest.setSource(${JSON.stringify(item.id)});window.__graphTest.renderMind()`);await delay(2);assert.match(await evalPage('document.body.textContent'),new RegExp(item.title.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&'))); }
 report.push({case:'mounted Mind mutations reject cycle/stale/read-only and expose unsupported/missing/parse/no-heading states',transactions:await evalPage('window.__graphTest.mindTransactions().length')});
 // S20: legacy Mind entrypoints resolve into Graph structure mode, not a
 // separate Mind surface. The mode vocabulary is Documents/Structure/Galaxy.
 await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({docs,planning})},{body:document.querySelector('#graph')}));window.__graphTest.route('mind')`);const mindRoute=await evalPage(`({view:window.__graphTest.route('mind'),mode:window.__graphTest.snapshot().mode,options:[...document.querySelectorAll('[data-graph-mode] option')].map(x=>x.value)})`);assert.equal(mindRoute.view,'graph');assert.equal(mindRoute.mode,'structure');assert.ok(!mindRoute.options.includes('mind'),'Mind is not a separate Graph mode');report.push({case:'legacy Mind resolves to Graph structure mode',mindRoute});
 // S20: wheel zoom is pointer-anchored and moves the camera without buttons.
 await evalPage(`window.__graphTest.setup(Object.assign(${JSON.stringify({docs,planning})},{body:document.querySelector('#graph')}));window.__register();window.__graphTest.route('graph','documents');window.__graphTest.actual()`);const beforeWheel=await evalPage('document.querySelector(".copal-graph").getAttribute("viewBox")');const wrect=await evalPage(`(()=>{const r=document.querySelector(".copal-graph").getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}})()`);const wx=wrect.x+wrect.w/2,wy=wrect.y+wrect.h/2;await cdp('Input.dispatchMouseEvent',{type:'mouseWheel',x:wx,y:wy,deltaX:0,deltaY:-120,button:'none',buttons:0});await delay(30);const afterWheel=await evalPage('document.querySelector(".copal-graph").getAttribute("viewBox")');assert.notEqual(afterWheel,beforeWheel,JSON.stringify({beforeWheel,afterWheel}));report.push({case:'pointer-anchored wheel zoom',before:beforeWheel,after:afterWheel});
 const fitBefore=await evalPage('document.querySelector(".copal-graph").getAttribute("viewBox")');await evalPage(`document.querySelector('.copal-graph-ctrl[title="Fit graph"]').click()`);await delay(20);const fitAfter=await evalPage('document.querySelector(".copal-graph").getAttribute("viewBox")');assert.notEqual(fitAfter,fitBefore);report.push({case:'Fit control reframes mounted content',fitBefore,fitAfter});
 // S20: real facet filters and the official-docs default come from scoped
 // metadata, not a hardcoded kind allowlist.
 const facetDocs=[{id:'p1',name:'Notes/Personal.md',kind:'note',tags:['keep'],properties:{status:'open'},text:'personal'},{id:'o1',name:'OpenClank/Start Here',kind:'note',tags:['builtin'],properties:{product:'open-clank',builtin:true},builtin:true,text:'official'}];
 await evalPage(`window.__graphTest.setup(Object.assign({account:'acct-facet',workspace:'ws-facet',docs:${JSON.stringify(facetDocs)},planning:{tracks:[],floatingTodos:[]}},{body:document.querySelector('#graph')}));window.__graphTest.actual()`);await delay(20);const officialDefault=await evalPage(`({mounted:document.querySelectorAll('.copal-graph-node').length,official:document.querySelector('[data-graph-id="document:o1"]')!==null})`);assert.equal(officialDefault.official,false,'official docs are hidden by default');assert.equal(officialDefault.mounted,1);await evalPage(`(()=>{const t=document.querySelector('.copal-graph-official input');t.checked=true;t.dispatchEvent(new Event('change',{bubbles:true}))})()`);await delay(20);const officialShown=await evalPage(`document.querySelector('[data-graph-id="document:o1"]')!==null`);assert.equal(officialShown,true,'official docs are explicitly includable');report.push({case:'official docs excluded by default and includable',officialDefault,officialShown});
 await evalPage(`(()=>{const group=[...document.querySelectorAll('.copal-graph-facet-group')].find(g=>g.dataset.facetGroup==='Tag');const input=group.querySelector('input');input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}))})()`);await delay(20);const tagFiltered=await evalPage(`({nodes:document.querySelectorAll('.copal-graph-node').length,info:document.querySelector('.copal-graph-info')?.textContent})`);report.push({case:'real tag facet filter',tagFiltered});
 // S20: structure mode shows nested bullets beside headings, and a source
 // without structure gets a useful empty state.
 const structureText='# Root\n- top\n  - nested\n## Child\n\nJust prose after.';
 const structureDoc={id:'structure-doc',name:'Structure.md',kind:'note',text:'saved',head:'sh-1',resource:{key:{accountId:'acct-structure',workspaceId:'ws-structure',provider:'copal',resourceId:'structure-res'}},links:[],relations:[]};
 await evalPage(`window.__graphTest.setup({account:'acct-structure',workspace:'ws-structure',docs:${JSON.stringify([structureDoc])},drafts:{'structure-doc':{text:${JSON.stringify(structureText)},expectedRevision:{kind:'copalHead',value:'sh-1'},localRevision:0}},body:document.querySelector('#graph')});window.__graphTest.setSource('structure-doc');window.__graphTest.renderMind()`);const structureShape=await evalPage('({rows:[...document.querySelectorAll(".copal-mind-tree-label")].map(node=>node.textContent.trim()),kinds:[...document.querySelectorAll(".copal-mind-tree-node")].map(node=>node.dataset.structureKind)})');assert.deepEqual(structureShape.rows,['Root','top','nested','Child']);assert.deepEqual(structureShape.kinds,['heading','bullet','bullet','heading'],'nested bullets appear as bullet structure nodes');report.push({case:'structure mode shows headings and nested bullets',structureShape});

 console.log(JSON.stringify({passed:report},null,2));
} finally {if(ws)ws.close();if(browser){browser.kill('SIGTERM');if(browser.exitCode===null)browser.kill('SIGKILL');}if(!serverClosed){serverClosed=true;await new Promise(resolve=>server.close(resolve));}}
