#!/usr/bin/env node
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import zlib from 'node:zlib';
import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';

const root = process.cwd();
const fixture = String.raw`import { createPlanningFeature } from '/static/js/copal/planning.js';
import { configureCopalStorage } from '/static/js/copal/storage.js';
import { getActiveInputContext, resolveInputContext } from '/static/js/copal/inputContext.js';
configureCopalStorage('timeline-geometry-acceptance');
const h=(tag,attrs={},...children)=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k==='text')n.textContent=v;else if(k.startsWith('on')&&typeof v==='function')n.addEventListener(k.slice(2).toLowerCase(),v);else if(v===true)n.setAttribute(k,'');else if(v!==false&&v!=null)n.setAttribute(k,String(v));}for(const c of children.flat())if(c!=null)n.append(c.nodeType?c:document.createTextNode(String(c)));return n;};
const date=(s)=>new Date(s+'T00:00:00'); const fmt=(d)=>d.toISOString().slice(0,10);
const data={title:'Geometry fixture',tracks:[
 {id:'parent',name:'Parent',color:'#5ebfe3',enabled:true,tasks:[
  {id:'single',trackId:'parent',title:'Single day',startDate:'2024-02-25',dueDate:'2024-02-25',status:'pending',priority:'medium'},
 {id:'long',trackId:'parent',title:'Long span',startDate:'2024-03-01',dueDate:'2024-03-05',status:'pending',priority:'medium'},
 {id:'leap',trackId:'parent',title:'Leap day',startDate:'2024-02-28',dueDate:'2024-03-01',status:'pending',priority:'medium'},
  {id:'year',trackId:'parent',title:'Year boundary',startDate:'2024-12-31',dueDate:'2025-01-01',status:'pending',priority:'medium'},
  {id:'dst',trackId:'parent',title:'DST boundary',startDate:'2024-03-09',dueDate:'2024-03-11',status:'pending',priority:'medium'},
  {id:'dst-fall',trackId:'parent',title:'DST fall boundary',startDate:'2024-11-02',dueDate:'2024-11-04',status:'pending',priority:'medium'}]},
 {id:'child',name:'Child',color:'#f97316',enabled:true,parentTrackId:'parent',tasks:[
  {id:'child-event',trackId:'child',title:'Nested child',startDate:'2024-02-28',dueDate:'2024-03-01',status:'pending',priority:'medium'}]},
]};
const calls=[]; const bodyA=document.querySelector('#a'); const bodyB=document.querySelector('#b');
const originalDates=new Map(data.tracks.flatMap(t=>t.tasks).map(e=>[e.id,[e.startDate,e.dueDate]]));
const planning=createPlanningFeature({h,api:async(path,options={})=>{const payload=JSON.parse(options.body||'{}');calls.push({path,payload});const id=decodeURIComponent(path.split('/').pop());const event=data.tracks.flatMap(t=>t.tasks).find(e=>e.id===id);if(event&&payload.patch)Object.assign(event,payload.patch);return {event};},getPlanning:()=>data,refresh:async()=>{},setStatus:()=>{},projectionChanged:()=>{},openDocument:()=>{}}); planning.loadState('geometry');
function configure(rangeStart,rangeEnd,width,scale=1){for(const e of data.tracks.flatMap(t=>t.tasks)){const d=originalDates.get(e.id);[e.startDate,e.dueDate]=d;}document.documentElement.style.zoom=String(scale);planning.timelineState.dayWidth=width;planning.timelineState.rangeStart=date(rangeStart);planning.timelineState.rangeEnd=date(rangeEnd);planning.timelineState.expandedTracks=new Set(['parent']);planning.timelineState.collapsedTrackGroups=new Set();planning.renderTimeline(bodyA,{left:0});planning.renderTimeline(bodyB,{left:0});}
function node(id,which='a'){return document.querySelector('#'+which+' [data-task-id="'+id+'"]');}
function point(id,mode='move',which='a'){const n=node(id,which),r=(mode==='right'?n.querySelector('.copal-resize-right'):mode==='left'?n.querySelector('.copal-resize-left'):n).getBoundingClientRect();return {x:mode==='right'?r.right-1:mode==='left'?r.left+1:r.left+r.width/2,y:r.top+r.height/2};}
function geometry(id,which='a'){const n=node(id,which),r=n.getBoundingClientRect(),s=n.querySelector('.copal-event-surface').getBoundingClientRect();return {x:r.x,width:r.width,paintedX:s.x,paintedWidth:s.width};}
function header(dateText,which='a'){const r=document.querySelector('#'+which+' .copal-day-row span[title="'+dateText+'"]').getBoundingClientRect();return {x:r.x,width:r.width};}
function renderProbe(which='a'){const root=document.querySelector('#'+which),timeline=root.querySelector('.copal-timeline'),scroll=root.querySelector('.copal-timeline-scroll');const rows=[...root.querySelectorAll('.copal-track')].map((row)=>{const r=row.getBoundingClientRect();const label=row.querySelector('.copal-track-label').getBoundingClientRect();const style=getComputedStyle(row);return {id:row.dataset.trackId,top:r.top,bottom:r.bottom,height:r.height,labelLeft:label.left,labelWidth:label.width,backgroundImage:style.backgroundImage,borderBottom:style.borderBottomColor};});const days=[...root.querySelectorAll('.copal-day-row span')].map((cell)=>{const r=cell.getBoundingClientRect();return {date:cell.title,left:r.left,right:r.right,width:r.width};});return {timeline:timeline.getBoundingClientRect().toJSON(),scroll:scroll.getBoundingClientRect().toJSON(),rows,days,dayWidth:getComputedStyle(timeline).getPropertyValue('--copal-day-width').trim(),bandOffset:getComputedStyle(timeline).getPropertyValue('--copal-band-offset').trim(),grid:getComputedStyle(timeline).backgroundImage};}
function pixelPoints(which='a'){const root=document.querySelector('#'+which),row=root.querySelector('.copal-track[data-track-id="parent"]'),rr=row.getBoundingClientRect();return [...root.querySelectorAll('.copal-day-row span')].slice(0,8).map((cell)=>{const r=cell.getBoundingClientRect();return {date:cell.title,x:r.left+r.width/2,y:rr.bottom-12};});}
function rowPixelPoints(which='a'){const root=document.querySelector('#'+which),days=[...root.querySelectorAll('.copal-day-row span')].slice(0,4);return [...root.querySelectorAll('.copal-track')].map((row)=>{const rr=row.getBoundingClientRect();return {id:row.dataset.trackId,points:days.map((cell)=>{const r=cell.getBoundingClientRect();return {date:cell.title,x:r.left+r.width/2,y:rr.bottom-12};})};});}
async function zoomAnchor(which='a'){configure('2024-01-01','2024-07-01',18,1);const root=document.querySelector('#'+which),scroll=root.querySelector('.copal-timeline-scroll'),button=root.querySelector('button[aria-label="Zoom in"]');scroll.scrollLeft=1100;await new Promise((resolve)=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const center=scroll.getBoundingClientRect().left+scroll.clientWidth/2;const dateAt=()=>[...root.querySelectorAll('.copal-day-row span')].find((cell)=>{const r=cell.getBoundingClientRect();return r.left<=center&&center<r.right;})?.title||null;const before=dateAt();button.click();await new Promise((resolve)=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {before,after:dateAt(),scrollLeft:root.querySelector('.copal-timeline-scroll').scrollLeft,zoom:planning.timelineState.dayWidth};}
async function disclosure(which='a'){const root=document.querySelector('#'+which),scroll=root.querySelector('.copal-timeline-scroll'),button=root.querySelector('.copal-track[data-track-id="parent"] .copal-track-disclosure');scroll.scrollLeft=1100;await new Promise((resolve)=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const center=scroll.getBoundingClientRect().left+scroll.clientWidth/2;const dateAt=()=>[...root.querySelectorAll('.copal-day-row span')].find((cell)=>{const r=cell.getBoundingClientRect();return r.left<=center&&center<r.right;})?.title||null;const before={date:dateAt(),left:scroll.scrollLeft,expanded:button.getAttribute('aria-expanded')};button.click();await new Promise((resolve)=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const collapsedRoot=document.querySelector('#'+which),collapsedButton=collapsedRoot.querySelector('.copal-track[data-track-id="parent"] .copal-track-disclosure'),collapsedScroll=collapsedRoot.querySelector('.copal-timeline-scroll');const collapsed={date:[...collapsedRoot.querySelectorAll('.copal-day-row span')].find((cell)=>{const r=cell.getBoundingClientRect();return r.left<=center&&center<r.right;})?.title||null,left:collapsedScroll.scrollLeft,expanded:collapsedButton.getAttribute('aria-expanded')};const hidden=!collapsedRoot.querySelector('.copal-track[data-track-id="child"]');collapsedButton.click();await new Promise((resolve)=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {before,collapsed,hidden,restored:!!root.querySelector('.copal-track[data-track-id="child"]')};}
function active(which='a'){const n=node('leap',which);const c=resolveInputContext({target:n,composedPath:()=>[n,n.closest('.copal-timeline-scroll'),document.querySelector('#'+which),document.body,document.documentElement,document]});return c?.windowId||null;}
function contexts(){document.querySelector('#b').dispatchEvent(new FocusEvent('focusin',{bubbles:true}));const b=active('b');document.querySelector('#a').dispatchEvent(new FocusEvent('focusin',{bubbles:true}));return {active:getActiveInputContext()?.windowId||null,a:active('a'),b};}
window.audit={configure,point,geometry,header,renderProbe,pixelPoints,rowPixelPoints,zoomAnchor,disclosure,active,calls,clear:()=>calls.splice(0),dayWidth:()=>planning.timelineState.dayWidth,pixelDayWidth:()=>{const c=document.querySelector('#a .copal-timeline');return planning.timelineState.dayWidth*c.getBoundingClientRect().width/parseFloat(c.style.width);},contexts};
configure('2024-02-20','2024-03-10',18); await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))); window.auditReady=true;`;
const page = `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/static/style.css"><style>html,body{margin:0;background:#17202a;color:#eee}#a,#b{width:1200px;margin:0 0 24px}.copal-timeline-scroll{height:460px}</style><div id="a" data-window-id="timeline-a"></div><div id="b" data-window-id="timeline-b"></div><script>addEventListener('error',e=>document.body.dataset.error=e.message);addEventListener('unhandledrejection',e=>document.body.dataset.error=String(e.reason));</script><script type="module">import('/fixture.js').catch(e=>document.body.dataset.error=e.stack||String(e))</script>`;

function decodePng(base64) {
  const bytes = Buffer.from(base64, 'base64');
  assert.deepEqual([...bytes.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
  const width = bytes.readUInt32BE(16); const height = bytes.readUInt32BE(20); const bitDepth = bytes[24]; const colorType = bytes[25];
  assert.equal(bitDepth, 8, 'browser screenshot must use 8-bit pixels'); assert([2, 6].includes(colorType), `unsupported screenshot color type ${colorType}`);
  const bytesPerPixel = colorType === 6 ? 4 : 3; const idat = []; let offset = 8;
  while (offset < bytes.length) { const size = bytes.readUInt32BE(offset); const type = bytes.toString('ascii', offset + 4, offset + 8); if (type === 'IDAT') idat.push(bytes.subarray(offset + 8, offset + 8 + size)); offset += 12 + size; }
  const raw = zlib.inflateSync(Buffer.concat(idat)); const stride = width * bytesPerPixel; const pixels = Buffer.alloc(height * stride); let rawOffset = 0;
  const paeth = (a, b, c) => { const p = a + b - c; const pa = Math.abs(p - a); const pb = Math.abs(p - b); const pc = Math.abs(p - c); return pa <= pb && pa <= pc ? a : pb <= pc ? b : c; };
  for (let y = 0; y < height; y++) { const filter = raw[rawOffset++]; const row = y * stride; const prior = (y - 1) * stride; for (let x = 0; x < stride; x++) { const left = x >= bytesPerPixel ? pixels[row + x - bytesPerPixel] : 0; const up = y ? pixels[prior + x] : 0; const upLeft = y && x >= bytesPerPixel ? pixels[prior + x - bytesPerPixel] : 0; const value = raw[rawOffset++]; pixels[row + x] = filter === 0 ? value : filter === 1 ? (value + left) & 255 : filter === 2 ? (value + up) & 255 : filter === 3 ? (value + Math.floor((left + up) / 2)) & 255 : (value + paeth(left, up, upLeft)) & 255; } }
  return { width, height, pixel(x, y) { const px = Math.max(0, Math.min(width - 1, Math.round(x))); const py = Math.max(0, Math.min(height - 1, Math.round(y))); const index = py * stride + px * bytesPerPixel; return [...pixels.subarray(index, index + 3)]; } };
}
function colorDistance(a, b) { return Math.sqrt(a.reduce((sum, value, index) => sum + (value - b[index]) ** 2, 0)); }

const server = http.createServer((req,res)=>{
  if (req.url === '/') { res.writeHead(200, {'content-type':'text/html'}); res.end(page); return; }
  if (req.url === '/fixture.js') { res.writeHead(200, {'content-type':'text/javascript'}); res.end(fixture); return; }
  if (req.url.startsWith('/static/')) { const file=path.join(root,req.url.slice(1)); if (!file.startsWith(path.join(root,'static'))) { res.writeHead(403); res.end(); return; } try { const type=file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream'; res.writeHead(200,{'content-type':type}); res.end(fs.readFileSync(file)); } catch { res.writeHead(404); res.end(); } return; }
  res.writeHead(404); res.end();
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const port=server.address().port; const fixtureResponse=await fetch(`http://127.0.0.1:${port}/fixture.js`); assert.equal(fixtureResponse.status,200); const fixtureText=await fixtureResponse.text(); assert(fixtureText.includes('window.auditReady')); const chrome=['/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'].find(fs.existsSync); assert(chrome,'Chromium executable required');
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'copal-geometry-')); const browser=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu',`--user-data-dir=${profile}`,'--remote-debugging-port=0','about:blank'],{stdio:['ignore','pipe','pipe']});
let debugPort; const output=(chunk)=>{const m=String(chunk).match(/DevTools listening on ws:\/\/127\.0\.0\.1:(\d+)/);if(m)debugPort=Number(m[1]);}; browser.stderr.on('data',output); browser.stdout.on('data',output); for(let i=0;!debugPort&&i<100;i++)await delay(20); assert(debugPort,'DevTools did not start');
const targets=await (await fetch(`http://127.0.0.1:${debugPort}/json/new?${encodeURIComponent(`http://127.0.0.1:${port}/`)}`,{method:'PUT'})).json();
const ws=new WebSocket(targets.webSocketDebuggerUrl); await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})}); let seq=0; const pending=new Map(); ws.addEventListener('message',event=>{const msg=JSON.parse(event.data);if(msg.id&&pending.has(msg.id)){pending.get(msg.id)(msg);pending.delete(msg.id);}});
const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,msg=>msg.error?reject(new Error(msg.error.message)):resolve(msg.result));ws.send(JSON.stringify({id,method,params}));});
await cdp('Runtime.enable'); await cdp('Network.enable');
await cdp('Page.enable'); await cdp('Page.reload',{ignoreCache:true}); await delay(120);
const evaluate=async(expression,awaitPromise=true)=>{const r=await cdp('Runtime.evaluate',{expression,awaitPromise,returnByValue:true});return r.result?.value;};
const screenshotPixels=async(which='a')=>{const points=await evaluate(`window.audit.pixelPoints(${JSON.stringify(which)})`);const capture=await cdp('Page.captureScreenshot',{format:'png',fromSurface:true});const image=decodePng(capture.data);const dpr=await evaluate('window.devicePixelRatio');return points.map((point)=>({date:point.date,color:image.pixel(point.x*dpr,point.y*dpr)}));};
const screenshotRowPixels=async(which='a')=>{const rows=await evaluate(`window.audit.rowPixelPoints(${JSON.stringify(which)})`);const capture=await cdp('Page.captureScreenshot',{format:'png',fromSurface:true});const image=decodePng(capture.data);const dpr=await evaluate('window.devicePixelRatio');return rows.map((row)=>({id:row.id,pixels:row.points.map((point)=>({date:point.date,color:image.pixel(point.x*dpr,point.y*dpr)}))}));};
const cleanup=async()=>{try{ws.close();}catch{}if(browser.exitCode===null){browser.kill('SIGTERM');await delay(100);if(browser.exitCode===null)browser.kill('SIGKILL');}await new Promise(resolve=>server.close(resolve));try{fs.rmSync(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});}catch{} };
try {
for(let i=0;i<100;i++){if(await evaluate('Boolean(window.auditReady)'))break;await delay(20);} if(!await evaluate('Boolean(window.auditReady)')) { console.error('fixture location',await evaluate('location.href'),await evaluate('document.body.innerText'),await evaluate('document.body.dataset.error'),await evaluate('performance.getEntriesByType("resource").map(x=>x.name)')); throw new Error('fixture did not load'); }
async function drag(id,days,mode='move'){const p=await evaluate(`window.audit.point(${JSON.stringify(id)},${JSON.stringify(mode)})`);const px=await evaluate('window.audit.pixelDayWidth()');const x=p.x+days*px;await cdp('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',buttons:1,clickCount:1});await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',x,y:p.y,button:'left',buttons:1});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',x,y:p.y,button:'left',buttons:0,clickCount:1});await delay(80);}
async function setTimezone(timezoneId){await cdp('Emulation.setTimezoneOverride',{timezoneId});}
async function set(width,start,end,scale=1,dpr=1){await cdp('Emulation.setDeviceMetricsOverride',{width:1400,height:1000,deviceScaleFactor:dpr,mobile:false});await evaluate(`window.audit.configure(${JSON.stringify(start)},${JSON.stringify(end)},${width},${scale})`);await delay(40);}
const report=[];
await set(18,'2024-02-20','2024-03-10',1,1); const g=await evaluate('({e:window.audit.geometry("leap"),single:window.audit.geometry("single"),h:window.audit.header("2024-02-28"),singleHeader:window.audit.header("2024-02-25"),probe:window.audit.renderProbe()})'); assert(Math.abs(g.e.x-g.h.x)<1,'event/header x mismatch'); assert(Math.abs(g.e.width-g.h.width*3)<1,'multi-day width mismatch'); assert(Math.abs(g.single.paintedWidth-(g.singleHeader.width-2))<1,'single-day paint must occupy one date cell'); assert(g.probe.rows.some((row)=>row.id==='parent')&&g.probe.rows.some((row)=>row.id==='child'),'nested rows must render'); assert(g.probe.grid.includes('18px'),'timeline grid must resolve to the configured day width'); assert(g.probe.probe===undefined,'render probe must come from the live DOM');
const bands=await screenshotPixels(); const rowBands=await screenshotRowPixels(); const gridProbe=await evaluate('window.audit.renderProbe()'); assert(colorDistance(bands[0].color,bands[1].color)>1,'alternating day bands must differ in rendered pixels'); assert(colorDistance(bands[1].color,bands[2].color)>1,'adjacent date bands must alternate in rendered pixels'); for(const row of rowBands) assert(colorDistance(row.pixels[0].color,row.pixels[1].color)>1,`alternating bands must paint through ${row.id}`); const boundaryPoints=gridProbe.rows.flatMap((row)=>gridProbe.days.slice(1,4).map((day)=>({x:day.left,y:row.bottom-12}))); const capture=decodePng((await cdp('Page.captureScreenshot',{format:'png',fromSurface:true})).data); const dpr=await evaluate('window.devicePixelRatio'); for(const point of boundaryPoints){assert(colorDistance(capture.pixel(point.x*dpr,point.y*dpr),capture.pixel((point.x+2)*dpr,point.y*dpr))>1,'date grid boundary must remain painted through every track row');}
const anchor=await evaluate('window.audit.zoomAnchor()'); assert.equal(anchor.before,anchor.after,`zoom must retain the date at the viewport anchor: ${JSON.stringify(anchor)}`); assert(anchor.scrollLeft>0,`zoom anchor check must exercise a scrolled timeline: ${JSON.stringify(anchor)}`); const disclosure=await evaluate('window.audit.disclosure()'); assert.equal(disclosure.before.expanded,'true'); assert.equal(disclosure.collapsed.expanded,'false'); assert.equal(disclosure.before.date,disclosure.collapsed.date,`collapse must retain the visible date anchor: ${JSON.stringify(disclosure)}`); assert(Math.abs(disclosure.before.left-disclosure.collapsed.left)<1,'collapse must retain horizontal scroll'); assert(disclosure.hidden&&disclosure.restored,'disclosure must hide and restore nested rows'); await set(18,'2024-02-20','2024-03-10',1,1);
await setTimezone('America/New_York'); await set(18,'2024-03-09','2024-03-12',1,1); const spring=await evaluate('({e:window.audit.geometry("dst"),a:window.audit.header("2024-03-09"),b:window.audit.header("2024-03-10"),c:window.audit.header("2024-03-11")})'); assert(Math.abs(spring.a.width-spring.b.width)<1&&Math.abs(spring.b.width-spring.c.width)<1,'spring DST dates must retain equal day cells'); assert(Math.abs(spring.e.width-spring.a.width*3)<1,'spring DST event must retain three painted date cells'); await set(18,'2024-11-02','2024-11-05',1,1); const fall=await evaluate('({e:window.audit.geometry("dst-fall"),a:window.audit.header("2024-11-02"),b:window.audit.header("2024-11-03"),c:window.audit.header("2024-11-04")})'); assert(Math.abs(fall.a.width-fall.b.width)<1&&Math.abs(fall.b.width-fall.c.width)<1,'fall DST dates must retain equal day cells'); assert(Math.abs(fall.e.width-fall.a.width*3)<1,'fall DST event must retain three painted date cells'); await setTimezone('UTC'); await set(18,'2024-02-20','2024-03-10',1,1);
await evaluate('window.audit.clear()'); await drag('leap',1); let call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.deepEqual(call,{startDate:'2024-02-29',dueDate:'2024-03-02'}); report.push({case:'leapday drag',patch:call});
await set(18,'2024-02-20','2024-03-10',1,1); await evaluate('window.audit.clear()'); await drag('single',1); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.deepEqual(call,{startDate:'2024-02-26',dueDate:'2024-02-26'}); report.push({case:'normal single-day center drag',patch:call});
await set(18,'2024-02-20','2024-03-10',1,1); await evaluate('window.audit.clear()'); await drag('single',-1,'left'); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.equal(call.startDate,'2024-02-24'); report.push({case:'normal single-day left resize',patch:call});
await set(18,'2024-02-20','2024-03-10',1,1); await evaluate('window.audit.clear()'); await drag('single',1,'right'); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.deepEqual(call,{dueDate:'2024-02-26'}); report.push({case:'normal single-day right resize',patch:call});
await set(18,'2024-02-20','2024-03-10',1,1); await evaluate('window.audit.clear()'); await drag('leap',1,'right'); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.equal(call.dueDate,'2024-03-02'); report.push({case:'normal-width resize',patch:call});
await set(8,'2024-02-20','2024-03-10',1,1); const narrowBands=await screenshotPixels(); assert(colorDistance(narrowBands[0].color,narrowBands[1].color)>1,'narrow rendered day bands must remain date anchored'); await evaluate('window.audit.clear()'); await drag('leap',1,'right'); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.equal(call.dueDate,'2024-03-02'); report.push({case:'narrow resize',patch:call});
await set(8,'2024-02-20','2024-03-10',1,1); await evaluate('window.audit.clear()'); await drag('single',1); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.deepEqual(call,{startDate:'2024-02-26',dueDate:'2024-02-26'}); report.push({case:'narrow single-day center drag',patch:call});
await set(18,'2024-12-20','2025-01-10',.8,2); const z=await evaluate('({e:window.audit.geometry("year"),h:window.audit.header("2024-12-31")})'); assert(Math.abs(z.e.x-z.h.x)<1,'scaled event/header x mismatch'); const dpr2Bands=await screenshotPixels(); assert(colorDistance(dpr2Bands[0].color,dpr2Bands[1].color)>1,'DPR2 rendered day bands must remain date anchored'); await evaluate('window.audit.clear()'); await drag('year',1); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.deepEqual(call,{startDate:'2025-01-01',dueDate:'2025-01-02'}); report.push({case:'year boundary drag at dpr2/zoom.8',patch:call});
await set(18,'2024-02-20','2024-03-20',.8,1); await evaluate('window.audit.clear()'); await drag('long',5); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.deepEqual(call,{startDate:'2024-03-06',dueDate:'2024-03-10'}); report.push({case:'five-day drag at zoom.8',patch:call});
await set(18,'2024-02-20','2024-03-20',1.25,1); await evaluate('window.audit.clear()'); await drag('long',5); call=(await evaluate('window.audit.calls.at(-1)')).payload.patch; assert.deepEqual(call,{startDate:'2024-03-06',dueDate:'2024-03-10'}); report.push({case:'five-day drag at zoom1.25',patch:call});
await set(18,'2024-02-20','2024-03-10',1,1); await evaluate('window.audit.clear()'); await drag('child-event',1); const childCalls=await evaluate('window.audit.calls.map(c=>c.path)'); assert.equal(childCalls.length,1); assert(childCalls[0].endsWith('/child-event')); report.push({case:'nested child isolation',patch:(await evaluate('window.audit.calls[0].payload.patch'))});
const contexts=await evaluate('window.audit.contexts()'); assert.equal(contexts.a,'a'); assert.equal(contexts.b,'b'); report.push({case:'two live timeline instances',contexts});
console.log(JSON.stringify({passed:report},null,2));
} finally { await cleanup(); }
