#!/usr/bin/env node
import assert from 'node:assert/strict';
import { setTimeout as delay } from 'node:timers/promises';
import { withCopalBrowser } from './helpers/copal_browser_fixture.mjs';

const page=`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/static/style.css"><style>body{margin:0;background:#17202a;color:#eee}.copal-tool-modal{position:fixed;inset:10px auto auto 10px;width:900px;height:500px;display:flex!important}.copal-modal-content{width:100%;height:100%}.copal-view{height:350px;min-width:700px}.copal-timeline-scroll{height:260px;overflow:auto}.cm-editor{height:220px}</style><main id="fixture"></main><script>window.addEventListener("error",e=>window.auditError=e.message);window.addEventListener("unhandledrejection",e=>window.auditError=String(e.reason));</script><script type="module" src="/fixture.js"></script>`;
const fixture=`import { createOpenClankWindow } from '/static/js/copal/windows.js';
import { createMarkdownEditor } from '/static/js/copal/codemirror.js';
import { createPlanningFeature } from '/static/js/copal/planning.js';
import { configureCopalStorage } from '/static/js/copal/storage.js';
import { wireDialog } from '/static/js/copal/overlays.js';
import { activateInputContext } from '/static/js/copal/inputContext.js';
configureCopalStorage('input-ownership-fixture');
const h=(tag,attrs={},...children)=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k==='text')n.textContent=v;else if(k.startsWith('on')&&typeof v==='function')n.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==false&&v!=null)n.setAttribute(k,String(v));}for(const c of children.flat())if(c!=null)n.append(c.nodeType?c:document.createTextNode(String(c)));return n;};
const calls=[];const data={title:'Input fixture',tracks:[{id:'track-one',name:'Track One',enabled:true,tasks:[{id:'event-one',trackId:'track-one',title:'Event One',startDate:'2026-01-05',dueDate:'2026-01-06',status:'pending',priority:'medium'}]}],floatingTodos:[]};
const makeWindow=(id,label)=>{const w=createOpenClankWindow({id,label,onActivate(){}});w.show();return w;};
const timeline=makeWindow('timeline-one','Timeline');const secondTimeline=makeWindow('timeline-two','Embedded Timeline');
const makePlanning=()=>{const p=createPlanningFeature({h,api:async(path,opts={})=>{calls.push({path,opts});return {event:{}};},getPlanning:()=>data,refresh:async()=>{},setStatus:()=>{},projectionChanged:()=>{},openDocument:()=>{}});p.loadState('fixture');Object.assign(p.timelineState,{dayWidth:40,rangeStart:new Date(2026,0,1),rangeEnd:new Date(2026,0,31),expandedTracks:new Set(),collapsedTrackGroups:new Set()});return p;};
const planning=makePlanning();const planningTwo=makePlanning();planning.renderTimeline(timeline.body,{left:0});planningTwo.renderTimeline(secondTimeline.body,{left:0});const scroll=timeline.body.querySelector('.copal-timeline-scroll');const secondScroll=secondTimeline.body.querySelector('.copal-timeline-scroll');
const editor=makeWindow('editor-one','Editor');const cmHost=document.createElement('div');editor.body.append(cmHost);let cm=createMarkdownEditor({parent:cmHost,doc:'Editor text',label:'Editor',onChange:text=>calls.push(text)});
function modal(){const d=document.createElement('dialog');d.id='modal-'+Math.random().toString(36).slice(2);d.textContent='Modal';document.body.append(d);wireDialog(d);d.showModal();return d;}
function recreateEditor(){const previousCm=cm;previousCm.destroy();editor.destroy();const next=makeWindow('editor-one','Editor reopened');const host=document.createElement('div');next.body.append(host);cm=createMarkdownEditor({parent:host,doc:'Reopened text',label:'Editor reopened',onChange:text=>calls.push(text)});window.audit.cm=cm;return {window:next,previousCm};}
window.audit={get scroll(){return timeline.body.querySelector('.copal-timeline-scroll')},get secondScroll(){return secondTimeline.body.querySelector('.copal-timeline-scroll')},calls,cm,editor,timeline,secondTimeline,planning,planningTwo,modal,recreateEditor,activateTimeline:()=>{timeline.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerType:'mouse',button:1}));scroll.focus();},activateSecondTimeline:()=>{secondTimeline.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerType:'mouse',button:1}));secondScroll.focus();},state:()=>({scroll:scroll.scrollLeft,calls:calls.length,editorText:cm.getValue(),timelineVisible:timeline.visible,editorVisible:editor.visible,event:data.tracks[0].tasks[0]})};
await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));window.auditReady=true;`;
const results=[];
await withCopalBrowser({page,overrides:{'/fixture.js':fixture}},async({cdp,evaluate,until})=>{
 await until('Boolean(window.auditReady||window.auditError)'); assert.equal(await evaluate('window.auditError||null'),null); await until('window.audit.scroll.clientWidth>0 && window.audit.scroll.scrollWidth>window.audit.scroll.clientWidth');
 await evaluate('window.audit.cm.focus()');const before=await evaluate('window.audit.state()');await cdp('Input.insertText',{text:'X'});await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',modifiers:1,windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',modifiers:1,windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});const editorActive=await evaluate('window.audit.state()');assert.equal(editorActive.scroll,before.scroll);assert(editorActive.editorText.includes('X'));assert.equal(editorActive.event.startDate,'2026-01-05');results.push({case:'production CodeMirror typing/arrows/Alt+Arrow over Timeline',state:editorActive});
 await evaluate('window.audit.activateTimeline();window.audit.scroll.focus()');const positiveBefore=await evaluate('window.audit.scroll.scrollLeft');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});const positiveAfter=await evaluate('window.audit.scroll.scrollLeft');if (!(positiveAfter>positiveBefore)) { const diag=await evaluate('({active:document.activeElement?.className,scrollWidth:window.audit.scroll.scrollWidth,clientWidth:window.audit.scroll.clientWidth,tabindex:window.audit.scroll.getAttribute("tabindex"),visible:window.audit.timeline.visible})'); throw new Error(JSON.stringify({positiveBefore,positiveAfter,diag})); } results.push({case:'production Timeline keyboard navigation',before:positiveBefore,after:positiveAfter});
 await evaluate('(()=>{window.audit.secondTimeline.show();return true})()');assert.equal(await evaluate('window.audit.secondTimeline.visible'),true);results.push({case:'two production Timeline windows',first:await evaluate('window.audit.timeline.visible'),second:await evaluate('window.audit.secondTimeline.visible')});
 await evaluate('window.audit.editor.root.style.zIndex="10000";void window.audit.editor.show();');await delay(100);await evaluate('window.audit.cm.focus()');const wheelBefore=await evaluate('window.audit.scroll.scrollLeft');const cmRect=await evaluate('(()=>{const r=document.querySelector("#editor-one .cm-editor").getBoundingClientRect();const element=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {x:r.x+r.width/2,y:r.y+r.height/2,editor:!!element?.closest("#editor-one .cm-editor")}})()');assert.equal(cmRect.editor,true);await cdp('Input.dispatchMouseEvent',{type:'mouseWheel',x:cmRect.x,y:cmRect.y,deltaX:0,deltaY:100});const wheelAfter=await evaluate('window.audit.scroll.scrollLeft');assert.equal(wheelAfter,wheelBefore);results.push({case:'production editor wheel isolation',before:wheelBefore,after:wheelAfter});
 await evaluate('window.audit.activateTimeline();window.audit.scroll.focus()');const compBefore=await evaluate('window.audit.scroll.scrollLeft');await evaluate('window.audit.scroll.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true,cancelable:true,isComposing:true}))');const compAfter=await evaluate('window.audit.scroll.scrollLeft');assert.equal(compAfter,compBefore);results.push({case:'composition gate (synthetic isComposing event)',before:compBefore,after:compAfter,trusted:false});
 const modal=await evaluate('window.audit.modal().id');await evaluate('window.audit.scroll.focus()');const blockedBefore=await evaluate('window.audit.scroll.scrollLeft');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});const blockedAfter=await evaluate('window.audit.scroll.scrollLeft');assert.equal(blockedAfter,blockedBefore);const nested=await evaluate('window.audit.modal().id');await evaluate(`document.getElementById(${JSON.stringify(nested)}).close()`);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});const stillBlocked=await evaluate('window.audit.scroll.scrollLeft');assert.equal(stillBlocked,blockedAfter);await evaluate(`document.getElementById(${JSON.stringify(modal)}).close()`);await evaluate('window.audit.activateTimeline();window.audit.scroll.focus()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39,nativeVirtualKeyCode:39});const restored=await evaluate('window.audit.scroll.scrollLeft');assert(restored>stillBlocked);results.push({case:'true nested modal blocking/restoration',outer:modal,inner:nested,blocked:stillBlocked,restored});
 await evaluate('window.audit.editor.root.style.display="none";window.audit.editor.root.style.zIndex="1";window.audit.secondTimeline.root.style.zIndex="9999";void window.audit.secondTimeline.show()');await delay(100);await evaluate('window.audit.activateSecondTimeline();window.audit.secondScroll.focus()');const rect=await evaluate('(()=>{const r=window.audit.secondScroll.getBoundingClientRect();return {x:r.x,y:r.y}})()');await cdp('Input.dispatchMouseEvent',{type:'mousePressed',x:rect.x+20,y:rect.y+20,button:'left',buttons:1,clickCount:1});const activeDrag=await evaluate('window.audit.secondScroll.classList.contains("dragging")');if(!activeDrag){const d=await evaluate('(()=>{const r=window.audit.secondScroll.getBoundingClientRect(),e=document.elementFromPoint(r.x+20,r.y+20);return {r:{x:r.x,y:r.y,w:r.width,h:r.height},target:e?.className,editor:document.querySelector("#editor-one")?.style.display,active:document.activeElement?.className}})()');throw new Error(JSON.stringify(d));}const dragBefore=await evaluate('window.audit.secondScroll.scrollLeft');await evaluate('window.audit.secondScroll.dispatchEvent(new PointerEvent("pointercancel",{bubbles:true,cancelable:true,pointerId:1}))');await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',x:rect.x+20,y:rect.y+20,button:'left',buttons:0,clickCount:1});await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',x:rect.x+120,y:rect.y+20,button:'left',buttons:1});const canceled=await evaluate('({dragging:window.audit.secondScroll.classList.contains("dragging"),scroll:window.audit.secondScroll.scrollLeft})');assert.equal(canceled.dragging,false);assert.equal(canceled.scroll,dragBefore);await evaluate('window.audit.editor.root.style.display="flex"');results.push({case:'production Timeline pointer cancellation (synthetic cancel)',activeDrag,canceled,trustedCancel:false});
 const oldCalls=await evaluate('window.audit.calls.length');const reopened=await evaluate('(()=>{const value=window.audit.recreateEditor();value.window.body.querySelector(".cm-editor").dispatchEvent(new FocusEvent("focusin",{bubbles:true}));return {visible:!document.querySelector("#editor-one").classList.contains("hidden"),oldConnected:value.previousCm.view.dom.isConnected}})()');assert.equal(reopened.visible,true);assert.equal(reopened.oldConnected,false);await evaluate('window.audit.cm.focus()');await cdp('Input.insertText',{text:'Y'});const recreated=await evaluate('({text:window.audit.cm.getValue(),calls:window.audit.calls.length,oldCalls:'+oldCalls+',windows:document.querySelectorAll("#editor-one").length})');assert(recreated.text.includes('Y'));assert.equal(recreated.calls,recreated.oldCalls+1);assert.equal(recreated.windows,1);results.push({case:'production Editor destroy/recreate with new CodeMirror context',recreated});
});
console.log(JSON.stringify({passed:results},null,2));
