#!/usr/bin/env node

// Disposable G07/G08 gate. Exercises the mounted Files UI plus the real
// FastAPI facade, Rust Files service and filesystem in a generated host root.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { execFileSync, spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';

const repo = process.cwd();
const python = path.join(repo, 'venv', 'bin', 'python');
const chrome = ['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser', '/usr/bin/google-chrome'].find(fs.existsSync);
const filesService = path.join(repo, 'packages/odysseus-files/target/release/odysseus-files-service');
if (!fs.existsSync(python) || !chrome || !fs.existsSync(filesService)) { console.log(JSON.stringify({ skipped:'requires venv/bin/python, Chrome, and release Files service' })); process.exit(0); }
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'copal-qol3-g07-')); const data = path.join(temporary, 'data'); const hostRoot = path.join(temporary, 'authorized-host'); const registryPath = path.join(data, 'odysseus-file-roots.json'); fs.mkdirSync(hostRoot, { recursive:true }); fs.mkdirSync(data, { recursive:true });
const password = 'g07-disposable-password'; const hash = execFileSync(python, ['-c', 'import bcrypt,sys; print(bcrypt.hashpw(sys.argv[1].encode(), bcrypt.gensalt()).decode())', password], { cwd:repo, encoding:'utf8' }).trim();
const now=Date.now(); const registryBuilder='import json,sys; from src.openclank.filesystem_registry import FilesystemRootRegistry; r=FilesystemRootRegistry(sys.argv[1]); root=r.add("e",sys.argv[2],"recursive_directory",["read","write"]); r.assign_visibility("e","e",root["id"],["read","write"]); data=r.snapshot(); print(json.dumps({"root":data["roots"][root["id"]],"assignment":next(v for v in data["visibility_assignments"].values() if v["root_id"]==root["id"])}))';
const seededRegistry=JSON.parse(execFileSync(python,['-c',registryBuilder,registryPath,hostRoot],{cwd:repo,encoding:'utf8'})); const root=seededRegistry.root; const assignment=seededRegistry.assignment;
fs.writeFileSync(path.join(data, 'auth.json'), JSON.stringify({ signup_enabled:false, users:{ e:{ account_id:'account-e', password_hash:hash, created:now/1000, is_admin:false }, b:{ account_id:'account-b', password_hash:hash, created:now/1000, is_admin:false } } }));
const freePort = () => new Promise((resolve, reject) => { const server = net.createServer(); server.once('error', reject); server.listen(0, '127.0.0.1', () => { const p = server.address().port; server.close(error => error ? reject(error) : resolve(p)); }); });
const port = await freePort(); const base = `http://127.0.0.1:${port}`; let appOutput = '';
const app = spawn(python, ['-m','uvicorn','app:app','--host','127.0.0.1','--port',String(port)], { cwd:repo, env:{ ...process.env, DEBUG:'false', OPENCLANK_DEBUG:'false', AUTH_ENABLED:'true', OPENCLANK_RECOVERY_MODE:'true', COPAL_STORAGE:'redb', COPAL_DATA_DIR:path.join(data,'copal-db'), COPAL_BRIDGE_COMMAND:path.join(repo,'packages/Copal/rust/copal-db/target/release/copal-bridge'), OPEN_CLANK_DATA_DIR:data, DATABASE_URL:`sqlite:///${path.join(data,'app.db')}`, ODYSSEUS_FILES_REGISTRY:registryPath, ODYSSEUS_FILES_SERVICE_BIN:filesService, ODYSSEUS_FILES_TRANSPORT:'framed', PYTHONUNBUFFERED:'1' }, stdio:['ignore','pipe','pipe'] });
const collect = chunk => { appOutput += String(chunk); if (appOutput.length > 30000) appOutput = appOutput.slice(-30000); }; app.stdout.on('data', collect); app.stderr.on('data', collect);
async function waitHealth() { for (let i=0;i<1200;i+=1) { if (app.exitCode != null) throw new Error(`FastAPI exited: ${appOutput.slice(-4000)}`); try { if ((await fetch(`${base}/api/health`)).ok) return; } catch (_) {} await delay(100); } throw new Error(`health timeout: ${appOutput.slice(-4000)}`); }
let session = ''; async function request(route, options={}) { const headers = new Headers(options.headers || {}); if (session) headers.set('Cookie', `odysseus_session=${session}`); return fetch(`${base}${route}`, { ...options, headers }); }
async function json(route, options={}) { const r=await request(route,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}); const body=await r.text(); assert(r.ok, `${route}: HTTP ${r.status} ${body}`); return JSON.parse(body); }
async function openBrowser() { const profile=fs.mkdtempSync(path.join(os.tmpdir(),'copal-qol3-g07-browser-')); const child=spawn(chrome,['--headless=new','--disable-gpu','--disable-dev-shm-usage','--no-sandbox','--no-first-run','--no-default-browser-check',`--user-data-dir=${profile}`,'--remote-debugging-port=0','about:blank'],{stdio:['ignore','pipe','pipe']}); let out='', debugPort; const collectChrome=chunk=>{out+=String(chunk); const m=out.match(/DevTools listening on ws:\/\/127\.0\.0.1:(\d+)/); if(m)debugPort=Number(m[1]);}; child.stdout.on('data',collectChrome); child.stderr.on('data',collectChrome); for(let i=0;i<1200&&!debugPort;i+=1)await delay(25); assert(debugPort,out.slice(-1000)); const target=await(await fetch(`http://127.0.0.1:${debugPort}/json/new?${encodeURIComponent(`${base}/`)}`,{method:'PUT'})).json(); const ws=new WebSocket(target.webSocketDebuggerUrl); await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});}); let seq=0;const pending=new Map();ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(!m.id||!pending.has(m.id))return;const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(`CDP ${p.method}: ${m.error.message}`)):p.resolve(m.result);}); const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP timeout: ${method}`));},30000);pending.set(id,{method,resolve:v=>{clearTimeout(timer);resolve(v);},reject});ws.send(JSON.stringify({id,method,params}));}); const evaluate=async expression=>{const result=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result?.value;}; const until=async(expression,label,timeout=60000)=>{const deadline=Date.now()+timeout;while(Date.now()<deadline){if(await evaluate(`Boolean(${expression})`))return;await delay(100);}throw new Error(`browser timeout: ${label}: ${JSON.stringify(await evaluate('({href:location.href,text:document.body?.innerText?.slice(-1200)})').catch(()=>({})))}`);}; await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Network.enable');return{cdp,evaluate,until,async close(){try{ws.close();}catch(_){}if(child.exitCode==null)child.kill('SIGTERM');for(let i=0;i<80&&child.exitCode==null;i+=1)await delay(25);if(child.exitCode==null)child.kill('SIGKILL');fs.rmSync(profile,{recursive:true,force:true,maxRetries:8,retryDelay:100});}}; }
let browser;
function registryWith({ enabled=true, generation=2, owner='e' }={}) { const nextRoot={...root,enabled}; const nextAssignment={...assignment,enabled,subject_id:owner,generation}; return {version:1,generation,roots:{[root.id]:nextRoot},visibility_assignments:{[assignment.id]:nextAssignment}}; }
async function stop() { await browser?.close().catch(()=>{}); if(app.exitCode==null)app.kill('SIGTERM'); for(let i=0;i<100&&app.exitCode==null;i+=1)await delay(50); if(app.exitCode==null)app.kill('SIGKILL'); app.stdout?.destroy();app.stderr?.destroy(); fs.rmSync(temporary,{recursive:true,force:true,maxRetries:8,retryDelay:100}); }
try {
  await waitHealth(); const login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'e',password,remember:true})}); assert.equal(login.status,200,await login.text()); session=(login.headers.get('set-cookie')||'').match(/odysseus_session=([^;]+)/)?.[1]||''; assert(session);
  const roots=await json('/api/files-v1/roots?copal_workspace=default'); const generation=roots.policy_generation; const hostAnchor=roots.entries.find(item=>item.provider==='host'&&item.kind==='provider_root'); assert(hostAnchor,'real host provider root missing'); const anchors=await json('/api/files-v1/children',{method:'POST',body:JSON.stringify({parent_ref:hostAnchor.ref,limit:100,sort:{},query:''})}); const authorized=anchors.entries.find(item=>item.name==='authorized-host'); assert(authorized&&authorized.capabilities.includes('write'),JSON.stringify(anchors));
  browser=await openBrowser(); const {cdp,evaluate,until}=browser; await cdp('Network.setCookie',{name:'odysseus_session',value:session,url:`${base}/`,httpOnly:true,sameSite:'Lax'}); await cdp('Page.navigate',{url:`${base}/`}); await until('Boolean(window.filesModule)','Files module'); await evaluate('(async()=>{await window.filesModule.open();})()'); await until('Boolean(document.querySelector("[data-files-body]"))','Files surface'); await until('document.querySelectorAll("[data-files-selection-key]").length >= 1 || document.body.innerText.includes("Host locations › authorized-host")','authorized host surface');
  await evaluate(`window.__g07Prompts=[]; window.__g07PickerCalls=0; window.__g07ConfirmQueue=[]; window.__g07Opened=null; window.uiModule.styledPrompt=async()=>window.__g07Prompts.shift()??null; window.uiModule.styledConfirm=async()=>{window.__g07PickerCalls+=1;return window.__g07ConfirmQueue.shift()??false;}; window.__openClankOpenResourceHandle=async payload=>{window.__g07Opened=payload;}`);
  const freshContext=async selector=>{ await evaluate(`(()=>{ const old=document.querySelector('#openclank-context-menu'); if(old) old.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})); document.querySelector('#openclank-context-menu')?.remove(); const row=document.querySelector(${JSON.stringify(selector)}); if(!row) throw new Error('context target missing: '+${JSON.stringify(selector)}); const r=row.getBoundingClientRect(); row.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:r.left+r.width/2,clientY:r.top+r.height/2,detail:1})); })()`); await delay(0); await until('Boolean(document.querySelector(\"#openclank-context-menu\"))','fresh context menu'); };
  const rootRow=`[data-files-selection-key][data-file-name="authorized-host"]`; if (await evaluate(`Boolean(document.querySelector(${JSON.stringify(rootRow)}))`)) { await evaluate(`document.querySelector(${JSON.stringify(rootRow)})?.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))`); await until(`[data-files-body] [data-files-selection-key]`, 'authorized host listing'); }
  // Toolbar New → Folder uses the captured current host directory.
  await evaluate(`window.__g07Prompts.push('Toolbar Folder'); document.querySelector('[data-files-new]')?.click();`); await until('document.querySelector(".files-action-menu")','toolbar New menu'); assert((await evaluate('[...document.querySelectorAll(".files-action-menu-item")].map(x=>x.textContent.trim())')).includes('New Folder…')); await evaluate(`[...document.querySelectorAll('.files-action-menu-item')].find(x=>x.textContent.trim()==='New Folder…')?.click()`); await until('document.body.innerText.includes("Created folder: Toolbar Folder")','toolbar folder receipt'); await until("Array.from(document.querySelectorAll('[data-files-selection-key]')).some(x=>x.dataset.fileName==='Toolbar Folder')",'toolbar folder row'); assert(fs.existsSync(path.join(hostRoot,'Toolbar Folder'))&&fs.statSync(path.join(hostRoot,'Toolbar Folder')).isDirectory());
  // Blank pane context New → File captures the current folder.
  await freshContext('[data-files-body]'); assert(await evaluate('[...document.querySelectorAll("#openclank-context-menu [data-command]")].some(x=>x.dataset.command==="files-new-file")')); await evaluate(`window.__g07Prompts.push('Blank Zero.txt'); document.querySelector('#openclank-context-menu [data-command="files-new-file"]')?.click()`); await until('document.body.innerText.includes("Created file: Blank Zero.txt")','blank file receipt'); await until("Array.from(document.querySelectorAll('[data-files-selection-key]')).some(x=>x.dataset.fileName==='Blank Zero.txt')",'blank file row'); assert(fs.existsSync(path.join(hostRoot,'Blank Zero.txt'))&&fs.statSync(path.join(hostRoot,'Blank Zero.txt')).size===0);
  // Folder row context New → File must target the folder, not its parent.
  await freshContext('[data-files-selection-key][data-file-name="Toolbar Folder"]'); await evaluate(`window.__g07Prompts.push('Nested.txt'); document.querySelector('#openclank-context-menu [data-command="files-new-file"]')?.click()`); await until('document.body.innerText.includes("Created file: Nested.txt")','nested file receipt'); assert(fs.existsSync(path.join(hostRoot,'Toolbar Folder','Nested.txt'))&&fs.statSync(path.join(hostRoot,'Toolbar Folder','Nested.txt')).size===0);
  // File row context New → File uses the containing folder, and text files
  // expose Open in Editor through the same shared context menu.
  await freshContext('[data-files-selection-key][data-file-name="Blank Zero.txt"]'); const fileCommands=await evaluate('[...document.querySelectorAll("#openclank-context-menu [data-command]")].map(x=>x.dataset.command)'); assert(fileCommands.includes('open-in-editor')); await evaluate('document.querySelector("#openclank-context-menu [data-command=\\"open-in-editor\\"]")?.click()'); await until('window.__g07Opened','Open in Editor handoff'); assert.equal((await evaluate('window.__g07Opened.name')),'Blank Zero.txt');
  // Aggregate/search New requires an explicit authorized-folder picker.
  await evaluate(`const p=document.querySelector('.files-provider-select');p.value='all';p.dispatchEvent(new Event('change',{bubbles:true}))`); await until('document.querySelector("[data-files-body]")','aggregate view'); await evaluate(`window.__g07ConfirmQueue.push(true); window.__g07Prompts.push('Aggregate.txt'); document.querySelector('[data-files-new]')?.click();`); await until('document.querySelector(".files-action-menu")','aggregate New menu'); await evaluate(`document.querySelector('.files-action-menu-item')?.click()`); await until('document.body.innerText.includes("Created folder: Aggregate.txt")','aggregate picker creation'); assert((await evaluate('window.__g07PickerCalls'))>0); assert(fs.existsSync(path.join(hostRoot,'Aggregate.txt'))); await evaluate(`const hostProvider=document.querySelector('.files-provider-select'); hostProvider.value='host'; hostProvider.dispatchEvent(new Event('change',{bubbles:true}))`); await until('document.body.innerText.includes("Host locations") && document.querySelector("[data-files-body]")','host destination restored');
  if (process.env.G07_ONLY) { console.log(JSON.stringify({ gate:'G07', passed:true, backend:'FastAPI → FilesFacade → exact release odysseus-files-service → generated host root', destination:hostRoot, created:{ toolbarFolder:true, blankZeroFile:true, nestedZeroFile:true, aggregatePicker:true }, zeroByteFiles:['Blank Zero.txt','Toolbar Folder/Nested.txt'], openInEditor:'Blank Zero.txt', pickerCalls:await evaluate('window.__g07PickerCalls') })); await stop(); process.exit(0); }
  // G08 collision=fail is exercised through the real multipart facade route.
  const makeImport=async(name,operation,content='')=>{const form=new FormData();form.append('file',new Blob([content], {type:'text/plain'}),name);form.append('metadata',JSON.stringify({operation_id:operation,item_id:`${operation}-item`,generation,destination_ref:authorized.ref,name,relative_path:name,collision:'fail'}));return request('/api/files-v1/imports',{method:'POST',body:form});}; const first=await makeImport('Collision.txt','g08-collision-1','original'); assert.equal(first.status,200); const second=await makeImport('Collision.txt','g08-collision-2'); assert.equal(second.status,409); assert.equal(fs.readFileSync(path.join(hostRoot,'Collision.txt'),'utf8'),'original');
  // Dropped response after a committed import is reconciled by the UI's
  // operation receipt without a second provider mutation.
  await evaluate(`(()=>{window.__g08Drop=true; window.__g08ImportCalls=0; return import('/static/js/filesFacadeClient.js').then(m=>{const client=m.filesFacadeClient; const prior=client.fetchImpl; client.fetchImpl=async(...args)=>{if(String(args[0]).includes('/imports')) window.__g08ImportCalls+=1; const r=await prior(...args); if(window.__g08Drop && String(args[0]).includes('/imports')){window.__g08Drop=false;throw new TypeError('dropped response after commit');} return r;}; window.__g08DropClient=client;})})()`); await evaluate(`window.__g07ConfirmQueue.push(true); window.__g07Prompts.push('Dropped.txt'); document.querySelector('[data-files-new]')?.click()`); await until('document.querySelector(".files-action-menu")','dropped New menu'); await evaluate(`[...document.querySelectorAll('.files-action-menu-item')].find(x=>x.textContent.trim()==='New File…')?.click()`); await until('document.body.innerText.includes("Created file: Dropped.txt")','dropped response receipt'); assert.equal(await evaluate('window.__g08ImportCalls'),1); assert(fs.existsSync(path.join(hostRoot,'Dropped.txt'))); const droppedSize=fs.statSync(path.join(hostRoot,'Dropped.txt')).size; assert.equal(droppedSize,0);
  // Revocation invalidates the captured destination before commit.
  await evaluate(`window.__g07Prompts.push('Revoked.txt'); const row=document.querySelector('[data-files-selection-key]'); window.__g08Capture=window.__openClankFilesContextCapture(row);`); fs.writeFileSync(registryPath,JSON.stringify(registryWith({enabled:false,generation:3}),null,2)); await evaluate(`window.__g08Revoked=window.__openClankFilesContextCommand('files-new-file',document.querySelector('[data-files-selection-key]'),{adapterContext:window.__g08Capture})`); await delay(300); assert(!fs.existsSync(path.join(hostRoot,'Revoked.txt'))); assert((await evaluate('document.body.innerText')).match(/access changed|authorized|policy/i));
  // Account switch revokes the old owner-bound context; no wrong-owner write.
  fs.writeFileSync(registryPath,JSON.stringify(registryWith({enabled:true,generation:4,owner:'b'}),null,2)); const loginB=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'b',password,remember:true})}); assert.equal(loginB.status,200); const cookieB=(loginB.headers.get('set-cookie')||'').match(/odysseus_session=([^;]+)/)?.[1]; await cdp('Network.setCookie',{name:'odysseus_session',value:cookieB,url:`${base}/`,httpOnly:true,sameSite:'Lax'}); await evaluate(`document.dispatchEvent(new CustomEvent('openclank:auth-user-ready',{detail:{username:'b'}}))`); await evaluate(`window.__g07Prompts.push('AccountSwitch.txt'); window.__g08AccountSwitch=window.__openClankFilesContextCommand('files-new-file',document.querySelector('[data-files-selection-key]'),{adapterContext:window.__g08Capture})`); await delay(300); assert(!fs.existsSync(path.join(hostRoot,'AccountSwitch.txt'))); assert((await evaluate('document.body.innerText')).match(/access changed|authorized|policy|account/i)); console.log(JSON.stringify({gate:'G07-G08',passed:true,backend:'FastAPI → FilesFacade → exact release odysseus-files-service → generated host root',destination:hostRoot,created:{toolbarFolder:true,blankZeroFile:true,nestedZeroFile:true,aggregatePicker:true},zeroByteFiles:['Blank Zero.txt','Toolbar Folder/Nested.txt','Dropped.txt'],openInEditor:'Blank Zero.txt',collision:{status:409,originalPreserved:true},droppedResponse:{reconciled:true,providerMutation:1,duplicate:false},revocation:{denied:true,noWrite:true},accountSwitch:{denied:true,noWrongDestinationWrite:true},pickerCalls:await evaluate('window.__g07PickerCalls') }));
} finally { await stop(); }
