# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import admission_pb2 as admission__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in admission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdmissionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/openclank.files.admission.v1.Admission/Health',
                request_serializer=admission__pb2.HealthRequest.SerializeToString,
                response_deserializer=admission__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Browse = channel.unary_unary(
                '/openclank.files.admission.v1.Admission/Browse',
                request_serializer=admission__pb2.BrowseRequest.SerializeToString,
                response_deserializer=admission__pb2.BrowseResponse.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_stream(
                '/openclank.files.admission.v1.Admission/Transfer',
                request_serializer=admission__pb2.TransferRequest.SerializeToString,
                response_deserializer=admission__pb2.TransferChunk.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/openclank.files.admission.v1.Admission/Metrics',
                request_serializer=admission__pb2.MetricsRequest.SerializeToString,
                response_deserializer=admission__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/openclank.files.admission.v1.Admission/Shutdown',
                request_serializer=admission__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=admission__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class AdmissionServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Browse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=admission__pb2.HealthRequest.FromString,
                    response_serializer=admission__pb2.HealthResponse.SerializeToString,
            ),
            'Browse': grpc.unary_unary_rpc_method_handler(
                    servicer.Browse,
                    request_deserializer=admission__pb2.BrowseRequest.FromString,
                    response_serializer=admission__pb2.BrowseResponse.SerializeToString,
            ),
            'Transfer': grpc.unary_stream_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=admission__pb2.TransferRequest.FromString,
                    response_serializer=admission__pb2.TransferChunk.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=admission__pb2.MetricsRequest.FromString,
                    response_serializer=admission__pb2.MetricsResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=admission__pb2.ShutdownRequest.FromString,
                    response_serializer=admission__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openclank.files.admission.v1.Admission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openclank.files.admission.v1.Admission', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Admission:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclank.files.admission.v1.Admission/Health',
            admission__pb2.HealthRequest.SerializeToString,
            admission__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Browse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclank.files.admission.v1.Admission/Browse',
            admission__pb2.BrowseRequest.SerializeToString,
            admission__pb2.BrowseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openclank.files.admission.v1.Admission/Transfer',
            admission__pb2.TransferRequest.SerializeToString,
            admission__pb2.TransferChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclank.files.admission.v1.Admission/Metrics',
            admission__pb2.MetricsRequest.SerializeToString,
            admission__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclank.files.admission.v1.Admission/Shutdown',
            admission__pb2.ShutdownRequest.SerializeToString,
            admission__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
