# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import files_transport_pb2 as files__transport__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in files_transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilesTransportStub:
    """Private local transport for the canonical open-clank.files/v1 JSON
    envelope. Keeping that envelope intact lets framed stdio and Tonic run in
    parity while typed provider handles are still being implemented.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/openclank.files.transport.v1.FilesTransport/Health',
                request_serializer=files__transport__pb2.HealthRequest.SerializeToString,
                response_deserializer=files__transport__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Dispatch = channel.unary_unary(
                '/openclank.files.transport.v1.FilesTransport/Dispatch',
                request_serializer=files__transport__pb2.DispatchRequest.SerializeToString,
                response_deserializer=files__transport__pb2.DispatchResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_stream(
                '/openclank.files.transport.v1.FilesTransport/Read',
                request_serializer=files__transport__pb2.ReadRequest.SerializeToString,
                response_deserializer=files__transport__pb2.ReadChunk.FromString,
                _registered_method=True)
        self.Thumbnail = channel.unary_unary(
                '/openclank.files.transport.v1.FilesTransport/Thumbnail',
                request_serializer=files__transport__pb2.NativeThumbnailRequest.SerializeToString,
                response_deserializer=files__transport__pb2.NativeThumbnailResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/openclank.files.transport.v1.FilesTransport/Watch',
                request_serializer=files__transport__pb2.WatchRequest.SerializeToString,
                response_deserializer=files__transport__pb2.WatchEvent.FromString,
                _registered_method=True)


class FilesTransportServicer:
    """Private local transport for the canonical open-clank.files/v1 JSON
    envelope. Keeping that envelope intact lets framed stdio and Tonic run in
    parity while typed provider handles are still being implemented.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Thumbnail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=files__transport__pb2.HealthRequest.FromString,
                    response_serializer=files__transport__pb2.HealthResponse.SerializeToString,
            ),
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=files__transport__pb2.DispatchRequest.FromString,
                    response_serializer=files__transport__pb2.DispatchResponse.SerializeToString,
            ),
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=files__transport__pb2.ReadRequest.FromString,
                    response_serializer=files__transport__pb2.ReadChunk.SerializeToString,
            ),
            'Thumbnail': grpc.unary_unary_rpc_method_handler(
                    servicer.Thumbnail,
                    request_deserializer=files__transport__pb2.NativeThumbnailRequest.FromString,
                    response_serializer=files__transport__pb2.NativeThumbnailResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=files__transport__pb2.WatchRequest.FromString,
                    response_serializer=files__transport__pb2.WatchEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openclank.files.transport.v1.FilesTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openclank.files.transport.v1.FilesTransport', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilesTransport:
    """Private local transport for the canonical open-clank.files/v1 JSON
    envelope. Keeping that envelope intact lets framed stdio and Tonic run in
    parity while typed provider handles are still being implemented.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclank.files.transport.v1.FilesTransport/Health',
            files__transport__pb2.HealthRequest.SerializeToString,
            files__transport__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclank.files.transport.v1.FilesTransport/Dispatch',
            files__transport__pb2.DispatchRequest.SerializeToString,
            files__transport__pb2.DispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openclank.files.transport.v1.FilesTransport/Read',
            files__transport__pb2.ReadRequest.SerializeToString,
            files__transport__pb2.ReadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Thumbnail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclank.files.transport.v1.FilesTransport/Thumbnail',
            files__transport__pb2.NativeThumbnailRequest.SerializeToString,
            files__transport__pb2.NativeThumbnailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openclank.files.transport.v1.FilesTransport/Watch',
            files__transport__pb2.WatchRequest.SerializeToString,
            files__transport__pb2.WatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
