"""Managed Imps image projects — versioned editable state with Lore recovery.

Imps (the Image Processing Suite) keeps its editable layers, masks and text in a
managed project record that is bound to a stable Files image resource identity.
This module owns that record: creation, versioned state updates, the recoverable
Save operation, Save-a-copy, and the explicit portable project export.

Recovery is delegated to the shared Lore/history capture seam through an
injected ``lore_capture`` callable — there is no independent Imps recovery
system. A Save captures the original image bytes and the original project state
as preimages before any mutation, then commits expected revisions. Restore
replays those captured preimages.

Nothing here deletes shared generated bytes, editor drafts, or the application
database. The record is additive storage for editable work.
"""

from __future__ import annotations

import base64
import hashlib
import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable, Mapping, MutableMapping, Sequence

from sqlalchemy.orm import Session

from core.database import ManagedImageProject

# Portable project export schema version. Bump only for a breaking change to
# the editable manifest; additive keys must round-trip unknown fields.
EXPORT_SCHEMA_VERSION = 1
EXPORT_KIND = "imps-project"

# The editable state document version understood by the current editor.
STATE_SCHEMA_VERSION = 2

# Optional process-level Lore capture seam. When set, HTTP routes use it as the
# repository's preimage capture callable. It is a plain injectable hook so a
# configured history worker can be wired without a process-global singleton,
# and so tests can substitute a deterministic capture.
ACTIVE_LORE_CAPTURE: Callable[..., Any] | None = None


class ImageProjectError(RuntimeError):
    """Base error for managed project operations."""

    def __init__(self, message: str, *, code: str = "image_project_error") -> None:
        super().__init__(message)
        self.code = code


class StaleProjectRevision(ImageProjectError):
    """The caller's expected project revision is no longer current."""

    def __init__(self, message: str) -> None:
        super().__init__(message, code="stale_project_revision")


class StaleImageRevision(ImageProjectError):
    """The caller's expected image revision is no longer current."""

    def __init__(self, message: str) -> None:
        super().__init__(message, code="stale_image_revision")


class ProjectNotFound(ImageProjectError):
    def __init__(self, message: str = "project not found") -> None:
        super().__init__(message, code="project_not_found")


class LoreCaptureFailed(ImageProjectError):
    """Preimage capture failed; the mutation was left unapplied."""

    def __init__(self, message: str = "preimage capture failed; save left unapplied") -> None:
        super().__init__(message, code="lore_capture_failed")


@dataclass(frozen=True)
class ImageResourceIdentity:
    """Stable identity of the image a project is bound to.

    ``provider`` + ``resource_id`` is the durable pair. Gallery/database row
    identifiers are never the public identity; they are an adapter detail that
    maps onto this pair during the transition.
    """

    provider: str
    resource_id: str

    def as_key(self) -> dict[str, str]:
        return {"provider": self.provider, "resource_id": self.resource_id}

    def stable_id(self, *, owner: str) -> str:
        """Deterministic opaque identity for a given owner + image resource."""
        material = f"{owner}\0{self.provider}\0{self.resource_id}".encode("utf-8")
        return hashlib.sha256(material).hexdigest()[:32]


@dataclass(frozen=True)
class ManagedProjectRecord:
    """Read projection of a managed project row."""

    id: str
    owner: str
    image_provider: str
    image_resource_id: str
    expected_image_revision: str
    project_revision: int
    name: str
    width: int | None
    height: int | None
    state: dict[str, Any]
    is_active: bool
    created_at: datetime | None = None
    updated_at: datetime | None = None

    @property
    def image_identity(self) -> ImageResourceIdentity:
        return ImageResourceIdentity(self.image_provider, self.image_resource_id)


@dataclass
class SaveOutcome:
    """Result of a recoverable Save or Save-a-copy."""

    project_id: str
    project_revision: int
    image_identity: ImageResourceIdentity
    action_id: str | None
    # True when the operation created a brand-new image resource (Save a copy)
    # rather than updating the writable original in place.
    allocated: bool
    refresh_receipt: dict[str, Any] = field(default_factory=dict)


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _state_digest(state: Mapping[str, Any]) -> str:
    payload = json.dumps(state, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _load_state(raw: Any) -> dict[str, Any]:
    if isinstance(raw, Mapping):
        return dict(raw)
    if isinstance(raw, (bytes, bytearray)):
        raw = raw.decode("utf-8", "replace")
    if isinstance(raw, str) and raw.strip():
        try:
            parsed = json.loads(raw)
        except (ValueError, TypeError):
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _normalize_state(state: Mapping[str, Any] | None) -> dict[str, Any]:
    """Accept an editor state document and stamp its schema version."""
    body = dict(state or {})
    body.setdefault("v", STATE_SCHEMA_VERSION)
    return body


def _row_to_record(row: ManagedImageProject) -> ManagedProjectRecord:
    return ManagedProjectRecord(
        id=row.id,
        owner=row.owner or "",
        image_provider=row.image_provider or "",
        image_resource_id=row.image_resource_id or "",
        expected_image_revision=row.expected_image_revision or "",
        project_revision=int(row.project_revision or 1),
        name=row.name or "Untitled",
        width=row.width,
        height=row.height,
        state=_load_state(row.state),
        is_active=bool(row.is_active),
        created_at=row.created_at,
        updated_at=row.updated_at,
    )


class ImageProjectRepository:
    """Versioned managed project storage bound to an image resource identity."""

    def __init__(
        self,
        session_factory: Callable[[], Session],
        *,
        lore_capture: Callable[..., Any] | None = None,
    ) -> None:
        self.session_factory = session_factory
        self.lore_capture = lore_capture

    # ── create / read ──────────────────────────────────────────────────

    def create_project(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity,
        name: str = "Untitled",
        width: int | None = None,
        height: int | None = None,
        state: Mapping[str, Any] | None = None,
        expected_image_revision: str = "",
    ) -> ManagedProjectRecord:
        """Create a managed project bound to an image resource.

        Blank-canvas work is first class: ``image_identity`` still names a
        resource (a draft or a freshly allocated image), so a blank canvas
        persists exactly like any other project.
        """
        if not owner:
            raise ImageProjectError("owner is required", code="owner_required")
        project_id = uuid.uuid4().hex
        now = _utcnow()
        body = _normalize_state(state)
        db = self.session_factory()
        try:
            row = ManagedImageProject(
                id=project_id,
                owner=owner,
                image_provider=image_identity.provider,
                image_resource_id=image_identity.resource_id,
                expected_image_revision=expected_image_revision or "",
                project_revision=1,
                name=name or "Untitled",
                width=width,
                height=height,
                state=json.dumps(body, ensure_ascii=False),
                is_active=True,
                created_at=now,
                updated_at=now,
            )
            db.add(row)
            db.commit()
            db.refresh(row)
            return _row_to_record(row)
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

    def get_project(self, *, project_id: str, owner: str) -> ManagedProjectRecord:
        db = self.session_factory()
        try:
            row = (
                db.query(ManagedImageProject)
                .filter(
                    ManagedImageProject.id == project_id,
                    ManagedImageProject.owner == owner,
                    ManagedImageProject.is_active == True,  # noqa: E712
                )
                .first()
            )
            if row is None:
                raise ProjectNotFound(f"project {project_id} not found")
            return _row_to_record(row)
        finally:
            db.close()

    def list_projects(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity | None = None,
    ) -> list[ManagedProjectRecord]:
        db = self.session_factory()
        try:
            q = db.query(ManagedImageProject).filter(
                ManagedImageProject.owner == owner,
                ManagedImageProject.is_active == True,  # noqa: E712
            )
            if image_identity is not None:
                q = q.filter(
                    ManagedImageProject.image_provider == image_identity.provider,
                    ManagedImageProject.image_resource_id == image_identity.resource_id,
                )
            rows = q.order_by(ManagedImageProject.updated_at.desc()).all()
            return [_row_to_record(row) for row in rows]
        finally:
            db.close()

    def find_for_image(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity,
    ) -> ManagedProjectRecord | None:
        """Return the newest active project bound to an image resource."""
        projects = self.list_projects(owner=owner, image_identity=image_identity)
        return projects[0] if projects else None

    # ── versioned state updates ────────────────────────────────────────

    def update_state(
        self,
        *,
        project_id: str,
        owner: str,
        state: Mapping[str, Any],
        expected_project_revision: int,
        name: str | None = None,
        width: int | None = None,
        height: int | None = None,
        expected_image_revision: str | None = None,
        new_image_revision: str | None = None,
    ) -> ManagedProjectRecord:
        """Commit a new project state under optimistic concurrency.

        ``expected_project_revision`` must match the stored revision. When
        ``expected_image_revision`` is supplied it must match the image
        revision the project is currently bound to (a stale editor cannot
        overwrite work rebased onto a newer image). ``new_image_revision``
        rebinds the project to a new image revision in the same commit.
        """
        db = self.session_factory()
        try:
            row = (
                db.query(ManagedImageProject)
                .filter(
                    ManagedImageProject.id == project_id,
                    ManagedImageProject.owner == owner,
                    ManagedImageProject.is_active == True,  # noqa: E712
                )
                .first()
            )
            if row is None:
                raise ProjectNotFound(f"project {project_id} not found")
            if int(row.project_revision or 1) != int(expected_project_revision):
                raise StaleProjectRevision(
                    f"project {project_id} is at revision {row.project_revision}, "
                    f"not {expected_project_revision}"
                )
            if expected_image_revision is not None and (row.expected_image_revision or "") != expected_image_revision:
                raise StaleImageRevision(
                    f"project {project_id} expects image revision "
                    f"{row.expected_image_revision!r}, not {expected_image_revision!r}"
                )
            row.state = json.dumps(_normalize_state(state), ensure_ascii=False)
            row.project_revision = int(row.project_revision or 1) + 1
            if name is not None:
                row.name = name
            if width is not None:
                row.width = width
            if height is not None:
                row.height = height
            if new_image_revision is not None:
                row.expected_image_revision = new_image_revision
            row.updated_at = _utcnow()
            db.commit()
            db.refresh(row)
            return _row_to_record(row)
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

    def rebind_image_revision(
        self,
        *,
        project_id: str,
        owner: str,
        expected_image_revision: str,
        expected_project_revision: int,
    ) -> ManagedProjectRecord:
        """Move the project onto a new image revision after a successful Save."""
        db = self.session_factory()
        try:
            row = (
                db.query(ManagedImageProject)
                .filter(
                    ManagedImageProject.id == project_id,
                    ManagedImageProject.owner == owner,
                    ManagedImageProject.is_active == True,  # noqa: E712
                )
                .first()
            )
            if row is None:
                raise ProjectNotFound(f"project {project_id} not found")
            if int(row.project_revision or 1) != int(expected_project_revision):
                raise StaleProjectRevision(
                    f"project {project_id} is at revision {row.project_revision}, "
                    f"not {expected_project_revision}"
                )
            row.expected_image_revision = expected_image_revision
            row.project_revision = int(row.project_revision or 1) + 1
            row.updated_at = _utcnow()
            db.commit()
            db.refresh(row)
            return _row_to_record(row)
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

    # ── recoverable Save ───────────────────────────────────────────────

    def save_image_and_project(
        self,
        *,
        owner: str,
        project_id: str,
        expected_project_revision: int,
        expected_image_revision: str,
        new_image_revision: str,
        image_writer: Callable[[], Any],
        state: Mapping[str, Any] | None = None,
        name: str | None = None,
        width: int | None = None,
        height: int | None = None,
        operation_id: str | None = None,
    ) -> SaveOutcome:
        """Save the writable original image and its managed project together.

        Order of operations:

        1. Capture the original image bytes and the original project state as
           Lore preimages. If capture fails, nothing is mutated.
        2. Write the new image bytes through ``image_writer`` and commit the
           expected revisions (image revision + project state).
        3. Preserve the original image identity — Save never reallocates a
           resource.

        ``image_writer`` performs the actual byte write and returns the new
        image revision (or ``None`` to keep ``new_image_revision``). It runs
        only after preimage capture succeeded.
        """
        record = self.get_project(project_id=project_id, owner=owner)
        if int(record.project_revision) != int(expected_project_revision):
            raise StaleProjectRevision(
                f"project {project_id} is at revision {record.project_revision}, "
                f"not {expected_project_revision}"
            )
        if (record.expected_image_revision or "") != (expected_image_revision or ""):
            raise StaleImageRevision(
                f"project {project_id} expects image revision "
                f"{record.expected_image_revision!r}, not {expected_image_revision!r}"
            )

        action_id = operation_id or f"imps-save-{uuid.uuid4().hex}"
        preimage_state = dict(record.state)
        preimage_revision = record.expected_image_revision

        # 1. Lore preimage capture — the mutation is refused if recovery state
        #    could not be made durable.
        self._capture_preimages(
            owner=owner,
            project_id=project_id,
            action_id=action_id,
            record=record,
            preimage_state=preimage_state,
            preimage_revision=preimage_revision,
        )

        # 2. Commit the image bytes, then the project state under CAS. The
        #    guard is the pre-save image revision; the new value rebinds the
        #    project onto the committed revision.
        written_revision = image_writer()
        committed_image_revision = (
            str(written_revision) if written_revision is not None else new_image_revision
        )
        updated = self.update_state(
            project_id=project_id,
            owner=owner,
            state=state if state is not None else record.state,
            expected_project_revision=expected_project_revision,
            name=name,
            width=width,
            height=height,
            expected_image_revision=expected_image_revision,
            new_image_revision=committed_image_revision,
        )
        return SaveOutcome(
            project_id=updated.id,
            project_revision=updated.project_revision,
            image_identity=updated.image_identity,
            action_id=action_id,
            allocated=False,
            refresh_receipt={
                "operation": "save",
                "image": updated.image_identity.as_key(),
                "image_revision": updated.expected_image_revision,
                "project_revision": updated.project_revision,
                "lore_action_id": action_id,
            },
        )

    def save_copy(
        self,
        *,
        owner: str,
        project_id: str,
        image_identity: ImageResourceIdentity,
        expected_image_revision: str,
        image_writer: Callable[[], Any],
        state: Mapping[str, Any] | None = None,
        name: str | None = None,
        width: int | None = None,
        height: int | None = None,
    ) -> SaveOutcome:
        """Allocate a separate image resource and a separate project.

        The source project and its image are left untouched. The new project is
        bound to the freshly allocated ``image_identity``.
        """
        source = self.get_project(project_id=project_id, owner=owner)
        action_id = f"imps-copy-{uuid.uuid4().hex}"

        written_revision = image_writer()
        committed_image_revision = (
            str(written_revision) if written_revision is not None else expected_image_revision
        )
        created = self.create_project(
            owner=owner,
            image_identity=image_identity,
            name=name or f"{source.name} copy",
            width=width if width is not None else source.width,
            height=height if height is not None else source.height,
            state=state if state is not None else source.state,
            expected_image_revision=committed_image_revision,
        )
        return SaveOutcome(
            project_id=created.id,
            project_revision=created.project_revision,
            image_identity=created.image_identity,
            action_id=action_id,
            allocated=True,
            refresh_receipt={
                "operation": "save_copy",
                "source_project_id": source.id,
                "image": created.image_identity.as_key(),
                "image_revision": created.expected_image_revision,
                "project_revision": created.project_revision,
            },
        )

    def _capture_preimages(
        self,
        *,
        owner: str,
        project_id: str,
        action_id: str,
        record: ManagedProjectRecord,
        preimage_state: Mapping[str, Any],
        preimage_revision: str,
    ) -> None:
        """Capture original image + project preimages through Lore.

        The capture callable receives an opaque operation id and the exact
        before-state. Any failure aborts the Save before mutation — a partially
        recoverable Save is worse than a refused one.
        """
        if not callable(self.lore_capture):
            return
        try:
            self.lore_capture(
                operation_id=action_id,
                resource_id=record.image_resource_id,
                provider=record.image_provider,
                owner=owner,
                project_id=project_id,
                preimage=json.dumps(
                    {
                        "kind": "imps_project_preimage",
                        "project_id": project_id,
                        "image_resource": record.image_identity.as_key(),
                        "image_revision": preimage_revision,
                        "project_revision": record.project_revision,
                        "state": dict(preimage_state),
                    },
                    sort_keys=True,
                    ensure_ascii=False,
                ),
                image_revision=preimage_revision,
                project_revision=record.project_revision,
            )
        except LoreCaptureFailed:
            raise
        except Exception as exc:  # noqa: BLE001 — refuse the save on capture failure
            raise LoreCaptureFailed(
                f"preimage capture failed; save left unapplied: {exc}"
            ) from exc

    # ── portable project export / import ───────────────────────────────

    def export_project(
        self,
        *,
        project_id: str,
        owner: str,
        assets: Sequence[Mapping[str, Any]] = (),
    ) -> dict[str, Any]:
        """Explicit portable export of an editable project.

        The export carries the editable manifest plus the assets required to
        restore layers/text/masks. It is never written as a companion sidecar
        beside the image — callers decide where the bytes go.
        """
        record = self.get_project(project_id=project_id, owner=owner)
        return {
            "kind": EXPORT_KIND,
            "schema_version": EXPORT_SCHEMA_VERSION,
            "name": record.name,
            "width": record.width,
            "height": record.height,
            "image": {
                **record.image_identity.as_key(),
                "revision": record.expected_image_revision,
            },
            "project_revision": record.project_revision,
            "state": dict(record.state),
            "assets": [dict(asset) for asset in assets],
        }

    def import_project(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity,
        bundle: Mapping[str, Any],
        expected_image_revision: str = "",
    ) -> ManagedProjectRecord:
        """Restore an exported project under a (possibly new) image resource.

        Unknown future keys in the bundle round-trip in the state document so a
        newer export can be held by an older reader without losing data.
        """
        if str(bundle.get("kind") or "") != EXPORT_KIND:
            raise ImageProjectError(
                "bundle is not an Imps project export", code="invalid_export"
            )
        state = _load_state(bundle.get("state"))
        # Preserve unknown top-level state keys verbatim.
        if isinstance(bundle.get("state"), Mapping):
            state = {**dict(bundle["state"]), **state}
        return self.create_project(
            owner=owner,
            image_identity=image_identity,
            name=str(bundle.get("name") or "Untitled"),
            width=bundle.get("width"),
            height=bundle.get("height"),
            state=state,
            expected_image_revision=expected_image_revision
            or str((bundle.get("image") or {}).get("revision") or ""),
        )
