"""Managed Imps image projects — versioned editable state with Lore recovery.

Imps (the Image Processing Suite) keeps its editable layers, masks and text in a
managed project record that is bound to a stable Files image resource identity.
This module owns that record: creation, versioned state updates, the recoverable
Save operation, Save-a-copy, and the explicit portable project export.

Recovery is delegated to the shared Lore/history capture seam through an
injected ``lore_capture`` callable — there is no independent Imps recovery
system. A Save captures a durable preimage before any mutation, then commits
expected revisions. Restore replays a captured preimage.

What the preimage actually contains (this is the honest limit):

* always — the original project state document and the original image revision;
* when the caller supplies ``image_bytes`` (an ``image_reader`` read of the
  writable original) — those exact bytes, base64-encoded with a sha256 digest.

When no image reader is available the payload records
``image_bytes_captured: false`` rather than pretending bytes were stored.

Nothing here deletes shared generated bytes, editor drafts, or the application
database. The record is additive storage for editable work.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

from sqlalchemy.orm import Session

from core.database import ManagedImageProject

# Portable project export schema version. Bump only for a breaking change to
# the editable manifest; additive keys must round-trip unknown fields.
EXPORT_SCHEMA_VERSION = 1
EXPORT_KIND = "imps-project"

# The editable state document version understood by the current editor.
STATE_SCHEMA_VERSION = 2

# Preimage envelope kind. Restoring is keyed on this marker.
PREIMAGE_KIND = "imps_project_preimage"

# Honest limitation id: history-worker-side preimage discovery (reading a
# preimage back out of the history service without its local managed copy) is
# not orchestrated. Replay uses the local managed preimage store.
L_S19_LORE_RESTORE = "L-S19-LORE-RESTORE"

_ACTION_ID_RE = re.compile(r"^[A-Za-z0-9._:-]{1,128}$")


def preimage_store_root() -> Path:
    """Managed root for durable Imps preimages.

    Overridable via ``IMPS_PREIMAGE_DIR`` (tests point it at a tmp dir).
    Defaults to the application data dir so preimages live with other managed
    state and are never written beside the image as a companion file.
    """
    override = str(os.getenv("IMPS_PREIMAGE_DIR") or "").strip()
    if override:
        return Path(override).expanduser().resolve()
    from src.constants import DATA_DIR

    return Path(DATA_DIR).expanduser().resolve() / "imps_preimages"


def _preimage_path(action_id: str) -> Path:
    if not _ACTION_ID_RE.fullmatch(action_id or ""):
        raise LoreCaptureFailed(f"invalid lore action id {action_id!r}")
    return preimage_store_root() / f"{action_id}.preimage.json"


def default_lore_capture(
    *,
    operation_id: str,
    preimage: str,
    document_id: str | None = None,
    project_id: str | None = None,
    resource_id: str | None = None,
    provider: str | None = None,
    owner: str | None = None,
    image_revision: str | None = None,
    project_revision: int | None = None,
    **_extra: Any,
) -> dict[str, Any]:
    """Production ``ACTIVE_LORE_CAPTURE``: durable capture on the real path.

    The preimage bytes are written with ``core.atomic_io.atomic_write_bytes`` —
    the same capture path every managed file mutation uses — so a configured
    history worker sees the exact before-state and an unconfigured one leaves an
    honest ``history_status`` in the receipt instead of a silent no-op.

    The signature accepts both the S17 document seam
    (``document_id``/``preimage``/``operation_id``) and the Imps project seam,
    so one hook serves both callers.
    """
    payload = str(preimage or "")
    if not payload:
        raise LoreCaptureFailed("empty preimage payload")
    action_id = str(operation_id or "").strip()
    target = _preimage_path(action_id)
    data = payload.encode("utf-8")
    try:
        from core.atomic_io import atomic_write_bytes

        digest = atomic_write_bytes(
            str(target),
            data,
            action_id=action_id,
        )
    except LoreCaptureFailed:
        raise
    except Exception as exc:  # noqa: BLE001 — refuse the save on capture failure
        raise LoreCaptureFailed(
            f"preimage capture failed; save left unapplied: {exc}"
        ) from exc
    return {
        "action_id": action_id,
        "history_status": "complete",
        "capture_phase": "before_durable",
        "preimage_path": str(target),
        "fingerprint": digest,
        "document_id": document_id,
        "project_id": project_id,
        "resource_key": {"provider": provider, "resource_id": resource_id},
        "owner": owner,
        "image_revision": image_revision,
        "project_revision": project_revision,
    }


def read_captured_preimage(action_id: str) -> dict[str, Any] | None:
    """Read back a durable preimage captured by ``default_lore_capture``."""
    try:
        target = _preimage_path(action_id)
    except LoreCaptureFailed:
        return None
    try:
        raw = target.read_text(encoding="utf-8")
    except (OSError, ValueError):
        return None
    try:
        parsed = json.loads(raw)
    except (ValueError, TypeError):
        return None
    return parsed if isinstance(parsed, dict) else None


# Process-level Lore capture seam. Routes pass this to the repository so a
# configured history worker is engaged in production; tests substitute a
# deterministic capture. Assigned at import so production Save is never a
# silent no-op for recovery.
ACTIVE_LORE_CAPTURE: Callable[..., Any] | None = default_lore_capture


class ImageProjectError(RuntimeError):
    """Base error for managed project operations."""

    def __init__(self, message: str, *, code: str = "image_project_error") -> None:
        super().__init__(message)
        self.code = code


class StaleProjectRevision(ImageProjectError):
    """The caller's expected project revision is no longer current."""

    def __init__(self, message: str) -> None:
        super().__init__(message, code="stale_project_revision")


class StaleImageRevision(ImageProjectError):
    """The caller's expected image revision is no longer current."""

    def __init__(self, message: str) -> None:
        super().__init__(message, code="stale_image_revision")


class ProjectNotFound(ImageProjectError):
    def __init__(self, message: str = "project not found") -> None:
        super().__init__(message, code="project_not_found")


class LoreCaptureFailed(ImageProjectError):
    """Preimage capture failed; the mutation was left unapplied."""

    def __init__(self, message: str = "preimage capture failed; save left unapplied") -> None:
        super().__init__(message, code="lore_capture_failed")


@dataclass(frozen=True)
class ImageResourceIdentity:
    """Stable identity of the image a project is bound to.

    ``provider`` + ``resource_id`` is the durable pair. Gallery/database row
    identifiers are never the public identity; they are an adapter detail that
    maps onto this pair during the transition.
    """

    provider: str
    resource_id: str

    def as_key(self) -> dict[str, str]:
        return {"provider": self.provider, "resource_id": self.resource_id}

    def stable_id(self, *, owner: str) -> str:
        """Deterministic opaque identity for a given owner + image resource."""
        material = f"{owner}\0{self.provider}\0{self.resource_id}".encode("utf-8")
        return hashlib.sha256(material).hexdigest()[:32]


@dataclass(frozen=True)
class ManagedProjectRecord:
    """Read projection of a managed project row."""

    id: str
    owner: str
    image_provider: str
    image_resource_id: str
    expected_image_revision: str
    project_revision: int
    name: str
    width: int | None
    height: int | None
    state: dict[str, Any]
    is_active: bool
    created_at: datetime | None = None
    updated_at: datetime | None = None

    @property
    def image_identity(self) -> ImageResourceIdentity:
        return ImageResourceIdentity(self.image_provider, self.image_resource_id)


@dataclass
class SaveOutcome:
    """Result of a recoverable Save or Save-a-copy."""

    project_id: str
    project_revision: int
    image_identity: ImageResourceIdentity
    action_id: str | None
    # True when the operation created a brand-new image resource (Save a copy)
    # rather than updating the writable original in place.
    allocated: bool
    refresh_receipt: dict[str, Any] = field(default_factory=dict)
    # Receipt returned by the Lore capture seam (or ``None`` when the call site
    # did not capture). Carries the honest capture status, not a claim.
    lore_receipt: dict[str, Any] | None = None


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _state_digest(state: Mapping[str, Any]) -> str:
    payload = json.dumps(state, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _load_state(raw: Any) -> dict[str, Any]:
    if isinstance(raw, Mapping):
        return dict(raw)
    if isinstance(raw, (bytes, bytearray)):
        raw = raw.decode("utf-8", "replace")
    if isinstance(raw, str) and raw.strip():
        try:
            parsed = json.loads(raw)
        except (ValueError, TypeError):
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _normalize_state(state: Mapping[str, Any] | None) -> dict[str, Any]:
    """Accept an editor state document and stamp its schema version."""
    body = dict(state or {})
    body.setdefault("v", STATE_SCHEMA_VERSION)
    return body


def _row_to_record(row: ManagedImageProject) -> ManagedProjectRecord:
    return ManagedProjectRecord(
        id=row.id,
        owner=row.owner or "",
        image_provider=row.image_provider or "",
        image_resource_id=row.image_resource_id or "",
        expected_image_revision=row.expected_image_revision or "",
        project_revision=int(row.project_revision or 1),
        name=row.name or "Untitled",
        width=row.width,
        height=row.height,
        state=_load_state(row.state),
        is_active=bool(row.is_active),
        created_at=row.created_at,
        updated_at=row.updated_at,
    )


class ImageProjectRepository:
    """Versioned managed project storage bound to an image resource identity."""

    def __init__(
        self,
        session_factory: Callable[[], Session],
        *,
        lore_capture: Callable[..., Any] | None = None,
    ) -> None:
        self.session_factory = session_factory
        self.lore_capture = lore_capture

    # ── create / read ──────────────────────────────────────────────────

    def create_project(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity,
        name: str = "Untitled",
        width: int | None = None,
        height: int | None = None,
        state: Mapping[str, Any] | None = None,
        expected_image_revision: str = "",
    ) -> ManagedProjectRecord:
        """Create a managed project bound to an image resource.

        Blank-canvas work is first class: ``image_identity`` still names a
        resource (a draft or a freshly allocated image), so a blank canvas
        persists exactly like any other project.
        """
        if not owner:
            raise ImageProjectError("owner is required", code="owner_required")
        project_id = uuid.uuid4().hex
        now = _utcnow()
        body = _normalize_state(state)
        db = self.session_factory()
        try:
            row = ManagedImageProject(
                id=project_id,
                owner=owner,
                image_provider=image_identity.provider,
                image_resource_id=image_identity.resource_id,
                expected_image_revision=expected_image_revision or "",
                project_revision=1,
                name=name or "Untitled",
                width=width,
                height=height,
                state=json.dumps(body, ensure_ascii=False),
                is_active=True,
                created_at=now,
                updated_at=now,
            )
            db.add(row)
            db.commit()
            db.refresh(row)
            return _row_to_record(row)
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

    def get_project(self, *, project_id: str, owner: str) -> ManagedProjectRecord:
        db = self.session_factory()
        try:
            row = (
                db.query(ManagedImageProject)
                .filter(
                    ManagedImageProject.id == project_id,
                    ManagedImageProject.owner == owner,
                    ManagedImageProject.is_active == True,  # noqa: E712
                )
                .first()
            )
            if row is None:
                raise ProjectNotFound(f"project {project_id} not found")
            return _row_to_record(row)
        finally:
            db.close()

    def list_projects(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity | None = None,
    ) -> list[ManagedProjectRecord]:
        db = self.session_factory()
        try:
            q = db.query(ManagedImageProject).filter(
                ManagedImageProject.owner == owner,
                ManagedImageProject.is_active == True,  # noqa: E712
            )
            if image_identity is not None:
                q = q.filter(
                    ManagedImageProject.image_provider == image_identity.provider,
                    ManagedImageProject.image_resource_id == image_identity.resource_id,
                )
            rows = q.order_by(ManagedImageProject.updated_at.desc()).all()
            return [_row_to_record(row) for row in rows]
        finally:
            db.close()

    def find_for_image(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity,
    ) -> ManagedProjectRecord | None:
        """Return the newest active project bound to an image resource."""
        projects = self.list_projects(owner=owner, image_identity=image_identity)
        return projects[0] if projects else None

    # ── versioned state updates ────────────────────────────────────────

    def update_state(
        self,
        *,
        project_id: str,
        owner: str,
        state: Mapping[str, Any],
        expected_project_revision: int,
        name: str | None = None,
        width: int | None = None,
        height: int | None = None,
        expected_image_revision: str | None = None,
        new_image_revision: str | None = None,
    ) -> ManagedProjectRecord:
        """Commit a new project state under optimistic concurrency.

        ``expected_project_revision`` must match the stored revision. When
        ``expected_image_revision`` is supplied it must match the image
        revision the project is currently bound to (a stale editor cannot
        overwrite work rebased onto a newer image). ``new_image_revision``
        rebinds the project to a new image revision in the same commit.
        """
        db = self.session_factory()
        try:
            row = (
                db.query(ManagedImageProject)
                .filter(
                    ManagedImageProject.id == project_id,
                    ManagedImageProject.owner == owner,
                    ManagedImageProject.is_active == True,  # noqa: E712
                )
                .first()
            )
            if row is None:
                raise ProjectNotFound(f"project {project_id} not found")
            if int(row.project_revision or 1) != int(expected_project_revision):
                raise StaleProjectRevision(
                    f"project {project_id} is at revision {row.project_revision}, "
                    f"not {expected_project_revision}"
                )
            if expected_image_revision is not None and (row.expected_image_revision or "") != expected_image_revision:
                raise StaleImageRevision(
                    f"project {project_id} expects image revision "
                    f"{row.expected_image_revision!r}, not {expected_image_revision!r}"
                )
            row.state = json.dumps(_normalize_state(state), ensure_ascii=False)
            row.project_revision = int(row.project_revision or 1) + 1
            if name is not None:
                row.name = name
            if width is not None:
                row.width = width
            if height is not None:
                row.height = height
            if new_image_revision is not None:
                row.expected_image_revision = new_image_revision
            row.updated_at = _utcnow()
            db.commit()
            db.refresh(row)
            return _row_to_record(row)
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

    def rebind_image_revision(
        self,
        *,
        project_id: str,
        owner: str,
        expected_image_revision: str,
        expected_project_revision: int,
    ) -> ManagedProjectRecord:
        """Move the project onto a new image revision after a successful Save."""
        db = self.session_factory()
        try:
            row = (
                db.query(ManagedImageProject)
                .filter(
                    ManagedImageProject.id == project_id,
                    ManagedImageProject.owner == owner,
                    ManagedImageProject.is_active == True,  # noqa: E712
                )
                .first()
            )
            if row is None:
                raise ProjectNotFound(f"project {project_id} not found")
            if int(row.project_revision or 1) != int(expected_project_revision):
                raise StaleProjectRevision(
                    f"project {project_id} is at revision {row.project_revision}, "
                    f"not {expected_project_revision}"
                )
            row.expected_image_revision = expected_image_revision
            row.project_revision = int(row.project_revision or 1) + 1
            row.updated_at = _utcnow()
            db.commit()
            db.refresh(row)
            return _row_to_record(row)
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

    # ── recoverable Save ───────────────────────────────────────────────

    def save_image_and_project(
        self,
        *,
        owner: str,
        project_id: str,
        expected_project_revision: int,
        expected_image_revision: str,
        new_image_revision: str,
        image_writer: Callable[[], Any],
        state: Mapping[str, Any] | None = None,
        name: str | None = None,
        width: int | None = None,
        height: int | None = None,
        operation_id: str | None = None,
        image_bytes: bytes | None = None,
    ) -> SaveOutcome:
        """Save the writable original image and its managed project together.

        Order of operations:

        1. Capture a durable Lore preimage: the original project state always,
           and the original image bytes when ``image_bytes`` is supplied (an
           ``image_reader`` read of the writable original). If capture fails,
           nothing is mutated.
        2. Write the new image bytes through ``image_writer`` and commit the
           expected revisions (image revision + project state).
        3. Preserve the original image identity — Save never reallocates a
           resource.

        ``image_writer`` performs the actual byte write and returns the new
        image revision (or ``None`` to keep ``new_image_revision``). It runs
        only after preimage capture succeeded. When the call site owns the byte
        write (a caller-supplied revision with no bytes here), the refresh
        receipt reports ``image_write: "caller-owned"`` rather than claiming
        this surface wrote the image.
        """
        record = self.get_project(project_id=project_id, owner=owner)
        if int(record.project_revision) != int(expected_project_revision):
            raise StaleProjectRevision(
                f"project {project_id} is at revision {record.project_revision}, "
                f"not {expected_project_revision}"
            )
        if (record.expected_image_revision or "") != (expected_image_revision or ""):
            raise StaleImageRevision(
                f"project {project_id} expects image revision "
                f"{record.expected_image_revision!r}, not {expected_image_revision!r}"
            )

        action_id = operation_id or f"imps-save-{uuid.uuid4().hex}"
        preimage_state = dict(record.state)
        preimage_revision = record.expected_image_revision

        # 1. Lore preimage capture — the mutation is refused if recovery state
        #    could not be made durable.
        lore_receipt = self._capture_preimages(
            owner=owner,
            project_id=project_id,
            action_id=action_id,
            record=record,
            preimage_state=preimage_state,
            preimage_revision=preimage_revision,
            image_bytes=image_bytes,
        )

        # 2. Commit the image bytes, then the project state under CAS. The
        #    guard is the pre-save image revision; the new value rebinds the
        #    project onto the committed revision.
        written_revision = image_writer()
        committed_image_revision = (
            str(written_revision) if written_revision is not None else new_image_revision
        )
        updated = self.update_state(
            project_id=project_id,
            owner=owner,
            state=state if state is not None else record.state,
            expected_project_revision=expected_project_revision,
            name=name,
            width=width,
            height=height,
            expected_image_revision=expected_image_revision,
            new_image_revision=committed_image_revision,
        )
        return SaveOutcome(
            project_id=updated.id,
            project_revision=updated.project_revision,
            image_identity=updated.image_identity,
            action_id=action_id,
            allocated=False,
            lore_receipt=lore_receipt,
            refresh_receipt={
                "operation": "save",
                "image": updated.image_identity.as_key(),
                "image_revision": updated.expected_image_revision,
                "project_revision": updated.project_revision,
                "lore_action_id": action_id,
                "lore": lore_receipt or {},
                "image_write": (
                    "captured-and-written" if image_bytes is not None else "caller-owned"
                ),
                "restore": {
                    "path": "replay_preimage",
                    "action_id": action_id,
                    "limitation": L_S19_LORE_RESTORE,
                },
            },
        )

    def save_copy(
        self,
        *,
        owner: str,
        project_id: str,
        image_identity: ImageResourceIdentity,
        expected_image_revision: str,
        image_writer: Callable[[], Any],
        state: Mapping[str, Any] | None = None,
        name: str | None = None,
        width: int | None = None,
        height: int | None = None,
    ) -> SaveOutcome:
        """Allocate a separate image resource and a separate project.

        The source project and its image are left untouched. The new project is
        bound to the freshly allocated ``image_identity``.
        """
        source = self.get_project(project_id=project_id, owner=owner)
        action_id = f"imps-copy-{uuid.uuid4().hex}"

        written_revision = image_writer()
        committed_image_revision = (
            str(written_revision) if written_revision is not None else expected_image_revision
        )
        created = self.create_project(
            owner=owner,
            image_identity=image_identity,
            name=name or f"{source.name} copy",
            width=width if width is not None else source.width,
            height=height if height is not None else source.height,
            state=state if state is not None else source.state,
            expected_image_revision=committed_image_revision,
        )
        return SaveOutcome(
            project_id=created.id,
            project_revision=created.project_revision,
            image_identity=created.image_identity,
            action_id=action_id,
            allocated=True,
            refresh_receipt={
                "operation": "save_copy",
                "source_project_id": source.id,
                "image": created.image_identity.as_key(),
                "image_revision": created.expected_image_revision,
                "project_revision": created.project_revision,
            },
        )

    def _capture_preimages(
        self,
        *,
        owner: str,
        project_id: str,
        action_id: str,
        record: ManagedProjectRecord,
        preimage_state: Mapping[str, Any],
        preimage_revision: str,
        image_bytes: bytes | None = None,
    ) -> dict[str, Any]:
        """Capture original project + image preimages through Lore.

        The capture callable receives an opaque operation id and the exact
        before-state. The payload always carries the original project state and
        image revision; it carries the original image bytes only when the
        caller supplied them (``image_bytes_captured`` is then ``true``). Any
        capture failure aborts the Save before mutation — a partially
        recoverable Save is worse than a refused one. An unhooked seam is a
        capture failure, not a silent skip.
        """
        capture = self.lore_capture if callable(self.lore_capture) else ACTIVE_LORE_CAPTURE
        if not callable(capture):
            raise LoreCaptureFailed(
                "no Lore capture seam is configured; save left unapplied"
            )
        if image_bytes is not None and not isinstance(image_bytes, (bytes, bytearray)):
            raise LoreCaptureFailed("image_bytes must be bytes or None")
        body = {
            "kind": PREIMAGE_KIND,
            "project_id": project_id,
            "image_resource": record.image_identity.as_key(),
            "image_revision": preimage_revision,
            "project_revision": record.project_revision,
            "state": dict(preimage_state),
        }
        if image_bytes is not None:
            raw = bytes(image_bytes)
            body["image_bytes"] = base64.b64encode(raw).decode("ascii")
            body["image_bytes_encoding"] = "base64"
            body["image_bytes_sha256"] = hashlib.sha256(raw).hexdigest()
            body["image_bytes_captured"] = True
        else:
            body["image_bytes"] = None
            body["image_bytes_captured"] = False
        try:
            receipt = capture(
                operation_id=action_id,
                resource_id=record.image_resource_id,
                provider=record.image_provider,
                owner=owner,
                project_id=project_id,
                preimage=json.dumps(body, sort_keys=True, ensure_ascii=False),
                image_revision=preimage_revision,
                project_revision=record.project_revision,
            )
        except LoreCaptureFailed:
            raise
        except Exception as exc:  # noqa: BLE001 — refuse the save on capture failure
            raise LoreCaptureFailed(
                f"preimage capture failed; save left unapplied: {exc}"
            ) from exc
        return dict(receipt) if isinstance(receipt, Mapping) else {"result": receipt}

    def replay_preimage(
        self,
        *,
        owner: str,
        project_id: str,
        action_id: str,
        image_writer: Callable[[], Any] | None = None,
        expected_project_revision: int | None = None,
    ) -> SaveOutcome:
        """Restore a Save by replaying its captured preimage.

        The project state is restored to the captured before-state under
        optimistic concurrency. When the preimage carries image bytes and an
        ``image_writer`` is supplied, those bytes are written back too. History
        worker-side discovery of preimages (without the local managed copy) is
        not orchestrated — see ``L_S19_LORE_RESTORE``.
        """
        if not owner:
            raise ImageProjectError("owner is required", code="owner_required")
        payload = read_captured_preimage(action_id)
        if not payload or str(payload.get("kind") or "") != PREIMAGE_KIND:
            raise ImageProjectError(
                f"no captured preimage for {action_id}", code="preimage_missing"
            )
        if str(payload.get("project_id") or "") != project_id:
            raise ImageProjectError(
                "preimage belongs to a different project", code="preimage_mismatch"
            )
        current = self.get_project(project_id=project_id, owner=owner)
        expected_revision = (
            current.project_revision
            if expected_project_revision is None
            else int(expected_project_revision)
        )
        restored_state = _load_state(payload.get("state"))
        restored_image_revision = str(payload.get("image_revision") or "")
        image_restored = False
        written_revision = None
        if image_writer is not None and payload.get("image_bytes_captured"):
            raw = base64.b64decode(str(payload.get("image_bytes") or ""), validate=True)
            digest = str(payload.get("image_bytes_sha256") or "")
            if digest and hashlib.sha256(raw).hexdigest() != digest:
                raise ImageProjectError(
                    "captured preimage image bytes are corrupt", code="preimage_corrupt"
                )
            written_revision = image_writer()
            image_restored = True
        committed_image_revision = (
            str(written_revision)
            if written_revision is not None
            else restored_image_revision or current.expected_image_revision
        )
        updated = self.update_state(
            project_id=project_id,
            owner=owner,
            state=restored_state,
            expected_project_revision=expected_revision,
            expected_image_revision=current.expected_image_revision,
            new_image_revision=committed_image_revision,
        )
        return SaveOutcome(
            project_id=updated.id,
            project_revision=updated.project_revision,
            image_identity=updated.image_identity,
            action_id=action_id,
            allocated=False,
            refresh_receipt={
                "operation": "replay_restore",
                "image": updated.image_identity.as_key(),
                "image_revision": updated.expected_image_revision,
                "project_revision": updated.project_revision,
                "lore_action_id": action_id,
                "image_restored": image_restored,
                "state_restored": True,
                "limitation": L_S19_LORE_RESTORE,
            },
        )

    # ── portable project export / import ───────────────────────────────

    def export_project(
        self,
        *,
        project_id: str,
        owner: str,
        assets: Sequence[Mapping[str, Any]] = (),
    ) -> dict[str, Any]:
        """Explicit portable export of an editable project.

        The export carries the editable manifest plus the assets required to
        restore layers/text/masks. It is never written as a companion sidecar
        beside the image — callers decide where the bytes go.
        """
        record = self.get_project(project_id=project_id, owner=owner)
        return {
            "kind": EXPORT_KIND,
            "schema_version": EXPORT_SCHEMA_VERSION,
            "name": record.name,
            "width": record.width,
            "height": record.height,
            "image": {
                **record.image_identity.as_key(),
                "revision": record.expected_image_revision,
            },
            "project_revision": record.project_revision,
            "state": dict(record.state),
            "assets": [dict(asset) for asset in assets],
        }

    def import_project(
        self,
        *,
        owner: str,
        image_identity: ImageResourceIdentity,
        bundle: Mapping[str, Any],
        expected_image_revision: str = "",
    ) -> ManagedProjectRecord:
        """Restore an exported project under a (possibly new) image resource.

        Unknown future keys in the bundle round-trip in the state document so a
        newer export can be held by an older reader without losing data.
        """
        if str(bundle.get("kind") or "") != EXPORT_KIND:
            raise ImageProjectError(
                "bundle is not an Imps project export", code="invalid_export"
            )
        state = _load_state(bundle.get("state"))
        # Preserve unknown top-level state keys verbatim.
        if isinstance(bundle.get("state"), Mapping):
            state = {**dict(bundle["state"]), **state}
        return self.create_project(
            owner=owner,
            image_identity=image_identity,
            name=str(bundle.get("name") or "Untitled"),
            width=bundle.get("width"),
            height=bundle.get("height"),
            state=state,
            expected_image_revision=expected_image_revision
            or str((bundle.get("image") or {}).get("revision") or ""),
        )
