import assert from 'node:assert/strict';
import { findReferenceToken, resolveReference, extractReferenceSection, mediaKind } from '../../static/js/copal/markdownResources.js';

const origin = { id:'note', name:'Notes/旅行.md' };
const documents = [origin, { id:'local', name:'Notes/photo one.png', kind:'asset' }, { id:'other', name:'Other/photo one.png', kind:'asset' }, { id:'root', name:'root.png', kind:'asset' }, { id:'alias', name:'Manual/Guide.md', properties:{ aliases:['Help'] } }];
const resolve = source => resolveReference(findReferenceToken(source), { documents, origin });
assert.equal(resolve('before ![](./photo%20one.png) after').target.id, 'local');
assert.equal(resolve('![[photo one.png|240x120]] trailing').target.id, 'local');
assert.equal(resolve('![](../root.png)').target.id, 'root');
assert.equal(resolve('![](/root.png)').target.id, 'root');
assert.equal(resolve('![](../../root.png)').status, 'missing');
assert.equal(resolve('![](./missing.png)').status, 'missing');
assert.equal(resolve('[[Help#Getting started|Read this]]').target.id, 'alias');
assert.equal(resolve('[[#Heading]]').target.id, 'note');
assert.equal(resolveReference(findReferenceToken('![[photo one.png]]'), { documents }).status, 'ambiguous');
assert.equal(resolve('![](file:///tmp/private.png)').status, 'unsupported');
assert.equal(resolve('![](https://example.invalid/image.png)').status, 'external');
const reference = findReferenceToken('before ![alt](<./photo (one).png> "Photo title") after');
assert.equal(reference.index, 7);
assert.equal(reference.target, './photo (one).png');
assert.equal(reference.title, 'Photo title');
assert.equal('before ![alt](<./photo (one).png> "Photo title") after'.slice(reference.index + reference.length), ' after');
assert.equal(findReferenceToken('\\!\\[\\[not a link\\]\\]'), null);
assert.equal(findReferenceToken('![broken](unclosed'), null);
assert.equal(mediaKind({ name:'recording.wav' }), 'audio');
assert.equal(mediaKind({ name:'film.webm' }), 'video');
assert.equal(mediaKind({ name:'manual.pdf' }), 'pdf');
const source = '# Top\nintro\n## Kept\nwanted\n```md\n## Fake\n```\n### Nested\nmore\n## Omitted\nother\n';
const section = extractReferenceSection(source, 'Kept');
assert.equal(section.line, 3);
assert(section.text.includes('wanted'));
assert(section.text.includes('### Nested'));
assert(!section.text.includes('Omitted'));
assert.equal(extractReferenceSection('# Same\none\n# Same\ntwo', 'Same').status, 'ambiguous');
assert.equal(extractReferenceSection(source, 'Fake').status, 'missing');
assert.equal(extractReferenceSection('first paragraph\n\nblock first\nblock last ^keep\n\nafter', '^keep').text, 'block first\nblock last ^keep');
console.log('Copal shared Markdown reference resolution passed');
