-- Generated by the explicit offline Frankenmemory tool. Current schema v14.
CREATE TABLE curated (
                id TEXT PRIMARY KEY,
                content TEXT NOT NULL,
                kind TEXT NOT NULL DEFAULT 'episodic',
                priority INTEGER NOT NULL DEFAULT 50,
                trust_score REAL NOT NULL DEFAULT 0.50,
                confidence_score REAL NOT NULL DEFAULT 0.6,
                importance_score REAL NOT NULL DEFAULT 0.5,
                scene_name TEXT,
                source TEXT NOT NULL DEFAULT '',
                source_type TEXT NOT NULL DEFAULT 'auto_extracted',
                owner TEXT,
                workspace_id TEXT NOT NULL DEFAULT 'global',
                session_key TEXT NOT NULL DEFAULT '',
                session_id TEXT NOT NULL DEFAULT '',
                tags TEXT NOT NULL DEFAULT '[]',
                source_message_ids TEXT NOT NULL DEFAULT '[]',
                timestamps TEXT NOT NULL DEFAULT '[]',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                archived INTEGER NOT NULL DEFAULT 0,
                last_accessed_at TEXT,
                exempt_from_decay INTEGER NOT NULL DEFAULT 0,
                exempt_from_dedup INTEGER NOT NULL DEFAULT 0,
                metadata TEXT NOT NULL DEFAULT 'null',
                workspace_path TEXT,
                embedding BLOB
            );
CREATE TABLE raw (
                id TEXT PRIMARY KEY,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                session_key TEXT NOT NULL DEFAULT '',
                session_id TEXT NOT NULL DEFAULT '',
                workspace_id TEXT NOT NULL DEFAULT 'global',
                owner TEXT,
                recorded_at TEXT NOT NULL,
                metadata TEXT NOT NULL DEFAULT 'null',
                workspace_path TEXT,
                embedding BLOB
            );
CREATE TABLE facts (
                id TEXT PRIMARY KEY,
                content TEXT NOT NULL,
                entities TEXT NOT NULL DEFAULT '[]',
                trust_score REAL NOT NULL DEFAULT 0.50,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                embedding BLOB
            , owner TEXT, workspace_id TEXT NOT NULL DEFAULT 'global', candidate_id TEXT, status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE graph_nodes (
                id TEXT PRIMARY KEY,
                kind TEXT NOT NULL,
                label TEXT,
                name TEXT NOT NULL,
                norm_name TEXT NOT NULL,
                layer TEXT NOT NULL DEFAULT 'semantic',
                ref_table TEXT,
                ref_id TEXT,
                trust INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL,
                last_seen TEXT NOT NULL
            , owner TEXT, workspace_id TEXT NOT NULL DEFAULT 'global', candidate_id TEXT, status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE graph_cues (
                cue TEXT NOT NULL,
                node_id TEXT NOT NULL,
                source TEXT NOT NULL DEFAULT 'extracted',
                created_at TEXT NOT NULL, owner TEXT, workspace_id TEXT NOT NULL DEFAULT 'global', candidate_id TEXT, status TEXT NOT NULL DEFAULT 'active',
                PRIMARY KEY (cue, node_id)
            );
CREATE TABLE graph_edges (
                id TEXT PRIMARY KEY,
                src_id TEXT NOT NULL,
                tag TEXT NOT NULL,
                dst_id TEXT NOT NULL,
                fact_id TEXT,
                weight REAL NOT NULL DEFAULT 1.0,
                traversal_count INTEGER NOT NULL DEFAULT 0,
                trust INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL,
                last_seen TEXT NOT NULL, owner TEXT, workspace_id TEXT NOT NULL DEFAULT 'global', candidate_id TEXT, status TEXT NOT NULL DEFAULT 'active',
                UNIQUE (src_id, tag, dst_id)
            );
CREATE VIRTUAL TABLE graph_cues_fts USING fts5(
                cue, node_id UNINDEXED
            );
CREATE TABLE code_files (
                    codebase TEXT NOT NULL,
                    rel_path TEXT NOT NULL,
                    blake3 TEXT NOT NULL,
                    mtime_ns INTEGER NOT NULL,
                    size INTEGER NOT NULL,
                    symbol_count INTEGER NOT NULL DEFAULT 0,
                    indexed_at TEXT NOT NULL,
                    PRIMARY KEY (codebase, rel_path)
                );
CREATE TABLE candidates (
                    id TEXT PRIMARY KEY,
                    content TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    confidence_score REAL NOT NULL,
                    importance_score REAL NOT NULL,
                    owner TEXT NOT NULL,
                    workspace_id TEXT NOT NULL,
                    workspace_path TEXT,
                    session_id TEXT NOT NULL DEFAULT '',
                    turn_id TEXT NOT NULL,
                    raw_evidence_ids TEXT NOT NULL DEFAULT '[]',
                    evidence_role TEXT NOT NULL,
                    source TEXT NOT NULL,
                    source_event_id TEXT NOT NULL,
                    dedup_key TEXT NOT NULL UNIQUE,
                    status TEXT NOT NULL,
                    reason TEXT NOT NULL,
                    accepted_curated_id TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                , source_uri TEXT NOT NULL DEFAULT '', source_revision INTEGER NOT NULL DEFAULT 1, content_hash TEXT NOT NULL DEFAULT '', source_message_ids TEXT NOT NULL DEFAULT '[]');
CREATE TABLE memory_quarantine (
                    id TEXT PRIMARY KEY,
                    tier TEXT NOT NULL,
                    original_id TEXT NOT NULL,
                    content TEXT NOT NULL,
                    payload TEXT NOT NULL,
                    owner TEXT,
                    workspace_id TEXT NOT NULL DEFAULT 'global',
                    reason TEXT NOT NULL,
                    quarantined_at TEXT NOT NULL,
                    UNIQUE(tier, original_id)
                );
CREATE TABLE memory_metrics (
                    name TEXT PRIMARY KEY,
                    value INTEGER NOT NULL DEFAULT 0
                );
CREATE TABLE fm_meta (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                 );
CREATE TABLE memory_leases (
                        kind TEXT NOT NULL,
                        owner TEXT NOT NULL,
                        workspace_id TEXT NOT NULL,
                        subject TEXT NOT NULL,
                        holder TEXT NOT NULL,
                        acquired_at TEXT NOT NULL,
                        expires_at TEXT NOT NULL,
                        attempt INTEGER NOT NULL DEFAULT 1,
                        PRIMARY KEY(kind, owner, workspace_id, subject)
                    );
CREATE TABLE memory_tombstones (
                        id TEXT PRIMARY KEY,
                        owner TEXT NOT NULL,
                        workspace_id TEXT NOT NULL,
                        source_key TEXT NOT NULL,
                        affected_ids TEXT NOT NULL,
                        recovery_payload TEXT,
                        created_at TEXT NOT NULL,
                        recover_until TEXT,
                        recovered_at TEXT
                    , operation_id TEXT, operation_key TEXT);
CREATE TABLE memory_retention_policy (
                        owner TEXT NOT NULL,
                        workspace_id TEXT NOT NULL,
                        raw_days INTEGER NOT NULL,
                        candidate_days INTEGER NOT NULL,
                        curated_days INTEGER,
                        graph_days INTEGER,
                        recovery_seconds INTEGER NOT NULL DEFAULT 0,
                        updated_at TEXT NOT NULL,
                        PRIMARY KEY(owner, workspace_id)
                    );
CREATE TABLE memory_retention_operations (
                        owner TEXT NOT NULL,
                        workspace_id TEXT NOT NULL,
                        operation_id TEXT NOT NULL,
                        request_key TEXT NOT NULL,
                        closure TEXT NOT NULL,
                        committed_at TEXT NOT NULL,
                        PRIMARY KEY(owner, workspace_id, operation_id)
                    );
CREATE TABLE fm_v2_predicates (
            predicate TEXT PRIMARY KEY,
            value_type TEXT NOT NULL,
            cardinality TEXT NOT NULL,
            version INTEGER NOT NULL DEFAULT 1,
            allow_unknown INTEGER NOT NULL DEFAULT 0 CHECK (allow_unknown IN (0,1))
        );
CREATE TABLE fm_v2_change_sets (
            owner_id TEXT NOT NULL,
            change_set_id TEXT NOT NULL,
            actor_type TEXT NOT NULL,
            actor_id TEXT NOT NULL,
            reason TEXT NOT NULL,
            source_event_id TEXT,
            contract_version TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, change_set_id)
        );
CREATE TABLE fm_v2_entities (
            owner_id TEXT NOT NULL,
            entity_id TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            created_change_set_id TEXT NOT NULL,
            current_revision INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, entity_id),
            FOREIGN KEY (owner_id, created_change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_entity_revisions (
            owner_id TEXT NOT NULL,
            entity_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            payload TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            actor_type TEXT NOT NULL,
            actor_id TEXT NOT NULL,
            reason TEXT NOT NULL,
            change_set_id TEXT NOT NULL,
            previous_revision INTEGER,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, entity_id, revision),
            FOREIGN KEY (owner_id, entity_id)
                REFERENCES fm_v2_entities(owner_id, entity_id),
            FOREIGN KEY (owner_id, change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (revision > 0)
        );
CREATE TABLE fm_v2_knowledge_blocks (
            owner_id TEXT NOT NULL,
            block_id TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            subject_entity_id TEXT NOT NULL,
            predicate TEXT NOT NULL,
            claim_slot TEXT NOT NULL,
            cardinality TEXT NOT NULL,
            created_change_set_id TEXT NOT NULL,
            current_revision INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, block_id),
            UNIQUE (owner_id, workspace_key, project_key, subject_entity_id, predicate, claim_slot),
            FOREIGN KEY (owner_id, subject_entity_id)
                REFERENCES fm_v2_entities(owner_id, entity_id),
            FOREIGN KEY (owner_id, created_change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_knowledge_revisions (
            owner_id TEXT NOT NULL,
            block_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            value_type TEXT NOT NULL,
            value_json TEXT NOT NULL,
            expected_value_type TEXT,
            kind TEXT NOT NULL,
            tags_json TEXT NOT NULL DEFAULT '[]',
            status TEXT NOT NULL,
            confidence REAL NOT NULL,
            trust REAL NOT NULL,
            activation TEXT NOT NULL,
            activation_rationale TEXT NOT NULL DEFAULT '',
            valid_from TEXT,
            valid_to TEXT,
            evidence_json TEXT NOT NULL DEFAULT '[]',
            content_hash TEXT NOT NULL,
            actor_type TEXT NOT NULL,
            actor_id TEXT NOT NULL,
            reason TEXT NOT NULL,
            source_event_id TEXT,
            change_set_id TEXT NOT NULL,
            previous_revision INTEGER,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, block_id, revision),
            FOREIGN KEY (owner_id, block_id)
                REFERENCES fm_v2_knowledge_blocks(owner_id, block_id),
            FOREIGN KEY (owner_id, change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (revision > 0),
            CHECK (confidence >= 0 AND confidence <= 1),
            CHECK (trust >= 0 AND trust <= 1),
            CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from)
        );
CREATE TABLE fm_v2_conflicts (
            owner_id TEXT NOT NULL,
            conflict_id TEXT NOT NULL,
            block_id TEXT NOT NULL,
            current_revision INTEGER NOT NULL,
            competing_payload TEXT NOT NULL,
            state TEXT NOT NULL DEFAULT 'open',
            rationale TEXT NOT NULL DEFAULT '',
            created_change_set_id TEXT NOT NULL,
            resolved_change_set_id TEXT,
            created_at TEXT NOT NULL,
            resolved_at TEXT,
            PRIMARY KEY (owner_id, conflict_id),
            FOREIGN KEY (owner_id, block_id)
                REFERENCES fm_v2_knowledge_blocks(owner_id, block_id),
            FOREIGN KEY (owner_id, created_change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            FOREIGN KEY (owner_id, resolved_change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (state IN ('open','resolved','dismissed'))
        );
CREATE TABLE fm_v2_sources (
            owner_id TEXT NOT NULL,
            source_id TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            source_uri TEXT NOT NULL,
            source_revision INTEGER NOT NULL,
            content_hash TEXT NOT NULL,
            source_type TEXT NOT NULL,
            forget_state TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, source_id, source_revision),
            CHECK (source_revision > 0),
            CHECK (project_key = '' OR workspace_key <> ''),
            CHECK (forget_state IN ('active','forget_requested','forgotten'))
        );
CREATE TABLE fm_v2_evidence (
            owner_id TEXT NOT NULL,
            evidence_id TEXT NOT NULL,
            source_id TEXT NOT NULL,
            source_revision INTEGER NOT NULL,
            locator_type TEXT NOT NULL,
            locator_json TEXT NOT NULL,
            quote TEXT,
            extraction_contract TEXT NOT NULL,
            parser_version TEXT NOT NULL,
            raw_value_json TEXT NOT NULL,
            normalized_value_json TEXT NOT NULL,
            validation_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, evidence_id),
            FOREIGN KEY (owner_id, source_id, source_revision)
                REFERENCES fm_v2_sources(owner_id, source_id, source_revision)
        );
CREATE TABLE fm_v2_documents (
            owner_id TEXT NOT NULL,
            document_id TEXT NOT NULL,
            source_id TEXT NOT NULL,
            source_revision INTEGER NOT NULL,
            title TEXT NOT NULL DEFAULT '',
            parser_version TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, document_id),
            FOREIGN KEY (owner_id, source_id, source_revision)
                REFERENCES fm_v2_sources(owner_id, source_id, source_revision)
        );
CREATE TABLE fm_v2_chunks (
            owner_id TEXT NOT NULL,
            chunk_id TEXT NOT NULL,
            document_id TEXT NOT NULL,
            ordinal INTEGER NOT NULL,
            text TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            locator_json TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, chunk_id),
            UNIQUE (owner_id, document_id, ordinal),
            FOREIGN KEY (owner_id, document_id)
                REFERENCES fm_v2_documents(owner_id, document_id)
        );
CREATE TABLE fm_v2_jobs (
            owner_id TEXT NOT NULL,
            job_id TEXT NOT NULL,
            kind TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            idempotency_key TEXT NOT NULL,
            state TEXT NOT NULL,
            current_attempt_id TEXT,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            input_hash TEXT NOT NULL,
            result_json TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, job_id),
            UNIQUE (owner_id, idempotency_key),
            CHECK (state IN ('queued','active','awaiting_review','retry_wait','succeeded','failed_terminal','cancelled')),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_attempts (
            owner_id TEXT NOT NULL,
            attempt_id TEXT NOT NULL,
            job_id TEXT NOT NULL,
            attempt_number INTEGER NOT NULL,
            state TEXT NOT NULL,
            lease_epoch INTEGER NOT NULL,
            lease_owner TEXT,
            lease_expires_at TEXT,
            heartbeat_at TEXT,
            progress_watermark TEXT,
            error_json TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, attempt_id),
            UNIQUE (owner_id, job_id, attempt_number),
            FOREIGN KEY (owner_id, job_id)
                REFERENCES fm_v2_jobs(owner_id, job_id),
            CHECK (state IN ('leased','running','succeeded','failed_retryable','failed_terminal','cancelled','fenced')),
            CHECK (attempt_number > 0)
        );
CREATE TABLE fm_v2_projects (
            owner_id TEXT NOT NULL,
            project_id TEXT NOT NULL,
            workspace_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL, current_root TEXT NOT NULL DEFAULT '', current_locator_revision INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (owner_id, project_id)
        );
CREATE TABLE fm_v2_project_locators (
            owner_id TEXT NOT NULL,
            project_id TEXT NOT NULL,
            locator_revision INTEGER NOT NULL,
            canonical_root TEXT NOT NULL,
            root_identity TEXT NOT NULL,
            git_identity TEXT NOT NULL,
            worktree_identity TEXT NOT NULL,
            active INTEGER NOT NULL DEFAULT 1,
            authorized_at TEXT NOT NULL, git_repository TEXT NOT NULL DEFAULT '', worktree TEXT NOT NULL DEFAULT '', branch TEXT NOT NULL DEFAULT '', locator_hash TEXT NOT NULL DEFAULT '',
            PRIMARY KEY (owner_id, project_id, locator_revision),
            FOREIGN KEY (owner_id, project_id)
                REFERENCES fm_v2_projects(owner_id, project_id),
            CHECK (locator_revision > 0),
            CHECK (active IN (0,1))
        );
CREATE TABLE fm_v2_policy_projections (
            owner_id TEXT NOT NULL,
            project_id TEXT NOT NULL,
            contract_path TEXT NOT NULL,
            contract_hash TEXT NOT NULL,
            engine_version TEXT NOT NULL,
            summary_json TEXT NOT NULL,
            source_revision INTEGER NOT NULL,
            state TEXT NOT NULL DEFAULT 'never_activated',
            updated_at TEXT NOT NULL,
            workspace_id TEXT NOT NULL DEFAULT 'global',
            canonical_root TEXT NOT NULL DEFAULT '',
            root_identity TEXT NOT NULL DEFAULT '',
            git_identity TEXT NOT NULL DEFAULT '',
            worktree_identity TEXT NOT NULL DEFAULT '',
            activation_revision INTEGER NOT NULL DEFAULT 0,
            activated_by TEXT,
            activated_at TEXT,
            PRIMARY KEY (owner_id, project_id),
            CHECK (state IN ('never_activated','active','drifted','deactivated'))
        );
CREATE TABLE fm_v2_spells (
            owner_id TEXT NOT NULL,
            spell_id TEXT NOT NULL,
            project_id TEXT,
            title TEXT NOT NULL,
            suggestion_json TEXT NOT NULL,
            source_evidence_json TEXT NOT NULL DEFAULT '[]',
            status TEXT NOT NULL DEFAULT 'proposed',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            workspace_id TEXT NOT NULL DEFAULT 'global',
            path_scope TEXT NOT NULL DEFAULT '**/*',
            revision INTEGER NOT NULL DEFAULT 1,
            review_state TEXT NOT NULL DEFAULT 'proposed',
            lifecycle TEXT NOT NULL DEFAULT 'proposed',
            reviewed_by TEXT,
            reviewed_at TEXT,
            expires_at TEXT,
            rationale TEXT NOT NULL DEFAULT '',
            confidence REAL NOT NULL DEFAULT 0.5,
            promoted_contract_hash TEXT,
            promoted_transition_id TEXT,
            PRIMARY KEY (owner_id, spell_id),
            CHECK (status IN ('proposed','dismissed','expired','edited','promoted'))
        );
CREATE TABLE fm_v2_policy_transitions (
            owner_id TEXT NOT NULL,
            transition_id TEXT NOT NULL,
            project_id TEXT NOT NULL,
            phase TEXT NOT NULL,
            contract_hash TEXT NOT NULL,
            actor_id TEXT NOT NULL,
            payload_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            contract_path TEXT,
            old_contract_hash TEXT,
            new_contract_hash TEXT,
            old_bytes BLOB,
            new_bytes BLOB,
            spell_id TEXT,
            spell_revision INTEGER,
            payload_json TEXT NOT NULL DEFAULT '{}',
            updated_at TEXT, operation_id TEXT, sequence INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'pending', previous_transition_id TEXT, previous_event_hash TEXT, event_hash TEXT, old_bytes_ref TEXT, new_bytes_ref TEXT, error_json TEXT,
            PRIMARY KEY (owner_id, transition_id),
            CHECK (phase IN ('prepared','blessing_consumed','file_published','activation_advanced','validated','projection_enqueued','spell_linked','committed','rollback_required','rolled_back'))
        );
CREATE TABLE fm_v2_outbox (
            owner_id TEXT NOT NULL,
            event_id TEXT NOT NULL,
            change_set_id TEXT NOT NULL,
            kind TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            source_revision INTEGER NOT NULL,
            state TEXT NOT NULL DEFAULT 'pending',
            created_at TEXT NOT NULL,
            published_at TEXT,
            PRIMARY KEY (owner_id, event_id),
            FOREIGN KEY (owner_id, change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (state IN ('pending','leased','published','failed'))
        );
CREATE TABLE fm_v2_migration_runs (
            migration_run_id TEXT PRIMARY KEY,
            source_database_id TEXT NOT NULL,
            source_schema_version INTEGER NOT NULL,
            source_high_water_mark TEXT NOT NULL,
            conversion_version TEXT NOT NULL,
            manifest_hash TEXT NOT NULL,
            outbox_high_water_mark INTEGER NOT NULL DEFAULT 0,
            backup_path TEXT,
            backup_hash TEXT,
            state TEXT NOT NULL DEFAULT 'planned',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            CHECK (state IN ('planned','applying','paused','applied','failed','rolled_back'))
        );
CREATE TABLE fm_v2_migration_plan (
            migration_run_id TEXT NOT NULL,
            plan_id INTEGER PRIMARY KEY AUTOINCREMENT,
            source_table TEXT NOT NULL,
            source_key TEXT NOT NULL,
            owner_id TEXT,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            source_fingerprint TEXT NOT NULL,
            planned_target_ids TEXT NOT NULL,
            conversion_rule TEXT NOT NULL,
            classification TEXT NOT NULL,
            activation_treatment TEXT NOT NULL,
            exception_id TEXT,
            created_at TEXT NOT NULL,
            UNIQUE (migration_run_id, source_table, source_key),
            FOREIGN KEY (migration_run_id) REFERENCES fm_v2_migration_runs(migration_run_id),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_migration_events (
            migration_run_id TEXT NOT NULL,
            event_id TEXT PRIMARY KEY,
            plan_id INTEGER NOT NULL,
            sequence INTEGER NOT NULL,
            phase TEXT NOT NULL,
            attempt INTEGER NOT NULL,
            checkpoint TEXT NOT NULL,
            target_ids TEXT NOT NULL,
            apply_result TEXT NOT NULL,
            validation_result TEXT NOT NULL,
            exception_id TEXT,
            rollback_marker TEXT,
            actor TEXT NOT NULL,
            previous_event_hash TEXT,
            event_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE (migration_run_id, sequence),
            FOREIGN KEY (migration_run_id) REFERENCES fm_v2_migration_runs(migration_run_id),
            FOREIGN KEY (plan_id) REFERENCES fm_v2_migration_plan(plan_id)
        );
CREATE TABLE fm_v2_trust_assignments (
            owner_id TEXT NOT NULL,
            assignment_id TEXT NOT NULL,
            subject_kind TEXT NOT NULL,
            subject_id TEXT NOT NULL,
            subject_revision INTEGER NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            assignment_revision INTEGER NOT NULL,
            state TEXT NOT NULL,
            trust REAL,
            actor_type TEXT NOT NULL,
            actor_id TEXT NOT NULL,
            reason_code TEXT NOT NULL,
            rationale TEXT NOT NULL DEFAULT '',
            evidence_json TEXT NOT NULL DEFAULT '[]',
            supersedes_assignment_id TEXT,
            content_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY(owner_id, assignment_id),
            UNIQUE(owner_id, subject_kind, subject_id, subject_revision, assignment_revision),
            CHECK(subject_kind IN ('knowledge_revision','candidate_revision','source_revision','document_revision','code_claim_revision','derived_artifact_revision')),
            CHECK(subject_revision > 0),
            CHECK(project_key = '' OR workspace_key <> ''),
            CHECK(state IN ('unreviewed','assigned','revoked')),
            CHECK((state = 'assigned' AND trust IS NOT NULL AND trust >= 0 AND trust <= 1) OR (state <> 'assigned' AND trust IS NULL)),
            CHECK(actor_type = 'owner'),
            CHECK(reason_code IN ('owner_review','owner_pin','owner_correction','owner_retraction','import_review','migration_review'))
        );
CREATE TABLE fm_v2_job_manifests (
            owner_id TEXT NOT NULL,
            manifest_id TEXT NOT NULL,
            job_id TEXT NOT NULL,
            phase TEXT NOT NULL,
            selected_json TEXT NOT NULL,
            completed_json TEXT NOT NULL DEFAULT '[]',
            reused_json TEXT NOT NULL DEFAULT '[]',
            failed_json TEXT NOT NULL DEFAULT '[]',
            waived_json TEXT NOT NULL DEFAULT '[]',
            config_hash TEXT NOT NULL,
            model_hash TEXT NOT NULL,
            tool_hash TEXT NOT NULL,
            input_hash TEXT NOT NULL,
            parent_manifest_id TEXT,
            content_hash TEXT NOT NULL,
            sealed_at TEXT NOT NULL,
            PRIMARY KEY(owner_id, manifest_id),
            UNIQUE(owner_id, job_id, phase),
            CHECK(phase IN ('selection','outcome'))
        );
CREATE TABLE fm_v2_entity_aliases (
            owner_id TEXT NOT NULL,
            entity_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            alias TEXT NOT NULL,
            PRIMARY KEY (owner_id, entity_id, revision, alias),
            FOREIGN KEY (owner_id, entity_id, revision)
                REFERENCES fm_v2_entity_revisions(owner_id, entity_id, revision),
            CHECK (trim(alias) <> '')
        );
CREATE TABLE fm_v2_entity_roles (
            owner_id TEXT NOT NULL,
            entity_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            role TEXT NOT NULL,
            is_current INTEGER NOT NULL DEFAULT 1,
            PRIMARY KEY (owner_id, entity_id, revision, role),
            FOREIGN KEY (owner_id, entity_id, revision)
                REFERENCES fm_v2_entity_revisions(owner_id, entity_id, revision),
            CHECK (project_key = '' OR workspace_key <> ''),
            CHECK (trim(role) <> ''),
            CHECK (is_current IN (0,1))
        );
CREATE TABLE fm_v2_entity_tags (
            owner_id TEXT NOT NULL,
            entity_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            tag TEXT NOT NULL,
            PRIMARY KEY (owner_id, entity_id, revision, tag),
            FOREIGN KEY (owner_id, entity_id, revision)
                REFERENCES fm_v2_entity_revisions(owner_id, entity_id, revision),
            CHECK (trim(tag) <> '')
        );
CREATE TABLE fm_v2_revision_evidence (
            owner_id TEXT NOT NULL,
            block_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            evidence_id TEXT NOT NULL,
            PRIMARY KEY (owner_id, block_id, revision, evidence_id),
            FOREIGN KEY (owner_id, block_id, revision)
                REFERENCES fm_v2_knowledge_revisions(owner_id, block_id, revision),
            FOREIGN KEY (owner_id, evidence_id)
                REFERENCES fm_v2_evidence(owner_id, evidence_id)
        );
CREATE TABLE fm_v2_candidates (
            owner_id TEXT NOT NULL,
            candidate_id TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            idempotency_key TEXT NOT NULL,
            created_change_set_id TEXT NOT NULL,
            current_revision INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, candidate_id),
            UNIQUE (owner_id, workspace_key, project_key, idempotency_key),
            FOREIGN KEY (owner_id, created_change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_candidate_revisions (
            owner_id TEXT NOT NULL,
            candidate_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            proposal_json TEXT NOT NULL,
            state TEXT NOT NULL,
            confidence REAL NOT NULL,
            importance REAL NOT NULL,
            reason TEXT NOT NULL,
            source_id TEXT,
            source_revision INTEGER,
            accepted_block_id TEXT,
            content_hash TEXT NOT NULL,
            actor_type TEXT NOT NULL,
            actor_id TEXT NOT NULL,
            source_event_id TEXT,
            change_set_id TEXT NOT NULL,
            previous_revision INTEGER,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, candidate_id, revision),
            FOREIGN KEY (owner_id, candidate_id)
                REFERENCES fm_v2_candidates(owner_id, candidate_id),
            FOREIGN KEY (owner_id, change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            FOREIGN KEY (owner_id, source_id, source_revision)
                REFERENCES fm_v2_sources(owner_id, source_id, source_revision),
            FOREIGN KEY (owner_id, accepted_block_id)
                REFERENCES fm_v2_knowledge_blocks(owner_id, block_id),
            CHECK (revision > 0),
            CHECK (confidence >= 0 AND confidence <= 1),
            CHECK (importance >= 0 AND importance <= 1),
            CHECK ((source_id IS NULL) = (source_revision IS NULL)),
            CHECK (state IN (
                'proposed','validating','awaiting_review','eligible_auto',
                'duplicate','corroborating','conflicted','quarantined',
                'rejected','cancelled','activated'
            ))
        );
CREATE TABLE fm_v2_candidate_evidence (
            owner_id TEXT NOT NULL,
            candidate_id TEXT NOT NULL,
            revision INTEGER NOT NULL,
            evidence_id TEXT NOT NULL,
            PRIMARY KEY (owner_id, candidate_id, revision, evidence_id),
            FOREIGN KEY (owner_id, candidate_id, revision)
                REFERENCES fm_v2_candidate_revisions(owner_id, candidate_id, revision),
            FOREIGN KEY (owner_id, evidence_id)
                REFERENCES fm_v2_evidence(owner_id, evidence_id)
        );
CREATE TABLE fm_v2_conflict_events (
            owner_id TEXT NOT NULL,
            conflict_id TEXT NOT NULL,
            sequence INTEGER NOT NULL,
            state TEXT NOT NULL,
            rationale TEXT NOT NULL DEFAULT '',
            change_set_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, conflict_id, sequence),
            FOREIGN KEY (owner_id, conflict_id)
                REFERENCES fm_v2_conflicts(owner_id, conflict_id),
            FOREIGN KEY (owner_id, change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (state IN ('open','resolved','dismissed'))
        );
CREATE TABLE fm_v2_job_events (
            owner_id TEXT NOT NULL,
            job_id TEXT NOT NULL,
            sequence INTEGER NOT NULL,
            state TEXT NOT NULL,
            attempt_id TEXT,
            lease_epoch INTEGER,
            result_json TEXT,
            error_json TEXT,
            change_set_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, job_id, sequence),
            FOREIGN KEY (owner_id, job_id)
                REFERENCES fm_v2_jobs(owner_id, job_id),
            FOREIGN KEY (owner_id, change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (state IN (
                'queued','active','awaiting_review','retry_wait',
                'succeeded','failed_terminal','cancelled'
            ))
        );
CREATE TABLE fm_v2_privacy_erasure_context (
            owner_id TEXT PRIMARY KEY,
            erasure_id TEXT NOT NULL UNIQUE,
            source_id TEXT,
            authorized_by TEXT NOT NULL,
            reason TEXT NOT NULL,
            created_at TEXT NOT NULL
        );
CREATE TABLE fm_v2_privacy_erasure_tombstones (
            owner_id TEXT NOT NULL,
            erasure_id TEXT NOT NULL,
            source_id TEXT,
            authorized_by TEXT NOT NULL,
            reason TEXT NOT NULL,
            erased_counts_json TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, erasure_id)
        );
CREATE TABLE fm_v2_episodes (
            owner_id TEXT NOT NULL,
            episode_id TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            source_id TEXT NOT NULL,
            source_revision INTEGER NOT NULL,
            payload_json TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            created_change_set_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, episode_id),
            FOREIGN KEY (owner_id, source_id, source_revision)
                REFERENCES fm_v2_sources(owner_id, source_id, source_revision),
            FOREIGN KEY (owner_id, created_change_set_id)
                REFERENCES fm_v2_change_sets(owner_id, change_set_id),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_derived_generations (
            owner_id TEXT NOT NULL,
            generation_id TEXT NOT NULL,
            logical_space TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            provider_ref TEXT NOT NULL,
            model TEXT NOT NULL,
            endpoint_class TEXT NOT NULL,
            dimension INTEGER NOT NULL,
            normalization TEXT NOT NULL,
            metric TEXT NOT NULL,
            chunker_version TEXT NOT NULL,
            config_fingerprint TEXT NOT NULL,
            source_watermark TEXT NOT NULL,
            row_count INTEGER NOT NULL DEFAULT 0,
            state TEXT NOT NULL,
            retention_state TEXT NOT NULL DEFAULT 'retained',
            failure_json TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            validated_at TEXT,
            PRIMARY KEY(owner_id, generation_id),
            CHECK (project_key = '' OR workspace_key <> ''),
            CHECK (dimension >= 0),
            CHECK (state IN ('planned','building','validating','ready','failed')),
            CHECK (retention_state IN ('retained','gc_eligible','deleted'))
        );
CREATE TABLE fm_v2_index_pointers (
            owner_id TEXT NOT NULL,
            logical_space TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            generation_id TEXT NOT NULL,
            publication_tx TEXT NOT NULL DEFAULT '',
            publication_watermark TEXT NOT NULL,
            published_at TEXT NOT NULL,
            PRIMARY KEY(owner_id, logical_space, workspace_key, project_key),
            FOREIGN KEY(owner_id, generation_id)
                REFERENCES fm_v2_derived_generations(owner_id, generation_id),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_chunk_embeddings (
            owner_id TEXT NOT NULL,
            generation_id TEXT NOT NULL,
            chunk_id TEXT NOT NULL,
            dimension INTEGER NOT NULL,
            embedding BLOB NOT NULL,
            content_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY(owner_id, generation_id, chunk_id),
            FOREIGN KEY(owner_id, generation_id)
                REFERENCES fm_v2_derived_generations(owner_id, generation_id),
            FOREIGN KEY(owner_id, chunk_id)
                REFERENCES fm_v2_chunks(owner_id, chunk_id) ON DELETE CASCADE,
            CHECK (dimension > 0)
        );
CREATE TABLE fm_v2_index_publications (
            owner_id TEXT NOT NULL,
            publication_id TEXT NOT NULL,
            logical_space TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            previous_generation_id TEXT,
            generation_id TEXT NOT NULL,
            action TEXT NOT NULL,
            publication_watermark TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY(owner_id, publication_id),
            CHECK (project_key = '' OR workspace_key <> ''),
            CHECK (action IN ('publish','rollback'))
        );
CREATE TABLE fm_v2_legacy_outbox (
            sequence INTEGER PRIMARY KEY AUTOINCREMENT,
            event_id TEXT NOT NULL UNIQUE,
            source_table TEXT NOT NULL,
            source_key TEXT NOT NULL,
            operation TEXT NOT NULL,
            owner_id TEXT,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            source_revision TEXT NOT NULL,
            pre_fingerprint TEXT,
            post_fingerprint TEXT,
            idempotency_key TEXT NOT NULL UNIQUE,
            payload_version TEXT NOT NULL,
            payload_json TEXT,
            state TEXT NOT NULL DEFAULT 'pending',
            created_at TEXT NOT NULL,
            applied_at TEXT,
            CHECK (operation IN ('insert','update','delete','retract','forget')),
            CHECK (state IN ('pending','applied','superseded','erased','quarantined')),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_migration_outbox_events (
            migration_run_id TEXT NOT NULL,
            outbox_sequence INTEGER NOT NULL,
            disposition TEXT NOT NULL,
            target_ids TEXT NOT NULL DEFAULT '[]',
            event_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (migration_run_id, outbox_sequence),
            FOREIGN KEY (migration_run_id)
                REFERENCES fm_v2_migration_runs(migration_run_id),
            FOREIGN KEY (outbox_sequence)
                REFERENCES fm_v2_legacy_outbox(sequence),
            CHECK (disposition IN ('applied','superseded','erased','quarantined'))
        );
CREATE TABLE fm_v2_migration_review (
            migration_run_id TEXT NOT NULL,
            review_id TEXT NOT NULL,
            plan_id INTEGER NOT NULL,
            owner_id TEXT NOT NULL,
            workspace_key TEXT NOT NULL DEFAULT '',
            project_key TEXT NOT NULL DEFAULT '',
            state TEXT NOT NULL DEFAULT 'awaiting_review',
            candidate_revision INTEGER NOT NULL DEFAULT 1,
            proposal_json TEXT NOT NULL,
            reason TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (migration_run_id, review_id),
            FOREIGN KEY (migration_run_id)
                REFERENCES fm_v2_migration_runs(migration_run_id),
            FOREIGN KEY (plan_id)
                REFERENCES fm_v2_migration_plan(plan_id),
            CHECK (state IN ('awaiting_review','edited','rejected','cancelled')),
            CHECK (project_key = '' OR workspace_key <> '')
        );
CREATE TABLE fm_v2_policy_trust (
            owner_id TEXT NOT NULL,
            project_id TEXT NOT NULL,
            trust_id TEXT NOT NULL DEFAULT '',
            revision INTEGER NOT NULL DEFAULT 1,
            canonical_root TEXT NOT NULL,
            worktree_identity TEXT NOT NULL,
            branch TEXT NOT NULL,
            contract_hash TEXT NOT NULL,
            engine_version TEXT NOT NULL,
            manifest_hash TEXT NOT NULL,
            capability_hash TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            revoked_at TEXT,
            created_by TEXT NOT NULL DEFAULT '',
            created_reason TEXT NOT NULL DEFAULT '',
            revoked_by TEXT,
            revoked_reason TEXT,
            created_at TEXT NOT NULL,
            PRIMARY KEY (
                owner_id, project_id, canonical_root, worktree_identity, branch,
                contract_hash, engine_version, manifest_hash, capability_hash
            ),
            FOREIGN KEY (owner_id, project_id)
                REFERENCES fm_v2_projects(owner_id, project_id)
        );
CREATE TABLE fm_v2_policy_profiles (
            owner_id TEXT NOT NULL,
            project_id TEXT NOT NULL,
            profile_id TEXT NOT NULL,
            os_uid INTEGER NOT NULL,
            credential_hash TEXT NOT NULL DEFAULT '',
            activation_revision INTEGER NOT NULL DEFAULT 0,
            allowed_actions_json TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            revoked_at TEXT,
            created_by TEXT NOT NULL DEFAULT '',
            created_reason TEXT NOT NULL DEFAULT '',
            revoked_by TEXT,
            revoked_reason TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (owner_id, project_id, profile_id),
            FOREIGN KEY (owner_id, project_id)
                REFERENCES fm_v2_projects(owner_id, project_id),
            CHECK (os_uid >= 0)
        );
CREATE TABLE code_index_runs (
                        owner TEXT NOT NULL,
                        workspace_id TEXT NOT NULL,
                        codebase TEXT NOT NULL,
                        run_id TEXT NOT NULL,
                        source_snapshot TEXT NOT NULL,
                        status TEXT NOT NULL,
                        files_indexed INTEGER NOT NULL DEFAULT 0,
                        files_unchanged INTEGER NOT NULL DEFAULT 0,
                        files_removed INTEGER NOT NULL DEFAULT 0,
                        symbols INTEGER NOT NULL DEFAULT 0,
                        errors TEXT NOT NULL DEFAULT '[]',
                        coverage TEXT NOT NULL DEFAULT '[]',
                        started_at TEXT NOT NULL,
                        finished_at TEXT,
                        PRIMARY KEY (owner, workspace_id, codebase, run_id)
                    );
CREATE TABLE code_index_heads (
                        owner TEXT NOT NULL,
                        workspace_id TEXT NOT NULL,
                        codebase TEXT NOT NULL,
                        run_id TEXT NOT NULL,
                        published_at TEXT NOT NULL,
                        PRIMARY KEY (owner, workspace_id, codebase)
                    );
CREATE VIRTUAL TABLE curated_fts USING fts5(
                content, scene_name, tags, workspace_id,
                content='curated', content_rowid='rowid'
            );
CREATE VIRTUAL TABLE raw_fts USING fts5(
                content, workspace_id,
                content='raw', content_rowid='rowid'
            );
CREATE VIRTUAL TABLE facts_fts USING fts5(
                content, entities,
                content='facts', content_rowid='rowid'
            );
CREATE INDEX idx_graph_nodes_norm ON graph_nodes(norm_name);
CREATE INDEX idx_graph_edges_src ON graph_edges(src_id);
CREATE INDEX idx_graph_edges_dst ON graph_edges(dst_id);
CREATE INDEX idx_candidates_scope_status
                    ON candidates(owner, workspace_id, status, updated_at);
CREATE INDEX idx_memory_quarantine_scope
                    ON memory_quarantine(owner, workspace_id, quarantined_at);
CREATE INDEX idx_graph_nodes_scope
                    ON graph_nodes(owner,workspace_id,status);
CREATE INDEX idx_graph_edges_scope
                    ON graph_edges(owner,workspace_id,status);
CREATE INDEX idx_graph_cues_scope
                    ON graph_cues(owner,workspace_id,status);
CREATE INDEX idx_facts_scope
                    ON facts(owner,workspace_id,status);
CREATE INDEX idx_memory_leases_expiry
                        ON memory_leases(expires_at);
CREATE INDEX idx_memory_tombstones_scope
                        ON memory_tombstones(owner, workspace_id, created_at);
CREATE INDEX idx_memory_tombstones_expiry
                        ON memory_tombstones(recover_until, recovered_at);
CREATE UNIQUE INDEX idx_memory_tombstones_operation
                        ON memory_tombstones(owner, workspace_id, operation_id)
                        WHERE operation_id IS NOT NULL;
CREATE UNIQUE INDEX idx_fm_v2_project_active_root
            ON fm_v2_project_locators(owner_id, canonical_root)
            WHERE active=1;
CREATE UNIQUE INDEX idx_fm_v2_project_active_locator
            ON fm_v2_project_locators(owner_id, project_id)
            WHERE active=1;
CREATE INDEX idx_fm_v2_blocks_scope
            ON fm_v2_knowledge_blocks(owner_id, workspace_key, project_key, subject_entity_id);
CREATE INDEX idx_fm_v2_revisions_current
            ON fm_v2_knowledge_revisions(owner_id, block_id, revision);
CREATE INDEX idx_fm_v2_sources_hash
            ON fm_v2_sources(owner_id, content_hash);
CREATE INDEX idx_fm_v2_jobs_state
            ON fm_v2_jobs(owner_id, state, updated_at);
CREATE INDEX idx_fm_v2_outbox_state
            ON fm_v2_outbox(owner_id, state, created_at);
CREATE INDEX idx_fm_v2_migration_plan_run
            ON fm_v2_migration_plan(migration_run_id, plan_id);
CREATE INDEX idx_fm_v2_migration_events_run
            ON fm_v2_migration_events(migration_run_id, sequence);
CREATE INDEX idx_fm_v2_trust_latest
            ON fm_v2_trust_assignments(owner_id, subject_kind, subject_id, subject_revision, assignment_revision DESC);
CREATE UNIQUE INDEX idx_fm_v2_current_self_scope
            ON fm_v2_entity_roles(owner_id, workspace_key, project_key)
            WHERE role='self' AND is_current=1;
CREATE INDEX idx_fm_v2_derived_generations_space
            ON fm_v2_derived_generations(
                owner_id,logical_space,workspace_key,project_key,created_at
            );
CREATE INDEX idx_fm_v2_legacy_outbox_pending
            ON fm_v2_legacy_outbox(state, sequence);
CREATE UNIQUE INDEX idx_fm_v2_policy_transition_sequence
            ON fm_v2_policy_transitions(owner_id, operation_id, sequence)
            WHERE operation_id IS NOT NULL;
CREATE INDEX idx_fm_v2_candidates_scope
            ON fm_v2_candidates(owner_id,workspace_key,project_key,current_revision);
CREATE INDEX idx_fm_v2_candidate_state
            ON fm_v2_candidate_revisions(owner_id,state,created_at);
CREATE INDEX idx_fm_v2_job_events_state
            ON fm_v2_job_events(owner_id,state,created_at);
CREATE INDEX idx_code_index_runs_status
                        ON code_index_runs(owner, workspace_id, codebase, status);
CREATE VIEW fm_v2_current_knowledge AS
            SELECT b.owner_id, b.block_id, b.workspace_key, b.project_key,
                   b.subject_entity_id, b.predicate, b.claim_slot,
                   b.current_revision, r.value_type, r.value_json,
                   r.expected_value_type, r.kind, r.tags_json, r.status,
                   r.confidence, r.trust, r.activation, r.activation_rationale,
                   r.valid_from, r.valid_to, r.evidence_json, r.content_hash,
                   r.created_at AS revision_created_at
              FROM fm_v2_knowledge_blocks b
              JOIN fm_v2_knowledge_revisions r
                ON r.owner_id=b.owner_id AND r.block_id=b.block_id
               AND r.revision=b.current_revision;
CREATE VIEW fm_v2_index_generations_compat AS
            SELECT owner_id,generation_id,logical_space,config_fingerprint,
                   source_watermark,
                   CASE state
                       WHEN 'planned' THEN 'building'
                       WHEN 'building' THEN 'building'
                       WHEN 'validating' THEN 'validated'
                       WHEN 'ready' THEN 'published'
                       ELSE 'failed'
                   END AS state,
                   CASE state WHEN 'failed' THEN 'failed' ELSE 'healthy' END AS health,
                   created_at,
                   CASE state WHEN 'ready' THEN validated_at END AS published_at
              FROM fm_v2_derived_generations;
CREATE VIEW fm_v2_index_heads_compat AS
            SELECT owner_id,logical_space,generation_id,published_at
              FROM fm_v2_index_pointers
             WHERE workspace_key='' AND project_key='';
CREATE TRIGGER fm_v2_generation_state_immutable
        BEFORE UPDATE OF state ON fm_v2_derived_generations
        WHEN NOT (
            old.state = new.state OR
            (old.state = 'planned' AND new.state = 'building') OR
            (old.state = 'building' AND new.state IN ('validating','failed')) OR
            (old.state = 'validating' AND new.state IN ('ready','failed'))
        )
        BEGIN
            SELECT RAISE(ABORT, 'invalid derived generation state transition');
        END;
CREATE TRIGGER fm_v2_active_generation_retained
        BEFORE UPDATE OF retention_state ON fm_v2_derived_generations
        WHEN new.retention_state <> 'retained' AND EXISTS (
            SELECT 1 FROM fm_v2_index_pointers pointer
             WHERE pointer.owner_id=old.owner_id
               AND pointer.generation_id=old.generation_id
        )
        BEGIN
            SELECT RAISE(ABORT, 'active generation must remain retained');
        END;
CREATE TRIGGER fm_v2_block_scope_insert
        BEFORE INSERT ON fm_v2_knowledge_blocks
        WHEN NOT EXISTS (
            SELECT 1 FROM fm_v2_entities entity
             WHERE entity.owner_id=NEW.owner_id
               AND entity.entity_id=NEW.subject_entity_id
               AND entity.workspace_key=NEW.workspace_key
               AND entity.project_key=NEW.project_key
        )
        BEGIN
            SELECT RAISE(ABORT, 'knowledge subject scope mismatch');
        END;
CREATE TRIGGER fm_v2_block_scope_update
        BEFORE UPDATE OF subject_entity_id,workspace_key,project_key ON fm_v2_knowledge_blocks
        WHEN NOT EXISTS (
            SELECT 1 FROM fm_v2_entities entity
             WHERE entity.owner_id=NEW.owner_id
               AND entity.entity_id=NEW.subject_entity_id
               AND entity.workspace_key=NEW.workspace_key
               AND entity.project_key=NEW.project_key
        )
        BEGIN
            SELECT RAISE(ABORT, 'knowledge subject scope mismatch');
        END;
CREATE TRIGGER fm_v2_knowledge_revision_validate
        BEFORE INSERT ON fm_v2_knowledge_revisions
        WHEN NEW.value_type NOT IN ('null','string','number','boolean','time','duration','uri','entity_ref','object','list')
          OR NEW.status NOT IN ('open','active','superseded','retracted')
          OR (NEW.status='open' AND (NEW.value_type<>'null' OR NEW.expected_value_type IS NULL))
          OR (NEW.revision=1 AND NEW.previous_revision IS NOT NULL)
          OR (NEW.revision>1 AND (
                NEW.previous_revision<>NEW.revision-1 OR NOT EXISTS (
                    SELECT 1 FROM fm_v2_knowledge_revisions prior
                     WHERE prior.owner_id=NEW.owner_id
                       AND prior.block_id=NEW.block_id
                       AND prior.revision=NEW.previous_revision
                )
             ))
          OR EXISTS (
                SELECT 1 FROM fm_v2_knowledge_blocks block
                JOIN fm_v2_predicates predicate ON predicate.predicate=block.predicate
                 WHERE block.owner_id=NEW.owner_id
                   AND block.block_id=NEW.block_id
                   AND (predicate.cardinality<>block.cardinality OR
                        predicate.value_type<>CASE WHEN NEW.value_type='null'
                            THEN COALESCE(NEW.expected_value_type,'') ELSE NEW.value_type END)
             )
        BEGIN
            SELECT RAISE(ABORT, 'invalid knowledge revision');
        END;
CREATE TRIGGER fm_v2_entity_revision_validate
        BEFORE INSERT ON fm_v2_entity_revisions
        WHEN (NEW.revision=1 AND NEW.previous_revision IS NOT NULL)
          OR (NEW.revision>1 AND (
                NEW.previous_revision<>NEW.revision-1 OR NOT EXISTS (
                    SELECT 1 FROM fm_v2_entity_revisions prior
                     WHERE prior.owner_id=NEW.owner_id
                       AND prior.entity_id=NEW.entity_id
                       AND prior.revision=NEW.previous_revision
                )
             ))
        BEGIN
            SELECT RAISE(ABORT, 'invalid entity revision');
        END;
CREATE TRIGGER fm_v2_candidate_revision_validate
        BEFORE INSERT ON fm_v2_candidate_revisions
        WHEN (NEW.revision=1 AND (
                NEW.previous_revision IS NOT NULL OR NEW.state<>'proposed'
             ))
          OR (NEW.revision>1 AND (
                NEW.previous_revision<>NEW.revision-1 OR NOT EXISTS (
                    SELECT 1 FROM fm_v2_candidate_revisions prior
                     WHERE prior.owner_id=NEW.owner_id
                       AND prior.candidate_id=NEW.candidate_id
                       AND prior.revision=NEW.previous_revision
                ) OR NOT EXISTS (
                    SELECT 1 FROM fm_v2_candidate_revisions prior
                     WHERE prior.owner_id=NEW.owner_id
                       AND prior.candidate_id=NEW.candidate_id
                       AND prior.revision=NEW.previous_revision
                       AND (
                           (prior.state='proposed' AND NEW.state='validating') OR
                           (prior.state='validating' AND NEW.state IN (
                               'awaiting_review','eligible_auto','duplicate',
                               'corroborating','conflicted','quarantined','rejected'
                           )) OR
                           (prior.state='awaiting_review' AND NEW.state IN (
                               'proposed','activated','rejected','cancelled'
                           )) OR
                           (prior.state='eligible_auto' AND NEW.state IN (
                               'activated','awaiting_review','quarantined'
                           ))
                       )
                )
             ))
          OR (NEW.state='activated' AND NEW.accepted_block_id IS NULL)
        BEGIN
            SELECT RAISE(ABORT, 'invalid candidate revision');
        END;
CREATE TRIGGER fm_v2_knowledge_head_validate
        BEFORE UPDATE OF current_revision ON fm_v2_knowledge_blocks
        WHEN NEW.current_revision>0 AND NOT EXISTS (
            SELECT 1 FROM fm_v2_knowledge_revisions revision
             WHERE revision.owner_id=NEW.owner_id
               AND revision.block_id=NEW.block_id
               AND revision.revision=NEW.current_revision
        )
        BEGIN
            SELECT RAISE(ABORT, 'knowledge head revision missing');
        END;
CREATE TRIGGER fm_v2_entity_head_validate
        BEFORE UPDATE OF current_revision ON fm_v2_entities
        WHEN NEW.current_revision>0 AND NOT EXISTS (
            SELECT 1 FROM fm_v2_entity_revisions revision
             WHERE revision.owner_id=NEW.owner_id
               AND revision.entity_id=NEW.entity_id
               AND revision.revision=NEW.current_revision
        )
        BEGIN
            SELECT RAISE(ABORT, 'entity head revision missing');
        END;
CREATE TRIGGER fm_v2_candidate_head_validate
        BEFORE UPDATE OF current_revision ON fm_v2_candidates
        WHEN NEW.current_revision>0 AND NOT EXISTS (
            SELECT 1 FROM fm_v2_candidate_revisions revision
             WHERE revision.owner_id=NEW.owner_id
               AND revision.candidate_id=NEW.candidate_id
               AND revision.revision=NEW.current_revision
        )
        BEGIN
            SELECT RAISE(ABORT, 'candidate head revision missing');
        END;
CREATE TRIGGER fm_v2_job_state_validate
        BEFORE UPDATE OF state ON fm_v2_jobs
        WHEN NOT (
            OLD.state=NEW.state OR
            (OLD.state='queued' AND NEW.state IN ('active','cancelled')) OR
            (OLD.state='active' AND NEW.state IN (
                'awaiting_review','retry_wait','succeeded','failed_terminal','cancelled'
            )) OR
            (OLD.state='retry_wait' AND NEW.state IN ('queued','cancelled')) OR
            (OLD.state='awaiting_review' AND NEW.state IN ('queued','succeeded','cancelled'))
        )
        BEGIN
            SELECT RAISE(ABORT, 'invalid job state transition');
        END;
CREATE TRIGGER fm_v2_attempt_state_validate
        BEFORE UPDATE OF state ON fm_v2_attempts
        WHEN NOT (
            OLD.state=NEW.state OR
            (OLD.state='leased' AND NEW.state IN ('running','cancelled','fenced')) OR
            (OLD.state='running' AND NEW.state IN (
                'succeeded','failed_retryable','failed_terminal','cancelled','fenced'
            ))
        )
        BEGIN
            SELECT RAISE(ABORT, 'invalid attempt state transition');
        END;
CREATE TRIGGER fm_v2_candidate_revision_no_update
        BEFORE UPDATE ON fm_v2_candidate_revisions
        BEGIN
            SELECT RAISE(ABORT, 'candidate revisions are append-only');
        END;
CREATE TRIGGER fm_v2_candidate_revision_no_delete
        BEFORE DELETE ON fm_v2_candidate_revisions
        WHEN NOT EXISTS (
            SELECT 1 FROM fm_v2_privacy_erasure_context context
             WHERE context.owner_id=OLD.owner_id
        )
        BEGIN
            SELECT RAISE(ABORT, 'candidate revisions are append-only');
        END;
CREATE TRIGGER fm_v2_conflict_event_no_update
        BEFORE UPDATE ON fm_v2_conflict_events BEGIN
            SELECT RAISE(ABORT, 'conflict events are append-only');
        END;
CREATE TRIGGER fm_v2_conflict_event_no_delete
        BEFORE DELETE ON fm_v2_conflict_events
        WHEN NOT EXISTS (
            SELECT 1 FROM fm_v2_privacy_erasure_context context
             WHERE context.owner_id=OLD.owner_id
        )
        BEGIN
            SELECT RAISE(ABORT, 'conflict events are append-only');
        END;
CREATE TRIGGER fm_v2_job_event_no_update
        BEFORE UPDATE ON fm_v2_job_events BEGIN
            SELECT RAISE(ABORT, 'job events are append-only');
        END;
CREATE TRIGGER fm_v2_job_event_no_delete
        BEFORE DELETE ON fm_v2_job_events BEGIN
            SELECT RAISE(ABORT, 'job events are append-only');
        END;
CREATE TRIGGER fm_v2_knowledge_revision_no_update
        BEFORE UPDATE ON fm_v2_knowledge_revisions
        BEGIN
            SELECT RAISE(ABORT, 'knowledge revisions are append-only');
        END;
CREATE TRIGGER fm_v2_knowledge_revision_no_delete
        BEFORE DELETE ON fm_v2_knowledge_revisions
        WHEN NOT EXISTS (
            SELECT 1 FROM fm_v2_privacy_erasure_context context
             WHERE context.owner_id=OLD.owner_id
        )
        BEGIN
            SELECT RAISE(ABORT, 'knowledge revisions are append-only');
        END;
CREATE TRIGGER fm_v2_entity_revision_no_update
        BEFORE UPDATE ON fm_v2_entity_revisions
        BEGIN
            SELECT RAISE(ABORT, 'entity revisions are append-only');
        END;
CREATE TRIGGER fm_v2_entity_revision_no_delete
        BEFORE DELETE ON fm_v2_entity_revisions
        WHEN NOT EXISTS (
            SELECT 1 FROM fm_v2_privacy_erasure_context context
             WHERE context.owner_id=OLD.owner_id
        )
        BEGIN
            SELECT RAISE(ABORT, 'entity revisions are append-only');
        END;
CREATE TRIGGER graph_cues_fts_insert
                 AFTER INSERT ON graph_cues WHEN new.status = 'active' BEGIN
                   INSERT INTO graph_cues_fts(cue, node_id) VALUES (new.cue, new.node_id);
                 END;
CREATE TRIGGER graph_cues_fts_delete
                 AFTER DELETE ON graph_cues BEGIN
                   DELETE FROM graph_cues_fts WHERE cue = old.cue AND node_id = old.node_id;
                 END;
CREATE TRIGGER graph_cues_fts_status
                 AFTER UPDATE OF status ON graph_cues BEGIN
                   DELETE FROM graph_cues_fts WHERE cue = old.cue AND node_id = old.node_id;
                   INSERT INTO graph_cues_fts(cue, node_id)
                     SELECT new.cue, new.node_id WHERE new.status = 'active';
                 END;
INSERT OR IGNORE INTO fm_meta(key,value) VALUES ('database_id',lower(hex(randomblob(16)))),('canonical_contract_version','frankenmemory.v2'),('v2_schema_installed_at',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
PRAGMA user_version=14;
