// Comprehensive emoji data organized by Unicode 15.1 categories.
// ~650 of the most commonly used emoji with search keywords.

export interface EmojiEntry {
  char: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string; // category tab icon
  emojis: EmojiEntry[];
}

function e(char: string, name: string, keywords: string): EmojiEntry {
  return { char, name, keywords: keywords.split(' ') };
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'frequent',
    name: 'Frequently Used',
    icon: '🕐',
    emojis: [], // populated at runtime from localStorage
  },
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      e('😀', 'grinning face', 'grin smile happy'),
      e('😃', 'grinning face with big eyes', 'smile happy open mouth'),
      e('😄', 'grinning face with smiling eyes', 'smile happy laugh'),
      e('😁', 'beaming face with smiling eyes', 'grin smile happy'),
      e('😆', 'grinning squinting face', 'laugh happy xd squint'),
      e('😅', 'grinning face with sweat', 'sweat smile nervous'),
      e('🤣', 'rolling on the floor laughing', 'rofl lol laughing'),
      e('😂', 'face with tears of joy', 'cry laugh lol'),
      e('🙂', 'slightly smiling face', 'smile'),
      e('🙃', 'upside-down face', 'silly sarcastic'),
      e('😉', 'winking face', 'wink flirt'),
      e('😊', 'smiling face with smiling eyes', 'blush happy warm'),
      e('😇', 'smiling face with halo', 'angel innocent'),
      e('🥰', 'smiling face with hearts', 'love affection adore'),
      e('😍', 'smiling face with heart-eyes', 'love crush heart eyes'),
      e('🤩', 'star-struck', 'star eyes wow amazed'),
      e('😘', 'face blowing a kiss', 'kiss love wink'),
      e('😗', 'kissing face', 'kiss'),
      e('😚', 'kissing face with closed eyes', 'kiss blush'),
      e('😙', 'kissing face with smiling eyes', 'kiss smile'),
      e('🥲', 'smiling face with tear', 'sad smile bittersweet'),
      e('😋', 'face savoring food', 'yummy delicious tasty tongue'),
      e('😛', 'face with tongue', 'tongue silly playful'),
      e('😜', 'winking face with tongue', 'tongue wink silly crazy'),
      e('🤪', 'zany face', 'crazy silly goofy wild'),
      e('😝', 'squinting face with tongue', 'tongue silly gross'),
      e('🤑', 'money-mouth face', 'money rich dollar'),
      e('🤗', 'smiling face with open hands', 'hug love embrace'),
      e('🤭', 'face with hand over mouth', 'oops giggle shy'),
      e('🤫', 'shushing face', 'quiet secret shh silence'),
      e('🤔', 'thinking face', 'think hmm wonder ponder'),
      e('🫡', 'saluting face', 'salute respect yes sir'),
      e('🤐', 'zipper-mouth face', 'zip secret quiet lips sealed'),
      e('🤨', 'face with raised eyebrow', 'skeptical suspicious doubt'),
      e('😐', 'neutral face', 'meh blank indifferent'),
      e('😑', 'expressionless face', 'blank deadpan done'),
      e('😶', 'face without mouth', 'mute silent speechless'),
      e('🫥', 'dotted line face', 'invisible disappear hidden'),
      e('😏', 'smirking face', 'smirk suggestive flirt'),
      e('😒', 'unamused face', 'meh unimpressed annoyed'),
      e('🙄', 'face with rolling eyes', 'eyeroll annoyed whatever'),
      e('😬', 'grimacing face', 'awkward cringe yikes'),
      e('🤥', 'lying face', 'pinocchio lie dishonest'),
      e('🫠', 'melting face', 'melt hot embarrassed'),
      e('😌', 'relieved face', 'relief calm peaceful'),
      e('😔', 'pensive face', 'sad thoughtful reflective'),
      e('😪', 'sleepy face', 'tired sleepy tear'),
      e('🤤', 'drooling face', 'drool hungry yummy'),
      e('😴', 'sleeping face', 'sleep zzz tired'),
      e('😷', 'face with medical mask', 'sick mask ill covid'),
      e('🤒', 'face with thermometer', 'sick fever ill temperature'),
      e('🤕', 'face with head-bandage', 'hurt injured clumsy'),
      e('🤢', 'nauseated face', 'sick disgusted gross vomit'),
      e('🤮', 'face vomiting', 'vomit sick throw up gross'),
      e('🥵', 'hot face', 'hot sweating overheated'),
      e('🥶', 'cold face', 'cold freezing frozen'),
      e('🥴', 'woozy face', 'drunk dizzy tipsy intoxicated'),
      e('😵', 'face with crossed-out eyes', 'dizzy dead stunned'),
      e('🤯', 'exploding head', 'mind blown shocked amazed wow'),
      e('🤠', 'cowboy hat face', 'cowboy yeehaw western'),
      e('🥳', 'partying face', 'party celebrate birthday'),
      e('🥸', 'disguised face', 'disguise incognito glasses mustache'),
      e('😎', 'smiling face with sunglasses', 'cool sunglasses'),
      e('🤓', 'nerd face', 'nerd geek glasses smart'),
      e('🧐', 'face with monocle', 'monocle fancy sophisticated'),
      e('😕', 'confused face', 'confused puzzled'),
      e('🫤', 'face with diagonal mouth', 'skeptical unsure meh'),
      e('😟', 'worried face', 'worried concerned nervous'),
      e('🙁', 'slightly frowning face', 'frown sad disappointed'),
      e('☹️', 'frowning face', 'frown sad upset'),
      e('😮', 'face with open mouth', 'surprised wow gasp'),
      e('😯', 'hushed face', 'surprised stunned quiet'),
      e('😲', 'astonished face', 'shocked amazed wow'),
      e('😳', 'flushed face', 'embarrassed shocked blush'),
      e('🥺', 'pleading face', 'puppy eyes please beg'),
      e('🥹', 'face holding back tears', 'emotional touched proud'),
      e('😦', 'frowning face with open mouth', 'shocked aw'),
      e('😧', 'anguished face', 'anguish distressed'),
      e('😨', 'fearful face', 'scared afraid fearful'),
      e('😰', 'anxious face with sweat', 'nervous anxious worried'),
      e('😥', 'sad but relieved face', 'phew disappointed relieved'),
      e('😢', 'crying face', 'cry sad tear'),
      e('😭', 'loudly crying face', 'cry sob wail bawling'),
      e('😱', 'face screaming in fear', 'scream horror scared omg'),
      e('😖', 'confounded face', 'confounded frustrated'),
      e('😣', 'persevering face', 'struggle frustrated'),
      e('😞', 'disappointed face', 'sad disappointed down'),
      e('😓', 'downcast face with sweat', 'cold sweat hard work'),
      e('😩', 'weary face', 'tired exhausted fed up'),
      e('😫', 'tired face', 'tired exhausted frustrated'),
      e('🥱', 'yawning face', 'yawn bored tired sleepy'),
      e('😤', 'face with steam from nose', 'angry frustrated triumph'),
      e('😡', 'pouting face', 'angry mad rage red'),
      e('😠', 'angry face', 'angry mad grumpy'),
      e('🤬', 'face with symbols on mouth', 'swearing cursing angry'),
      e('😈', 'smiling face with horns', 'devil evil naughty'),
      e('👿', 'angry face with horns', 'devil evil angry demon'),
      e('💀', 'skull', 'dead death skeleton'),
      e('☠️', 'skull and crossbones', 'death danger poison pirate'),
      e('💩', 'pile of poo', 'poop crap poo'),
      e('🤡', 'clown face', 'clown silly fool'),
      e('👹', 'ogre', 'monster japanese oni'),
      e('👺', 'goblin', 'monster japanese tengu'),
      e('👻', 'ghost', 'ghost spooky halloween boo'),
      e('👽', 'alien', 'ufo extraterrestrial space'),
      e('👾', 'alien monster', 'space invader game pixel'),
      e('🤖', 'robot', 'robot machine bot'),
      e('😺', 'grinning cat', 'cat smile happy'),
      e('😸', 'grinning cat with smiling eyes', 'cat happy'),
      e('😹', 'cat with tears of joy', 'cat laugh joy'),
      e('😻', 'smiling cat with heart-eyes', 'cat love'),
      e('😼', 'cat with wry smile', 'cat smirk sarcastic'),
      e('😽', 'kissing cat', 'cat kiss'),
      e('🙀', 'weary cat', 'cat shocked omg'),
      e('😿', 'crying cat', 'cat sad tear'),
      e('😾', 'pouting cat', 'cat angry grumpy'),
      e('🙈', 'see-no-evil monkey', 'monkey shy hide'),
      e('🙉', 'hear-no-evil monkey', 'monkey deaf'),
      e('🙊', 'speak-no-evil monkey', 'monkey quiet oops'),
      e('💌', 'love letter', 'letter love heart mail'),
      e('💘', 'heart with arrow', 'love cupid crush'),
      e('💝', 'heart with ribbon', 'gift love valentine'),
      e('💖', 'sparkling heart', 'love sparkle shine'),
      e('💗', 'growing heart', 'love expanding'),
      e('💓', 'beating heart', 'love heartbeat'),
      e('💞', 'revolving hearts', 'love couple'),
      e('💕', 'two hearts', 'love couple'),
      e('💟', 'heart decoration', 'love decoration'),
      e('❣️', 'heart exclamation', 'love heavy heart'),
      e('💔', 'broken heart', 'sad heartbreak split'),
      e('❤️‍🔥', 'heart on fire', 'passion desire burning love'),
      e('❤️‍🩹', 'mending heart', 'healing recovery'),
      e('❤️', 'red heart', 'love like'),
      e('🩷', 'pink heart', 'love pink cute'),
      e('🧡', 'orange heart', 'love orange'),
      e('💛', 'yellow heart', 'love yellow friendship'),
      e('💚', 'green heart', 'love green nature'),
      e('💙', 'blue heart', 'love blue'),
      e('🩵', 'light blue heart', 'love light blue sky'),
      e('💜', 'purple heart', 'love purple'),
      e('🖤', 'black heart', 'dark love emo'),
      e('🩶', 'grey heart', 'grey neutral'),
      e('🤍', 'white heart', 'pure love white'),
      e('🤎', 'brown heart', 'love brown'),
      e('💋', 'kiss mark', 'kiss lips love'),
      e('💯', 'hundred points', 'perfect score 100'),
      e('💢', 'anger symbol', 'angry mad'),
      e('💥', 'collision', 'boom explosion crash'),
      e('💫', 'dizzy', 'stars spinning'),
      e('💦', 'sweat droplets', 'water splash'),
      e('💨', 'dashing away', 'fast wind running poof'),
      e('🕳️', 'hole', 'void pit'),
      e('💬', 'speech balloon', 'chat talk message'),
      e('🗨️', 'left speech bubble', 'chat talk'),
      e('🗯️', 'right anger bubble', 'angry chat'),
      e('💭', 'thought balloon', 'think bubble'),
      e('💤', 'zzz', 'sleep sleeping tired'),
    ],
  },
  {
    id: 'people',
    name: 'People & Body',
    icon: '👋',
    emojis: [
      e('👋', 'waving hand', 'wave hello hi bye'),
      e('🤚', 'raised back of hand', 'hand backhand'),
      e('🖐️', 'hand with fingers splayed', 'hand five fingers'),
      e('✋', 'raised hand', 'hand stop high five'),
      e('🖖', 'vulcan salute', 'spock star trek hand'),
      e('🫱', 'rightwards hand', 'hand right palm'),
      e('🫲', 'leftwards hand', 'hand left palm'),
      e('🫳', 'palm down hand', 'hand shoo dismiss'),
      e('🫴', 'palm up hand', 'hand offer beckon'),
      e('🫷', 'leftwards pushing hand', 'hand push stop reject'),
      e('🫸', 'rightwards pushing hand', 'hand push stop reject'),
      e('👌', 'OK hand', 'ok perfect okay'),
      e('🤌', 'pinched fingers', 'italian what chef kiss'),
      e('🤏', 'pinching hand', 'small tiny little bit'),
      e('✌️', 'victory hand', 'peace victory two'),
      e('🤞', 'crossed fingers', 'luck hope wish'),
      e('🫰', 'hand with index finger and thumb crossed', 'money snap heart'),
      e('🤟', 'love-you gesture', 'ily love rock'),
      e('🤘', 'sign of the horns', 'rock metal horns'),
      e('🤙', 'call me hand', 'call phone shaka'),
      e('👈', 'backhand index pointing left', 'left point'),
      e('👉', 'backhand index pointing right', 'right point'),
      e('👆', 'backhand index pointing up', 'up point'),
      e('🖕', 'middle finger', 'flip off rude'),
      e('👇', 'backhand index pointing down', 'down point'),
      e('☝️', 'index pointing up', 'up point one'),
      e('🫵', 'index pointing at the viewer', 'point you'),
      e('👍', 'thumbs up', 'like yes approve good'),
      e('👎', 'thumbs down', 'dislike no disapprove bad'),
      e('✊', 'raised fist', 'fist power solidarity'),
      e('👊', 'oncoming fist', 'punch fist bump hit'),
      e('🤛', 'left-facing fist', 'fist bump left'),
      e('🤜', 'right-facing fist', 'fist bump right'),
      e('👏', 'clapping hands', 'clap applause bravo'),
      e('🙌', 'raising hands', 'hooray celebration praise'),
      e('🫶', 'heart hands', 'love heart gesture'),
      e('👐', 'open hands', 'hands open jazz'),
      e('🤲', 'palms up together', 'prayer cupped hands'),
      e('🤝', 'handshake', 'deal agreement handshake'),
      e('🙏', 'folded hands', 'pray please thank hope'),
      e('✍️', 'writing hand', 'write pen'),
      e('💅', 'nail polish', 'nails beauty manicure'),
      e('🤳', 'selfie', 'phone camera selfie'),
      e('💪', 'flexed biceps', 'strong muscle flex gym'),
      e('🦾', 'mechanical arm', 'prosthetic robot'),
      e('🦿', 'mechanical leg', 'prosthetic robot'),
      e('🦵', 'leg', 'kick limb'),
      e('🦶', 'foot', 'kick stomp'),
      e('👂', 'ear', 'hear listen sound'),
      e('🦻', 'ear with hearing aid', 'deaf accessibility'),
      e('👃', 'nose', 'smell sniff'),
      e('🧠', 'brain', 'smart intelligence think'),
      e('🫀', 'anatomical heart', 'heart organ cardiac'),
      e('🫁', 'lungs', 'breath breathe respiratory'),
      e('🦷', 'tooth', 'dentist dental'),
      e('🦴', 'bone', 'skeleton'),
      e('👀', 'eyes', 'look see watch'),
      e('👁️', 'eye', 'see look vision'),
      e('👅', 'tongue', 'taste lick'),
      e('👄', 'mouth', 'lips kiss talk'),
      e('🫦', 'biting lip', 'nervous flirt anxious'),
      e('👶', 'baby', 'infant newborn child'),
      e('🧒', 'child', 'kid young'),
      e('👦', 'boy', 'child male kid'),
      e('👧', 'girl', 'child female kid'),
      e('🧑', 'person', 'adult human'),
      e('👱', 'person with blond hair', 'blonde hair'),
      e('👨', 'man', 'male adult'),
      e('🧔', 'person with beard', 'beard facial hair'),
      e('👩', 'woman', 'female adult'),
      e('🧓', 'older person', 'elder senior'),
      e('👴', 'old man', 'grandpa elderly'),
      e('👵', 'old woman', 'grandma elderly'),
      e('🙍', 'person frowning', 'sad upset'),
      e('🙎', 'person pouting', 'angry mad'),
      e('🙅', 'person gesturing NO', 'no deny refuse'),
      e('🙆', 'person gesturing OK', 'yes ok approve'),
      e('💁', 'person tipping hand', 'sassy information'),
      e('🙋', 'person raising hand', 'question volunteer'),
      e('🧏', 'deaf person', 'deaf accessibility'),
      e('🙇', 'person bowing', 'bow sorry respect'),
      e('🤦', 'person facepalming', 'facepalm omg disappointed'),
      e('🤷', 'person shrugging', 'shrug idk whatever'),
      e('🧑‍⚕️', 'health worker', 'doctor nurse medical'),
      e('🧑‍🎓', 'student', 'graduate school university'),
      e('🧑‍🏫', 'teacher', 'instructor professor'),
      e('🧑‍💻', 'technologist', 'developer programmer coder'),
      e('🧑‍🔬', 'scientist', 'researcher lab'),
      e('🧑‍🎨', 'artist', 'painter creative'),
      e('🧑‍🚀', 'astronaut', 'space nasa'),
      e('🧑‍🚒', 'firefighter', 'fire rescue'),
      e('🧑‍🍳', 'cook', 'chef cooking'),
      e('💃', 'woman dancing', 'dance party salsa'),
      e('🕺', 'man dancing', 'dance party disco'),
      e('👯', 'people with bunny ears', 'dance party bunny'),
      e('🧖', 'person in steamy room', 'sauna spa steam'),
      e('🧗', 'person climbing', 'rock climbing'),
      e('🏄', 'person surfing', 'surf beach wave'),
      e('🚣', 'person rowing boat', 'rowboat row'),
      e('🏊', 'person swimming', 'swim pool water'),
      e('🚴', 'person biking', 'bicycle cycling'),
      e('🧘', 'person in lotus position', 'yoga meditation zen'),
      e('👫', 'woman and man holding hands', 'couple date'),
      e('👬', 'men holding hands', 'couple'),
      e('👭', 'women holding hands', 'couple'),
      e('💏', 'kiss', 'couple love kiss'),
      e('💑', 'couple with heart', 'love couple romance'),
      e('👪', 'family', 'family home parents'),
      e('🫂', 'people hugging', 'hug comfort embrace'),
      e('👤', 'bust in silhouette', 'person user profile'),
      e('👥', 'busts in silhouette', 'people users group'),
      e('👣', 'footprints', 'steps walk feet'),
    ],
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    icon: '🐻',
    emojis: [
      e('🐶', 'dog face', 'dog puppy pet'),
      e('🐱', 'cat face', 'cat kitten pet'),
      e('🐭', 'mouse face', 'mouse rodent'),
      e('🐹', 'hamster', 'hamster pet rodent'),
      e('🐰', 'rabbit face', 'bunny rabbit pet'),
      e('🦊', 'fox', 'fox clever'),
      e('🐻', 'bear', 'bear teddy'),
      e('🐻‍❄️', 'polar bear', 'arctic white bear'),
      e('🐼', 'panda', 'panda bear china'),
      e('🐨', 'koala', 'koala australia'),
      e('🐯', 'tiger face', 'tiger cat'),
      e('🦁', 'lion', 'lion king pride'),
      e('🐮', 'cow face', 'cow farm moo'),
      e('🐷', 'pig face', 'pig farm oink'),
      e('🐸', 'frog', 'frog toad kermit'),
      e('🐵', 'monkey face', 'monkey ape'),
      e('🙈', 'see-no-evil monkey', 'shy hide'),
      e('🙉', 'hear-no-evil monkey', 'deaf'),
      e('🙊', 'speak-no-evil monkey', 'quiet'),
      e('🐔', 'chicken', 'chicken hen poultry'),
      e('🐧', 'penguin', 'penguin bird tux'),
      e('🐦', 'bird', 'bird tweet'),
      e('🐤', 'baby chick', 'chick bird baby'),
      e('🦆', 'duck', 'duck quack bird'),
      e('🦅', 'eagle', 'eagle bird america'),
      e('🦉', 'owl', 'owl wise night'),
      e('🦇', 'bat', 'bat vampire night'),
      e('🐺', 'wolf', 'wolf howl'),
      e('🐴', 'horse face', 'horse pony'),
      e('🦄', 'unicorn', 'unicorn magic fantasy'),
      e('🐝', 'honeybee', 'bee honey buzz'),
      e('🪱', 'worm', 'worm earthworm'),
      e('🐛', 'bug', 'bug insect caterpillar'),
      e('🦋', 'butterfly', 'butterfly insect beautiful'),
      e('🐌', 'snail', 'snail slow shell'),
      e('🐞', 'lady beetle', 'ladybug bug insect'),
      e('🐜', 'ant', 'ant bug insect'),
      e('🪰', 'fly', 'fly insect buzz'),
      e('🪲', 'beetle', 'beetle bug insect'),
      e('🪳', 'cockroach', 'roach bug insect'),
      e('🦟', 'mosquito', 'mosquito insect bite'),
      e('🦗', 'cricket', 'cricket insect chirp'),
      e('🕷️', 'spider', 'spider web insect'),
      e('🦂', 'scorpion', 'scorpion zodiac'),
      e('🐢', 'turtle', 'turtle tortoise slow'),
      e('🐍', 'snake', 'snake reptile'),
      e('🦎', 'lizard', 'lizard reptile gecko'),
      e('🦖', 'T-Rex', 'dinosaur trex'),
      e('🦕', 'sauropod', 'dinosaur brontosaurus'),
      e('🐙', 'octopus', 'octopus sea'),
      e('🦑', 'squid', 'squid calamari'),
      e('🦐', 'shrimp', 'shrimp prawn seafood'),
      e('🦞', 'lobster', 'lobster seafood'),
      e('🦀', 'crab', 'crab seafood'),
      e('🐡', 'blowfish', 'puffer fish'),
      e('🐠', 'tropical fish', 'fish nemo'),
      e('🐟', 'fish', 'fish seafood'),
      e('🐬', 'dolphin', 'dolphin ocean smart'),
      e('🐳', 'spouting whale', 'whale ocean'),
      e('🐋', 'whale', 'whale ocean big'),
      e('🦈', 'shark', 'shark jaw fin'),
      e('🐊', 'crocodile', 'croc alligator'),
      e('🐅', 'tiger', 'tiger cat stripe'),
      e('🐆', 'leopard', 'leopard cat spot'),
      e('🦓', 'zebra', 'zebra stripe'),
      e('🫏', 'donkey', 'donkey mule'),
      e('🦍', 'gorilla', 'gorilla ape'),
      e('🦧', 'orangutan', 'orangutan ape monkey'),
      e('🐘', 'elephant', 'elephant big trunk'),
      e('🦣', 'mammoth', 'mammoth extinct'),
      e('🦛', 'hippopotamus', 'hippo'),
      e('🦏', 'rhinoceros', 'rhino'),
      e('🐪', 'camel', 'camel desert hump'),
      e('🐫', 'two-hump camel', 'camel bactrian'),
      e('🦒', 'giraffe', 'giraffe tall spots'),
      e('🦘', 'kangaroo', 'kangaroo australia joey'),
      e('🦬', 'bison', 'bison buffalo'),
      e('🐃', 'water buffalo', 'buffalo'),
      e('🐂', 'ox', 'ox bull'),
      e('🐄', 'cow', 'cow farm milk'),
      e('🐎', 'horse', 'horse race'),
      e('🐖', 'pig', 'pig farm'),
      e('🐏', 'ram', 'ram sheep'),
      e('🐑', 'ewe', 'sheep lamb wool'),
      e('🦙', 'llama', 'llama alpaca'),
      e('🐐', 'goat', 'goat'),
      e('🦌', 'deer', 'deer bambi'),
      e('🐕', 'dog', 'dog pet'),
      e('🐩', 'poodle', 'poodle dog fancy'),
      e('🦮', 'guide dog', 'blind accessibility'),
      e('🐕‍🦺', 'service dog', 'service accessibility'),
      e('🐈', 'cat', 'cat pet'),
      e('🐈‍⬛', 'black cat', 'cat black unlucky'),
      e('🪶', 'feather', 'feather bird light'),
      e('🐓', 'rooster', 'rooster cock dawn'),
      e('🦃', 'turkey', 'turkey thanksgiving'),
      e('🦤', 'dodo', 'dodo extinct'),
      e('🦚', 'peacock', 'peacock bird beautiful'),
      e('🦜', 'parrot', 'parrot bird talk pirate'),
      e('🦢', 'swan', 'swan bird elegant'),
      e('🪿', 'goose', 'goose bird honk'),
      e('🦩', 'flamingo', 'flamingo pink bird'),
      e('🕊️', 'dove', 'peace bird'),
      e('🐇', 'rabbit', 'bunny rabbit'),
      e('🦝', 'raccoon', 'raccoon trash panda'),
      e('🦨', 'skunk', 'skunk stink'),
      e('🦡', 'badger', 'badger honey'),
      e('🦫', 'beaver', 'beaver dam'),
      e('🦦', 'otter', 'otter cute swim'),
      e('🦥', 'sloth', 'sloth lazy slow'),
      e('🐁', 'mouse', 'mouse rodent'),
      e('🐀', 'rat', 'rat rodent'),
      e('🐿️', 'chipmunk', 'squirrel chipmunk'),
      e('🦔', 'hedgehog', 'hedgehog spiky'),
      e('🐾', 'paw prints', 'paw pet animal feet'),
      e('🐉', 'dragon', 'dragon fantasy'),
      e('🐲', 'dragon face', 'dragon chinese'),
      e('🌵', 'cactus', 'cactus desert plant'),
      e('🎄', 'Christmas tree', 'christmas tree holiday'),
      e('🌲', 'evergreen tree', 'tree pine forest'),
      e('🌳', 'deciduous tree', 'tree nature'),
      e('🌴', 'palm tree', 'tropical beach vacation'),
      e('🪵', 'wood', 'log lumber'),
      e('🌱', 'seedling', 'plant grow sprout'),
      e('🌿', 'herb', 'herb plant green nature'),
      e('☘️', 'shamrock', 'irish clover luck'),
      e('🍀', 'four leaf clover', 'luck clover'),
      e('🎍', 'pine decoration', 'bamboo japanese'),
      e('🪴', 'potted plant', 'plant pot indoor'),
      e('🎋', 'tanabata tree', 'japanese star festival'),
      e('🍃', 'leaf fluttering in wind', 'leaf wind nature'),
      e('🍂', 'fallen leaf', 'autumn fall leaf'),
      e('🍁', 'maple leaf', 'canada autumn fall'),
      e('🪻', 'hyacinth', 'flower purple'),
      e('🪷', 'lotus', 'flower zen meditation'),
      e('🌺', 'hibiscus', 'flower tropical'),
      e('🌸', 'cherry blossom', 'flower sakura japan spring'),
      e('💐', 'bouquet', 'flowers gift romance'),
      e('🌷', 'tulip', 'flower spring'),
      e('🌹', 'rose', 'flower love romance'),
      e('🥀', 'wilted flower', 'dead flower sad'),
      e('🌻', 'sunflower', 'flower sun happy'),
      e('🌼', 'blossom', 'flower spring'),
      e('🌾', 'sheaf of rice', 'rice grain harvest'),
      e('🍄', 'mushroom', 'mushroom fungus'),
      e('🌰', 'chestnut', 'nut'),
      e('🪹', 'empty nest', 'nest bird empty'),
      e('🪺', 'nest with eggs', 'nest bird eggs'),
      e('🌍', 'globe showing Europe-Africa', 'earth world globe'),
      e('🌎', 'globe showing Americas', 'earth world globe america'),
      e('🌏', 'globe showing Asia-Australia', 'earth world globe asia'),
      e('🌑', 'new moon', 'moon dark night'),
      e('🌙', 'crescent moon', 'moon night sleep'),
      e('⭐', 'star', 'star night sky'),
      e('🌟', 'glowing star', 'star shine'),
      e('✨', 'sparkles', 'sparkle magic shine'),
      e('⚡', 'high voltage', 'lightning thunder electric'),
      e('🔥', 'fire', 'hot flame lit'),
      e('🌈', 'rainbow', 'rainbow colors pride'),
      e('☀️', 'sun', 'sun sunny bright'),
      e('🌤️', 'sun behind small cloud', 'partly cloudy'),
      e('⛅', 'sun behind cloud', 'partly cloudy'),
      e('🌧️', 'cloud with rain', 'rain rainy'),
      e('⛈️', 'cloud with lightning and rain', 'thunderstorm'),
      e('🌩️', 'cloud with lightning', 'thunder'),
      e('🌨️', 'cloud with snow', 'snow cold winter'),
      e('❄️', 'snowflake', 'snow cold winter frozen'),
      e('🌊', 'water wave', 'wave ocean sea'),
      e('💧', 'droplet', 'water rain drop'),
      e('💦', 'sweat droplets', 'water splash'),
      e('🫧', 'bubbles', 'bubble soap clean'),
      e('💨', 'dashing away', 'wind fast puff'),
      e('🌪️', 'tornado', 'tornado storm'),
      e('🌫️', 'fog', 'fog misty'),
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍕',
    emojis: [
      e('🍎', 'red apple', 'apple fruit'),
      e('🍐', 'pear', 'pear fruit green'),
      e('🍊', 'tangerine', 'orange mandarin citrus fruit'),
      e('🍋', 'lemon', 'lemon citrus sour'),
      e('🍌', 'banana', 'banana fruit yellow'),
      e('🍉', 'watermelon', 'watermelon fruit summer'),
      e('🍇', 'grapes', 'grape fruit wine'),
      e('🍓', 'strawberry', 'strawberry fruit berry'),
      e('🫐', 'blueberries', 'blueberry berry fruit'),
      e('🍈', 'melon', 'melon honeydew fruit'),
      e('🍒', 'cherries', 'cherry fruit'),
      e('🍑', 'peach', 'peach fruit butt'),
      e('🥭', 'mango', 'mango fruit tropical'),
      e('🍍', 'pineapple', 'pineapple fruit tropical'),
      e('🥥', 'coconut', 'coconut tropical palm'),
      e('🥝', 'kiwi fruit', 'kiwi fruit green'),
      e('🍅', 'tomato', 'tomato vegetable red'),
      e('🍆', 'eggplant', 'aubergine purple'),
      e('🥑', 'avocado', 'avocado guacamole green'),
      e('🫛', 'pea pod', 'peas green vegetable'),
      e('🥦', 'broccoli', 'broccoli vegetable green'),
      e('🥬', 'leafy green', 'lettuce salad kale'),
      e('🥒', 'cucumber', 'cucumber pickle'),
      e('🌶️', 'hot pepper', 'chili spicy pepper'),
      e('🫑', 'bell pepper', 'pepper capsicum'),
      e('🌽', 'ear of corn', 'corn maize'),
      e('🥕', 'carrot', 'carrot vegetable orange'),
      e('🫒', 'olive', 'olive green'),
      e('🧄', 'garlic', 'garlic cooking'),
      e('🧅', 'onion', 'onion cry cooking'),
      e('🥔', 'potato', 'potato spud'),
      e('🍠', 'roasted sweet potato', 'sweet potato yam'),
      e('🫘', 'beans', 'beans legume'),
      e('🥜', 'peanuts', 'peanut nut'),
      e('🍞', 'bread', 'bread toast loaf'),
      e('🥐', 'croissant', 'croissant french pastry'),
      e('🥖', 'baguette bread', 'baguette french bread'),
      e('🫓', 'flatbread', 'naan pita bread'),
      e('🥨', 'pretzel', 'pretzel snack'),
      e('🥯', 'bagel', 'bagel bread'),
      e('🥞', 'pancakes', 'pancake breakfast'),
      e('🧇', 'waffle', 'waffle breakfast'),
      e('🧀', 'cheese wedge', 'cheese dairy'),
      e('🍖', 'meat on bone', 'meat bone'),
      e('🍗', 'poultry leg', 'chicken drumstick leg'),
      e('🥩', 'cut of meat', 'steak beef'),
      e('🥓', 'bacon', 'bacon meat breakfast'),
      e('🍔', 'hamburger', 'burger fast food'),
      e('🍟', 'french fries', 'fries chips fast food'),
      e('🍕', 'pizza', 'pizza slice italian'),
      e('🌭', 'hot dog', 'hotdog sausage'),
      e('🥪', 'sandwich', 'sandwich sub'),
      e('🌮', 'taco', 'taco mexican'),
      e('🌯', 'burrito', 'burrito wrap mexican'),
      e('🫔', 'tamale', 'tamale mexican'),
      e('🥙', 'stuffed flatbread', 'falafel pita kebab'),
      e('🧆', 'falafel', 'falafel chickpea'),
      e('🥚', 'egg', 'egg breakfast'),
      e('🍳', 'cooking', 'egg frying pan breakfast'),
      e('🥘', 'shallow pan of food', 'cooking paella'),
      e('🍲', 'pot of food', 'stew soup'),
      e('🫕', 'fondue', 'fondue cheese chocolate'),
      e('🥣', 'bowl with spoon', 'cereal oatmeal soup'),
      e('🥗', 'green salad', 'salad healthy'),
      e('🍿', 'popcorn', 'popcorn movie snack'),
      e('🧈', 'butter', 'butter dairy'),
      e('🧂', 'salt', 'salt sodium'),
      e('🥫', 'canned food', 'can soup'),
      e('🍱', 'bento box', 'bento japanese lunch'),
      e('🍘', 'rice cracker', 'rice cracker japanese'),
      e('🍙', 'rice ball', 'onigiri japanese rice'),
      e('🍚', 'cooked rice', 'rice bowl'),
      e('🍛', 'curry rice', 'curry indian'),
      e('🍜', 'steaming bowl', 'ramen noodles soup'),
      e('🍝', 'spaghetti', 'pasta italian noodles'),
      e('🍠', 'roasted sweet potato', 'yam sweet potato'),
      e('🍢', 'oden', 'oden japanese skewer'),
      e('🍣', 'sushi', 'sushi japanese fish'),
      e('🍤', 'fried shrimp', 'shrimp tempura prawn'),
      e('🍥', 'fish cake with swirl', 'narutomaki fish cake'),
      e('🥮', 'moon cake', 'mooncake chinese'),
      e('🍡', 'dango', 'dango japanese sweet'),
      e('🥟', 'dumpling', 'dumpling gyoza potsticker'),
      e('🥠', 'fortune cookie', 'fortune cookie chinese'),
      e('🥡', 'takeout box', 'chinese food takeout'),
      e('🦀', 'crab', 'crab seafood'),
      e('🦞', 'lobster', 'lobster seafood'),
      e('🦐', 'shrimp', 'shrimp prawn'),
      e('🦑', 'squid', 'squid calamari'),
      e('🦪', 'oyster', 'oyster shellfish pearl'),
      e('🍦', 'soft ice cream', 'ice cream cone dessert'),
      e('🍧', 'shaved ice', 'snow cone dessert'),
      e('🍨', 'ice cream', 'ice cream sundae dessert'),
      e('🍩', 'doughnut', 'donut dessert sweet'),
      e('🍪', 'cookie', 'cookie biscuit dessert'),
      e('🎂', 'birthday cake', 'cake birthday party'),
      e('🍰', 'shortcake', 'cake slice dessert'),
      e('🧁', 'cupcake', 'cupcake muffin dessert'),
      e('🥧', 'pie', 'pie dessert'),
      e('🍫', 'chocolate bar', 'chocolate candy sweet'),
      e('🍬', 'candy', 'candy sweet'),
      e('🍭', 'lollipop', 'candy lollipop sweet'),
      e('🍮', 'custard', 'pudding flan dessert'),
      e('🍯', 'honey pot', 'honey bee sweet'),
      e('🍼', 'baby bottle', 'baby milk bottle'),
      e('🥛', 'glass of milk', 'milk dairy drink'),
      e('☕', 'hot beverage', 'coffee tea hot'),
      e('🫖', 'teapot', 'tea pot'),
      e('🍵', 'teacup without handle', 'tea green matcha'),
      e('🍶', 'sake', 'sake japanese rice wine'),
      e('🍾', 'bottle with popping cork', 'champagne celebrate'),
      e('🍷', 'wine glass', 'wine red drink'),
      e('🍸', 'cocktail glass', 'martini cocktail drink'),
      e('🍹', 'tropical drink', 'cocktail tropical umbrella'),
      e('🍺', 'beer mug', 'beer drink cheers'),
      e('🍻', 'clinking beer mugs', 'beer cheers toast'),
      e('🥂', 'clinking glasses', 'champagne cheers toast'),
      e('🥃', 'tumbler glass', 'whiskey bourbon scotch'),
      e('🫗', 'pouring liquid', 'pour water spill drink'),
      e('🥤', 'cup with straw', 'soda juice drink'),
      e('🧋', 'bubble tea', 'boba tea'),
      e('🧃', 'beverage box', 'juice box drink'),
      e('🧉', 'mate', 'mate yerba drink'),
      e('🧊', 'ice', 'ice cube cold frozen'),
      e('🥢', 'chopsticks', 'chopsticks asian food'),
      e('🍽️', 'fork and knife with plate', 'dining dinner'),
      e('🍴', 'fork and knife', 'cutlery dining food'),
      e('🥄', 'spoon', 'spoon utensil'),
    ],
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: '✈️',
    emojis: [
      e('🚗', 'automobile', 'car drive red'),
      e('🚕', 'taxi', 'taxi cab yellow'),
      e('🚙', 'sport utility vehicle', 'suv car blue'),
      e('🚌', 'bus', 'bus transit'),
      e('🚎', 'trolleybus', 'trolley bus electric'),
      e('🏎️', 'racing car', 'race car fast formula'),
      e('🚓', 'police car', 'police cop car'),
      e('🚑', 'ambulance', 'ambulance hospital emergency'),
      e('🚒', 'fire engine', 'fire truck'),
      e('🚐', 'minibus', 'van bus shuttle'),
      e('🛻', 'pickup truck', 'truck pickup'),
      e('🚚', 'delivery truck', 'truck delivery moving'),
      e('🚛', 'articulated lorry', 'truck semi'),
      e('🚜', 'tractor', 'tractor farm'),
      e('🏍️', 'motorcycle', 'motorcycle motorbike'),
      e('🛵', 'motor scooter', 'scooter vespa'),
      e('🚲', 'bicycle', 'bike cycling'),
      e('🛴', 'kick scooter', 'scooter'),
      e('🛹', 'skateboard', 'skateboard skate'),
      e('🛼', 'roller skate', 'skate rollerskate'),
      e('🚁', 'helicopter', 'helicopter chopper'),
      e('✈️', 'airplane', 'plane flight travel'),
      e('🛩️', 'small airplane', 'plane private'),
      e('🚀', 'rocket', 'rocket space launch'),
      e('🛸', 'flying saucer', 'ufo alien space'),
      e('🚢', 'ship', 'ship boat cruise'),
      e('⛵', 'sailboat', 'sail boat wind'),
      e('🚤', 'speedboat', 'boat fast motorboat'),
      e('🛥️', 'motor boat', 'boat yacht'),
      e('🛳️', 'passenger ship', 'cruise ship'),
      e('⚓', 'anchor', 'anchor ship boat'),
      e('🛶', 'canoe', 'canoe kayak paddle'),
      e('🚏', 'bus stop', 'bus stop transit'),
      e('🛤️', 'railway track', 'train tracks railroad'),
      e('⛽', 'fuel pump', 'gas fuel petrol station'),
      e('🚨', 'police car light', 'siren emergency'),
      e('🚥', 'horizontal traffic light', 'traffic light signal'),
      e('🚦', 'vertical traffic light', 'traffic light signal'),
      e('🛑', 'stop sign', 'stop sign octagon'),
      e('🚧', 'construction', 'construction barrier'),
      e('⚓', 'anchor', 'anchor nautical'),
      e('🛟', 'ring buoy', 'life saver rescue'),
      e('💺', 'seat', 'chair airplane seat'),
      e('🪝', 'hook', 'hook fishing'),
      e('🛜', 'wireless', 'wifi internet'),
      e('🗿', 'moai', 'easter island statue'),
      e('🗽', 'Statue of Liberty', 'liberty new york'),
      e('🗼', 'Tokyo tower', 'tokyo japan tower'),
      e('🏰', 'castle', 'castle medieval european'),
      e('🏯', 'Japanese castle', 'castle japan'),
      e('🏟️', 'stadium', 'stadium arena sports'),
      e('🎡', 'ferris wheel', 'ferris wheel fair carnival'),
      e('🎢', 'roller coaster', 'roller coaster amusement'),
      e('🎠', 'carousel horse', 'carousel horse merry-go-round'),
      e('⛲', 'fountain', 'fountain water park'),
      e('🏖️', 'beach with umbrella', 'beach sand sun vacation'),
      e('🏝️', 'desert island', 'island palm tree tropical'),
      e('🏔️', 'snow-capped mountain', 'mountain snow'),
      e('⛰️', 'mountain', 'mountain hill'),
      e('🌋', 'volcano', 'volcano eruption lava'),
      e('🏕️', 'camping', 'tent camping outdoors'),
      e('🏗️', 'building construction', 'construction crane'),
      e('🏠', 'house', 'house home'),
      e('🏡', 'house with garden', 'house garden home'),
      e('🏢', 'office building', 'office work building'),
      e('🏣', 'Japanese post office', 'post japan'),
      e('🏤', 'post office', 'post mail'),
      e('🏥', 'hospital', 'hospital medical'),
      e('🏦', 'bank', 'bank money finance'),
      e('🏨', 'hotel', 'hotel lodging'),
      e('🏩', 'love hotel', 'hotel love'),
      e('🏪', 'convenience store', 'store shop 7-eleven'),
      e('🏬', 'department store', 'store shop mall'),
      e('🏛️', 'classical building', 'museum government'),
      e('⛪', 'church', 'church religion christian'),
      e('🕌', 'mosque', 'mosque islam'),
      e('🕍', 'synagogue', 'synagogue jewish'),
      e('🛕', 'hindu temple', 'temple hindu'),
      e('🕋', 'kaaba', 'kaaba islam mecca'),
      e('⛩️', 'shinto shrine', 'shrine japan torii'),
      e('🌅', 'sunrise', 'sunrise morning dawn'),
      e('🌄', 'sunrise over mountains', 'sunrise morning'),
      e('🌇', 'sunset', 'sunset evening dusk'),
      e('🌆', 'cityscape at dusk', 'city dusk evening'),
      e('🌃', 'night with stars', 'night city stars'),
      e('🌉', 'bridge at night', 'bridge night city'),
      e('🌌', 'milky way', 'galaxy space stars'),
      e('🎆', 'fireworks', 'fireworks celebration'),
      e('🎇', 'sparkler', 'sparkler firework celebration'),
      e('🎑', 'moon viewing ceremony', 'moon japanese'),
    ],
  },
  {
    id: 'activities',
    name: 'Activities',
    icon: '⚽',
    emojis: [
      e('🎃', 'jack-o-lantern', 'halloween pumpkin'),
      e('🎄', 'Christmas tree', 'christmas tree holiday'),
      e('🎆', 'fireworks', 'fireworks celebration new year'),
      e('🎇', 'sparkler', 'sparkler firework'),
      e('🧨', 'firecracker', 'firecracker dynamite'),
      e('✨', 'sparkles', 'sparkle magic star'),
      e('🎈', 'balloon', 'balloon party birthday'),
      e('🎉', 'party popper', 'party celebrate confetti'),
      e('🎊', 'confetti ball', 'celebrate party'),
      e('🎋', 'tanabata tree', 'japanese star festival'),
      e('🎍', 'pine decoration', 'bamboo japanese new year'),
      e('🎎', 'Japanese dolls', 'dolls japanese hina'),
      e('🎏', 'carp streamer', 'koinobori japanese children'),
      e('🎐', 'wind chime', 'wind chime japanese'),
      e('🎑', 'moon viewing ceremony', 'moon japanese tsukimi'),
      e('🧧', 'red envelope', 'lucky money chinese'),
      e('🎀', 'ribbon', 'ribbon gift bow'),
      e('🎁', 'wrapped gift', 'gift present birthday'),
      e('🎗️', 'reminder ribbon', 'awareness ribbon'),
      e('🎟️', 'admission tickets', 'ticket event concert'),
      e('🎫', 'ticket', 'ticket admission event'),
      e('🎖️', 'military medal', 'medal honor'),
      e('🏆', 'trophy', 'trophy winner champion'),
      e('🏅', 'sports medal', 'medal sport gold'),
      e('🥇', '1st place medal', 'gold first winner'),
      e('🥈', '2nd place medal', 'silver second'),
      e('🥉', '3rd place medal', 'bronze third'),
      e('⚽', 'soccer ball', 'soccer football'),
      e('⚾', 'baseball', 'baseball sport'),
      e('🥎', 'softball', 'softball sport'),
      e('🏀', 'basketball', 'basketball sport'),
      e('🏐', 'volleyball', 'volleyball sport'),
      e('🏈', 'american football', 'football american'),
      e('🏉', 'rugby football', 'rugby sport'),
      e('🎾', 'tennis', 'tennis sport ball'),
      e('🥏', 'flying disc', 'frisbee disc'),
      e('🎳', 'bowling', 'bowling sport strike'),
      e('🏏', 'cricket game', 'cricket sport bat'),
      e('🏑', 'field hockey', 'hockey sport'),
      e('🏒', 'ice hockey', 'hockey sport puck'),
      e('🥍', 'lacrosse', 'lacrosse sport'),
      e('🏓', 'ping pong', 'table tennis sport'),
      e('🏸', 'badminton', 'badminton sport shuttlecock'),
      e('🥊', 'boxing glove', 'boxing fight sport'),
      e('🥋', 'martial arts uniform', 'karate judo martial arts'),
      e('🥅', 'goal net', 'goal sport net'),
      e('⛳', 'flag in hole', 'golf sport'),
      e('⛸️', 'ice skate', 'skating ice winter'),
      e('🎣', 'fishing pole', 'fishing rod fish'),
      e('🤿', 'diving mask', 'diving scuba snorkel'),
      e('🎿', 'skis', 'ski snow winter'),
      e('🛷', 'sled', 'sled sleigh snow'),
      e('🥌', 'curling stone', 'curling sport'),
      e('🎯', 'bullseye', 'target dart aim'),
      e('🪀', 'yo-yo', 'yo-yo toy'),
      e('🪁', 'kite', 'kite fly wind'),
      e('🔫', 'water pistol', 'gun water pistol'),
      e('🎱', 'pool 8 ball', 'billiards pool eight ball'),
      e('🎰', 'slot machine', 'casino gambling slot'),
      e('🎲', 'game die', 'dice game chance'),
      e('🧩', 'puzzle piece', 'puzzle jigsaw piece'),
      e('🧸', 'teddy bear', 'teddy bear stuffed toy'),
      e('🪅', 'piñata', 'pinata party candy'),
      e('🪆', 'nesting dolls', 'matryoshka russian dolls'),
      e('♠️', 'spade suit', 'spades cards poker'),
      e('♥️', 'heart suit', 'hearts cards poker'),
      e('♦️', 'diamond suit', 'diamonds cards poker'),
      e('♣️', 'club suit', 'clubs cards poker'),
      e('♟️', 'chess pawn', 'chess pawn strategy'),
      e('🃏', 'joker', 'joker card wild'),
      e('🀄', 'mahjong red dragon', 'mahjong tile'),
      e('🎴', 'flower playing cards', 'hanafuda japanese'),
      e('🎭', 'performing arts', 'theater drama masks'),
      e('🎨', 'artist palette', 'art paint palette'),
      e('🧵', 'thread', 'sewing needle thread'),
      e('🧶', 'yarn', 'knitting crochet ball'),
      e('🎪', 'circus tent', 'circus carnival big top'),
      e('🎤', 'microphone', 'mic karaoke sing'),
      e('🎧', 'headphone', 'headphones music listen'),
      e('🎼', 'musical score', 'music score sheet'),
      e('🎹', 'musical keyboard', 'piano keyboard music'),
      e('🥁', 'drum', 'drum drumsticks music'),
      e('🪘', 'long drum', 'drum bongo conga'),
      e('🎷', 'saxophone', 'sax jazz music'),
      e('🎺', 'trumpet', 'trumpet brass music'),
      e('🎸', 'guitar', 'guitar rock music'),
      e('🪕', 'banjo', 'banjo country music'),
      e('🎻', 'violin', 'violin fiddle classical'),
      e('🎲', 'game die', 'dice game'),
    ],
  },
  {
    id: 'objects',
    name: 'Objects',
    icon: '💡',
    emojis: [
      e('⌚', 'watch', 'watch time wrist'),
      e('📱', 'mobile phone', 'phone cell smartphone'),
      e('📲', 'mobile phone with arrow', 'phone receive call'),
      e('💻', 'laptop', 'computer laptop macbook'),
      e('⌨️', 'keyboard', 'keyboard type computer'),
      e('🖥️', 'desktop computer', 'computer monitor'),
      e('🖨️', 'printer', 'printer print paper'),
      e('🖱️', 'computer mouse', 'mouse click'),
      e('💽', 'computer disk', 'disk minidisk'),
      e('💾', 'floppy disk', 'floppy save disk'),
      e('💿', 'optical disk', 'cd disc'),
      e('📀', 'dvd', 'dvd disc movie'),
      e('🧮', 'abacus', 'abacus calculate math'),
      e('🎥', 'movie camera', 'camera film movie'),
      e('📷', 'camera', 'camera photo picture'),
      e('📸', 'camera with flash', 'camera photo flash'),
      e('📹', 'video camera', 'video camcorder'),
      e('📽️', 'film projector', 'movie projector film'),
      e('🎬', 'clapper board', 'movie film action'),
      e('📺', 'television', 'tv screen watch'),
      e('📻', 'radio', 'radio music broadcast'),
      e('🧭', 'compass', 'compass direction navigation'),
      e('⏱️', 'stopwatch', 'stopwatch timer'),
      e('⏲️', 'timer clock', 'timer countdown'),
      e('⏰', 'alarm clock', 'alarm clock wake'),
      e('🕰️', 'mantelpiece clock', 'clock time'),
      e('⌛', 'hourglass done', 'hourglass time done'),
      e('⏳', 'hourglass not done', 'hourglass time waiting'),
      e('📡', 'satellite antenna', 'satellite dish signal'),
      e('🔋', 'battery', 'battery power charge'),
      e('🪫', 'low battery', 'battery low power'),
      e('🔌', 'electric plug', 'plug power electric'),
      e('💡', 'light bulb', 'idea light bulb bright'),
      e('🔦', 'flashlight', 'flashlight torch light'),
      e('🕯️', 'candle', 'candle light fire'),
      e('🧯', 'fire extinguisher', 'fire extinguisher safety'),
      e('🗑️', 'wastebasket', 'trash garbage bin'),
      e('🛢️', 'oil drum', 'oil drum barrel'),
      e('💸', 'money with wings', 'money fly waste spend'),
      e('💵', 'dollar banknote', 'money dollar bill'),
      e('💴', 'yen banknote', 'money yen japan'),
      e('💶', 'euro banknote', 'money euro europe'),
      e('💷', 'pound banknote', 'money pound uk'),
      e('🪙', 'coin', 'coin money gold'),
      e('💰', 'money bag', 'money bag rich'),
      e('💳', 'credit card', 'card credit payment'),
      e('💎', 'gem stone', 'diamond gem jewel'),
      e('⚖️', 'balance scale', 'scale justice balance law'),
      e('🔧', 'wrench', 'wrench tool fix'),
      e('🔨', 'hammer', 'hammer tool build'),
      e('⚒️', 'hammer and pick', 'tool work'),
      e('🛠️', 'hammer and wrench', 'tools fix build'),
      e('⛏️', 'pick', 'pickaxe mining tool'),
      e('🪚', 'carpentry saw', 'saw wood cut'),
      e('🔩', 'nut and bolt', 'bolt screw hardware'),
      e('⚙️', 'gear', 'gear settings cog'),
      e('🗜️', 'clamp', 'clamp compress tool'),
      e('⚖️', 'balance scale', 'scale balance justice'),
      e('🦯', 'white cane', 'blind accessibility'),
      e('🔗', 'link', 'link chain url'),
      e('⛓️', 'chains', 'chain link locked'),
      e('🪝', 'hook', 'hook fishing'),
      e('🧰', 'toolbox', 'toolbox tools'),
      e('🧲', 'magnet', 'magnet horseshoe attract'),
      e('🪜', 'ladder', 'ladder climb'),
      e('⚗️', 'alembic', 'chemistry distill'),
      e('🧪', 'test tube', 'science lab chemistry'),
      e('🧫', 'petri dish', 'science lab biology'),
      e('🧬', 'dna', 'dna genetics biology'),
      e('🔬', 'microscope', 'science lab microscope'),
      e('🔭', 'telescope', 'telescope astronomy space'),
      e('📐', 'triangular ruler', 'ruler math geometry'),
      e('📏', 'straight ruler', 'ruler measure'),
      e('🧮', 'abacus', 'abacus calculate math'),
      e('🔒', 'locked', 'lock secure private'),
      e('🔓', 'unlocked', 'lock open unlock'),
      e('🔏', 'locked with pen', 'lock pen secure'),
      e('🔐', 'locked with key', 'lock key secure'),
      e('🔑', 'key', 'key unlock access'),
      e('🗝️', 'old key', 'key vintage antique'),
      e('🛡️', 'shield', 'shield defense protection'),
      e('🗡️', 'dagger', 'sword blade weapon'),
      e('⚔️', 'crossed swords', 'swords battle weapon'),
      e('🏹', 'bow and arrow', 'archery bow arrow'),
      e('🪃', 'boomerang', 'boomerang australia'),
      e('🧨', 'firecracker', 'dynamite explosive'),
      e('💣', 'bomb', 'bomb explosive'),
      e('🪤', 'mouse trap', 'trap mouse catch'),
      e('📦', 'package', 'box package delivery'),
      e('🏷️', 'label', 'label tag price'),
      e('🔖', 'bookmark', 'bookmark save tag'),
      e('🗂️', 'card index dividers', 'divider organize'),
      e('📁', 'file folder', 'folder file directory'),
      e('📂', 'open file folder', 'folder open file'),
      e('🗑️', 'wastebasket', 'trash garbage delete'),
      e('📋', 'clipboard', 'clipboard paste copy'),
      e('📌', 'pushpin', 'pin tack note'),
      e('📎', 'paperclip', 'clip attach'),
      e('🖇️', 'linked paperclips', 'clips linked'),
      e('📏', 'straight ruler', 'ruler measure straight'),
      e('📐', 'triangular ruler', 'ruler triangle geometry'),
      e('✂️', 'scissors', 'cut scissors'),
      e('🖊️', 'pen', 'pen write'),
      e('🖋️', 'fountain pen', 'pen write fancy'),
      e('✒️', 'black nib', 'pen nib write'),
      e('🖌️', 'paintbrush', 'brush paint art'),
      e('🖍️', 'crayon', 'crayon draw color'),
      e('📝', 'memo', 'note write memo'),
      e('✏️', 'pencil', 'pencil write draw'),
      e('🔍', 'magnifying glass tilted left', 'search find zoom'),
      e('🔎', 'magnifying glass tilted right', 'search find zoom'),
      e('❤️‍🔥', 'heart on fire', 'passion love burning'),
      e('❤️‍🩹', 'mending heart', 'healing recovery'),
      e('🕯️', 'candle', 'candle light fire'),
      e('💰', 'money bag', 'money bag rich'),
      e('🪪', 'identification card', 'id card identity'),
      e('📜', 'scroll', 'scroll paper document'),
      e('📃', 'page with curl', 'document page'),
      e('📄', 'page facing up', 'document page paper'),
      e('📑', 'bookmark tabs', 'bookmark tabs'),
      e('📊', 'bar chart', 'chart graph stats'),
      e('📈', 'chart increasing', 'chart up growth'),
      e('📉', 'chart decreasing', 'chart down decline'),
      e('🗒️', 'spiral notepad', 'notepad note'),
      e('🗓️', 'spiral calendar', 'calendar date'),
      e('📆', 'tear-off calendar', 'calendar date day'),
      e('📅', 'calendar', 'calendar date schedule'),
      e('📇', 'card index', 'index card rolodex'),
      e('🗃️', 'card file box', 'file box organize'),
      e('🗄️', 'file cabinet', 'cabinet file storage'),
      e('🗳️', 'ballot box with ballot', 'vote election'),
      e('🗄️', 'file cabinet', 'cabinet file storage'),
    ],
  },
  {
    id: 'symbols',
    name: 'Symbols',
    icon: '💲',
    emojis: [
      e('❤️', 'red heart', 'heart love like'),
      e('🧡', 'orange heart', 'heart love'),
      e('💛', 'yellow heart', 'heart love friendship'),
      e('💚', 'green heart', 'heart love nature'),
      e('💙', 'blue heart', 'heart love'),
      e('💜', 'purple heart', 'heart love'),
      e('🖤', 'black heart', 'heart dark emo'),
      e('🤎', 'brown heart', 'heart love'),
      e('🤍', 'white heart', 'heart pure love'),
      e('💔', 'broken heart', 'heart sad break'),
      e('❣️', 'heart exclamation', 'heart heavy'),
      e('💕', 'two hearts', 'heart love couple'),
      e('💞', 'revolving hearts', 'heart love'),
      e('💓', 'beating heart', 'heart love beat'),
      e('💗', 'growing heart', 'heart love grow'),
      e('💖', 'sparkling heart', 'heart love sparkle'),
      e('💘', 'heart with arrow', 'heart love cupid'),
      e('💝', 'heart with ribbon', 'heart love gift'),
      e('💟', 'heart decoration', 'heart love decor'),
      e('☮️', 'peace symbol', 'peace hippie'),
      e('✝️', 'latin cross', 'cross christian religion'),
      e('☪️', 'star and crescent', 'islam muslim'),
      e('🕉️', 'om', 'om hindu buddhist'),
      e('☯️', 'yin yang', 'balance harmony'),
      e('✡️', 'star of David', 'jewish star'),
      e('🔯', 'dotted six-pointed star', 'star jewish'),
      e('♈', 'Aries', 'aries zodiac astrology'),
      e('♉', 'Taurus', 'taurus zodiac astrology'),
      e('♊', 'Gemini', 'gemini zodiac astrology'),
      e('♋', 'Cancer', 'cancer zodiac astrology'),
      e('♌', 'Leo', 'leo zodiac astrology'),
      e('♍', 'Virgo', 'virgo zodiac astrology'),
      e('♎', 'Libra', 'libra zodiac astrology'),
      e('♏', 'Scorpio', 'scorpio zodiac astrology'),
      e('♐', 'Sagittarius', 'sagittarius zodiac astrology'),
      e('♑', 'Capricorn', 'capricorn zodiac astrology'),
      e('♒', 'Aquarius', 'aquarius zodiac astrology'),
      e('♓', 'Pisces', 'pisces zodiac astrology'),
      e('⛎', 'Ophiuchus', 'ophiuchus zodiac'),
      e('🆔', 'ID button', 'id identity'),
      e('⚛️', 'atom symbol', 'atom science'),
      e('🈳', 'Japanese vacancy button', 'japanese kanji'),
      e('🈹', 'Japanese discount button', 'japanese discount'),
      e('☢️', 'radioactive', 'radioactive nuclear danger'),
      e('☣️', 'biohazard', 'biohazard danger toxic'),
      e('📴', 'mobile phone off', 'phone off silent'),
      e('📳', 'vibration mode', 'phone vibrate'),
      e('🈶', 'Japanese "not free of charge" button', 'japanese'),
      e('🈚', 'Japanese "free of charge" button', 'japanese free'),
      e('🈸', 'Japanese "application" button', 'japanese apply'),
      e('🈺', 'Japanese "open for business" button', 'japanese open'),
      e('🉐', 'Japanese "bargain" button', 'japanese bargain'),
      e('✴️', 'eight-pointed star', 'star eight'),
      e('🆚', 'VS button', 'versus vs battle'),
      e('🉑', 'Japanese "acceptable" button', 'japanese accept'),
      e('💮', 'white flower', 'flower brilliant'),
      e('🈴', 'Japanese "passing grade" button', 'japanese pass'),
      e('🈵', 'Japanese "no vacancy" button', 'japanese full'),
      e('🈲', 'Japanese "prohibited" button', 'japanese prohibit'),
      e('🅰️', 'A button', 'a blood type'),
      e('🅱️', 'B button', 'b blood type'),
      e('🆎', 'AB button', 'ab blood type'),
      e('🆑', 'CL button', 'cl clear'),
      e('🅾️', 'O button', 'o blood type'),
      e('🆘', 'SOS button', 'sos help emergency'),
      e('❌', 'cross mark', 'no wrong delete'),
      e('⭕', 'hollow red circle', 'circle ring correct'),
      e('🛑', 'stop sign', 'stop halt'),
      e('⛔', 'no entry', 'stop prohibited'),
      e('📛', 'name badge', 'name badge'),
      e('🚫', 'prohibited', 'no banned forbidden'),
      e('💯', 'hundred points', '100 perfect score'),
      e('💢', 'anger symbol', 'angry mad'),
      e('♨️', 'hot springs', 'hot springs onsen'),
      e('🚷', 'no pedestrians', 'no walking'),
      e('🚯', 'no littering', 'no trash'),
      e('🚳', 'no bicycles', 'no bike'),
      e('🚱', 'non-potable water', 'no drinking water'),
      e('🔞', 'no one under eighteen', '18+ adult'),
      e('📵', 'no mobile phones', 'no phone silent'),
      e('🔇', 'muted speaker', 'mute silent quiet'),
      e('🔕', 'bell with slash', 'mute no notification'),
      e('✅', 'check mark button', 'check yes done correct'),
      e('☑️', 'check box with check', 'check done yes'),
      e('✔️', 'check mark', 'check done yes correct'),
      e('❗', 'red exclamation mark', 'exclamation warning alert'),
      e('❕', 'white exclamation mark', 'exclamation'),
      e('❓', 'red question mark', 'question help'),
      e('❔', 'white question mark', 'question'),
      e('‼️', 'double exclamation mark', 'exclamation bang bang'),
      e('⁉️', 'exclamation question mark', 'exclamation question'),
      e('〰️', 'wavy dash', 'wave dash'),
      e('©️', 'copyright', 'copyright c'),
      e('®️', 'registered', 'registered r'),
      e('™️', 'trade mark', 'trademark tm'),
      e('#️⃣', 'keycap number sign', 'hashtag number pound'),
      e('*️⃣', 'keycap asterisk', 'star asterisk'),
      e('0️⃣', 'keycap 0', 'zero 0'),
      e('1️⃣', 'keycap 1', 'one 1'),
      e('2️⃣', 'keycap 2', 'two 2'),
      e('3️⃣', 'keycap 3', 'three 3'),
      e('4️⃣', 'keycap 4', 'four 4'),
      e('5️⃣', 'keycap 5', 'five 5'),
      e('6️⃣', 'keycap 6', 'six 6'),
      e('7️⃣', 'keycap 7', 'seven 7'),
      e('8️⃣', 'keycap 8', 'eight 8'),
      e('9️⃣', 'keycap 9', 'nine 9'),
      e('🔟', 'keycap 10', 'ten 10'),
      e('🔠', 'input latin uppercase', 'uppercase abc'),
      e('🔡', 'input latin lowercase', 'lowercase abc'),
      e('🔢', 'input numbers', 'numbers 123'),
      e('🔣', 'input symbols', 'symbols'),
      e('🔤', 'input latin letters', 'letters abc'),
      e('🆎', 'AB button', 'ab blood type'),
      e('🆑', 'CL button', 'cl clear'),
      e('🆒', 'COOL button', 'cool'),
      e('🆓', 'FREE button', 'free'),
      e('ℹ️', 'information', 'info information i'),
      e('🆔', 'ID button', 'id identity'),
      e('Ⓜ️', 'circled M', 'm metro'),
      e('🆕', 'NEW button', 'new'),
      e('🆖', 'NG button', 'ng no good'),
      e('🅾️', 'O button', 'o blood type'),
      e('🆗', 'OK button', 'ok okay'),
      e('🅿️', 'P button', 'parking p'),
      e('🆘', 'SOS button', 'sos help emergency'),
      e('🆙', 'UP! button', 'up'),
      e('🆚', 'VS button', 'versus vs battle'),
      e('🈁', 'Japanese "here" button', 'japanese here'),
      e('🈂️', 'Japanese "service charge" button', 'japanese service'),
      e('🈷️', 'Japanese "monthly amount" button', 'japanese monthly'),
      e('🈶', 'Japanese "not free of charge" button', 'japanese paid'),
      e('🈯', 'Japanese "reserved" button', 'japanese reserved'),
      e('🉐', 'Japanese "bargain" button', 'japanese bargain'),
      e('🈹', 'Japanese "discount" button', 'japanese discount'),
      e('🈚', 'Japanese "free of charge" button', 'japanese free'),
      e('🈲', 'Japanese "prohibited" button', 'japanese prohibited'),
      e('🉑', 'Japanese "acceptable" button', 'japanese accept'),
      e('🈸', 'Japanese "application" button', 'japanese apply'),
      e('🈴', 'Japanese "passing grade" button', 'japanese pass'),
      e('🈳', 'Japanese "vacancy" button', 'japanese vacancy'),
      e('㊗️', 'Japanese "congratulations" button', 'japanese congrats'),
      e('㊙️', 'Japanese "secret" button', 'japanese secret'),
      e('🈺', 'Japanese "open for business" button', 'japanese open'),
      e('🈵', 'Japanese "no vacancy" button', 'japanese full'),
      e('🔴', 'red circle', 'red circle dot'),
      e('🟠', 'orange circle', 'orange circle dot'),
      e('🟡', 'yellow circle', 'yellow circle dot'),
      e('🟢', 'green circle', 'green circle dot'),
      e('🔵', 'blue circle', 'blue circle dot'),
      e('🟣', 'purple circle', 'purple circle dot'),
      e('🟤', 'brown circle', 'brown circle dot'),
      e('⚫', 'black circle', 'black circle dot'),
      e('⚪', 'white circle', 'white circle dot'),
      e('🟥', 'red square', 'red square'),
      e('🟧', 'orange square', 'orange square'),
      e('🟨', 'yellow square', 'yellow square'),
      e('🟩', 'green square', 'green square'),
      e('🟦', 'blue square', 'blue square'),
      e('🟪', 'purple square', 'purple square'),
      e('🟫', 'brown square', 'brown square'),
      e('⬛', 'black large square', 'black square'),
      e('⬜', 'white large square', 'white square'),
      e('🔶', 'large orange diamond', 'orange diamond'),
      e('🔷', 'large blue diamond', 'blue diamond'),
      e('🔸', 'small orange diamond', 'orange diamond small'),
      e('🔹', 'small blue diamond', 'blue diamond small'),
      e('🔺', 'red triangle pointed up', 'red triangle up'),
      e('🔻', 'red triangle pointed down', 'red triangle down'),
      e('💠', 'diamond with a dot', 'diamond fancy'),
      e('🔘', 'radio button', 'radio button select'),
      e('🔳', 'white square button', 'square white button'),
      e('🔲', 'black square button', 'square black button'),
    ],
  },
  {
    id: 'flags',
    name: 'Flags',
    icon: '🏁',
    emojis: [
      e('🏁', 'chequered flag', 'checkered flag race finish'),
      e('🚩', 'triangular flag', 'flag red post'),
      e('🎌', 'crossed flags', 'flags japanese'),
      e('🏴', 'black flag', 'flag black'),
      e('🏳️', 'white flag', 'flag surrender peace'),
      e('🏳️‍🌈', 'rainbow flag', 'pride lgbtq rainbow'),
      e('🏳️‍⚧️', 'transgender flag', 'trans pride transgender'),
      e('🏴‍☠️', 'pirate flag', 'pirate skull jolly roger'),
      e('🇺🇸', 'flag United States', 'usa america flag'),
      e('🇬🇧', 'flag United Kingdom', 'uk britain flag'),
      e('🇨🇦', 'flag Canada', 'canada flag'),
      e('🇦🇺', 'flag Australia', 'australia flag'),
      e('🇩🇪', 'flag Germany', 'germany flag'),
      e('🇫🇷', 'flag France', 'france flag'),
      e('🇮🇹', 'flag Italy', 'italy flag'),
      e('🇪🇸', 'flag Spain', 'spain flag'),
      e('🇯🇵', 'flag Japan', 'japan flag'),
      e('🇰🇷', 'flag South Korea', 'korea flag'),
      e('🇨🇳', 'flag China', 'china flag'),
      e('🇮🇳', 'flag India', 'india flag'),
      e('🇧🇷', 'flag Brazil', 'brazil flag'),
      e('🇲🇽', 'flag Mexico', 'mexico flag'),
      e('🇷🇺', 'flag Russia', 'russia flag'),
      e('🇸🇪', 'flag Sweden', 'sweden flag'),
      e('🇳🇴', 'flag Norway', 'norway flag'),
      e('🇫🇮', 'flag Finland', 'finland flag'),
      e('🇩🇰', 'flag Denmark', 'denmark flag'),
      e('🇳🇱', 'flag Netherlands', 'netherlands dutch flag'),
      e('🇧🇪', 'flag Belgium', 'belgium flag'),
      e('🇨🇭', 'flag Switzerland', 'switzerland flag'),
      e('🇦🇹', 'flag Austria', 'austria flag'),
      e('🇵🇹', 'flag Portugal', 'portugal flag'),
      e('🇬🇷', 'flag Greece', 'greece flag'),
      e('🇹🇷', 'flag Turkey', 'turkey flag'),
      e('🇮🇱', 'flag Israel', 'israel flag'),
      e('🇸🇦', 'flag Saudi Arabia', 'saudi arabia flag'),
      e('🇦🇪', 'flag United Arab Emirates', 'uae dubai flag'),
      e('🇪🇬', 'flag Egypt', 'egypt flag'),
      e('🇿🇦', 'flag South Africa', 'south africa flag'),
      e('🇳🇬', 'flag Nigeria', 'nigeria flag'),
      e('🇰🇪', 'flag Kenya', 'kenya flag'),
      e('🇹🇭', 'flag Thailand', 'thailand flag'),
      e('🇻🇳', 'flag Vietnam', 'vietnam flag'),
      e('🇵🇭', 'flag Philippines', 'philippines flag'),
      e('🇮🇩', 'flag Indonesia', 'indonesia flag'),
      e('🇲🇾', 'flag Malaysia', 'malaysia flag'),
      e('🇸🇬', 'flag Singapore', 'singapore flag'),
      e('🇳🇿', 'flag New Zealand', 'new zealand flag'),
      e('🇨🇱', 'flag Chile', 'chile flag'),
      e('🇦🇷', 'flag Argentina', 'argentina flag'),
      e('🇨🇴', 'flag Colombia', 'colombia flag'),
      e('🇵🇪', 'flag Peru', 'peru flag'),
    ],
  },
];

// Build a flat search index from all categories (excluding frequent).
export const ALL_EMOJI_SEARCH_INDEX: EmojiEntry[] = EMOJI_CATEGORIES.flatMap(
  (cat) => (cat.id === 'frequent' ? [] : cat.emojis),
);
