#!/usr/bin/env bun

import { Script } from "@mimo-ai/script"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

await import("./generate.ts")

// Generate src/ext/_manifest.ts (same logic as build.ts). Create the dir when
// missing so a fresh clone with no local extensions still emits an empty
// manifest — plugin/index.ts imports "../ext/_manifest" with a fixed specifier
// that must resolve at bundle time (a filesystem scan does not work once bundled).
const extDir = path.join(dir, "src", "ext")
const createdExtDir = !fs.existsSync(extDir)
if (createdExtDir) fs.mkdirSync(extDir, { recursive: true })
const extFiles = fs.readdirSync(extDir)
  .filter((f) => f.endsWith(".ts") && !f.endsWith(".d.ts") && f !== "_manifest.ts")
  .sort()
const manifestImports = extFiles.map((f, i) => `import * as m${i} from "./${f.replace(/\.ts$/, "")}"`).join("\n")
const manifestEntries = extFiles.map((f, i) => `  ["${f.replace(/\.ts$/, "")}", m${i}],`).join("\n")
fs.writeFileSync(
  path.join(extDir, "_manifest.ts"),
  `// Generated by script/build-node.ts. Do not edit.\n${manifestImports}\nexport const modules: Record<string, Record<string, unknown>> = Object.fromEntries([\n${manifestEntries}\n])\n`,
)
if (extFiles.length) console.log(`Generated ext/_manifest.ts (${extFiles.length} modules)`)
process.on("exit", () => {
  try {
    if (createdExtDir) fs.rmSync(extDir, { recursive: true, force: true })
    else fs.rmSync(path.join(extDir, "_manifest.ts"), { force: true })
  } catch {}
})

// Load migrations from migration directories


await Bun.build({
  target: "node",
  entrypoints: ["./src/node.ts"],
  outdir: "./dist/node",
  format: "esm",
  sourcemap: "linked",
  external: ["jsonc-parser", "@lydell/node-pty"],
  define: {
    MIMOCODE_CHANNEL: `'${Script.channel}'`,
  },
  files: {
    "opencode-web-ui.gen.ts": "",
  },
})

console.log("Build complete")
