import path from "path"
import { validateCatalog } from "../src/provider/models-schema"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

// Builds are deliberately offline with respect to models.dev. Refreshing the
// tracked catalog is a reviewed source update, never an ambient build input.
const modelsInput = path.join(dir, "test", "tool", "fixtures", "models-api.json")
const modelsData = await Bun.file(modelsInput).text()
const snapshot = validateCatalog(JSON.parse(modelsData))
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${JSON.stringify(snapshot)}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log(`Generated models-snapshot.js from ${modelsInput}`)
